{
 "title": "cron-manager",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"cron-manager\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Rate запуска новых задач (Job)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cronmanager_running_jobs{instance=\"$instance\"}[1m])",
     "legendFormat": "{{ task_type }}"
    }
   ]
  },
  {
   "title": "Rate статусов задач (Job)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cronmanager_job_statuses_total{instance=\"$instance\"}[1m])",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Активные задачи (Job)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cronmanager_running_jobs", "legendFormat": "{{task_type}}" }
   ]
  },
  {
   "title": "Продолжительность выполнения задач (Job)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(cronmanager_job_duration_seconds_sum{instance=\"$instance\"}[1m]) / rate(cronmanager_job_duration_seconds_count{instance=\"$instance\"}[1m])",
     "legendFormat": "{{ task_type }}"
    }
   ]
  },
  {
   "title": "Активные задачи (SSH)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cronmanager_running_ssh_tasks", "legendFormat": "{{task_type}}" }
   ]
  },
  {
   "title": "Продолжительность выполнения задач (SSH)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(cronmanager_ssh_task_duration_seconds_sum{instance=\"$instance\"}[1m]) / rate(cronmanager_ssh_task_duration_seconds_count{instance=\"$instance\"}[1m])",
     "legendFormat": "{{ task_type }}"
    }
   ]
  }
 ]
}