{
 "title": "monitoring-service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"monitoring-service\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"monitoring-service\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"monitoring-service\", area=\"heap\", instance=~\"$instance\"}) / sum(jvm_memory_max_bytes{application=\"monitoring-service\", area=\"heap\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU Usage (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"monitoring-service\", instance=~\"$instance\"}",
     "legendFormat": "Process (5m)"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"monitoring-service\", area=\"heap\", instance=~\"$instance\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"monitoring-service\", area=\"heap\", instance=~\"$instance\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"monitoring-service\", area=\"heap\", instance=~\"$instance\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live{application=\"monitoring-service\", instance=~\"$instance\"} or jvm_threads_live_threads{application=\"monitoring-service\", instance=~\"$instance\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon{application=\"monitoring-service\", instance=~\"$instance\"} or jvm_threads_daemon_threads{application=\"monitoring-service\", instance=~\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak{application=\"monitoring-service\", instance=~\"$instance\"} or jvm_threads_peak_threads{application=\"monitoring-service\", instance=~\"$instance\"}",
     "legendFormat": "peak"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"monitoring-service\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "LA 1m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"monitoring-service\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Discoveries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate запуска discovery",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(irate(monitoringservice_scheduled_discoveries_total{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Discoveries"
      }
     ]
    },
    {
     "title": "Время выборки discovery из БД",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(monitoringservice_discovery_schedule_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval]) / \nrate(monitoringservice_discovery_schedule_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Duration"
      }
     ]
    },
    {
     "title": "Время выполнения discovery",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(monitoringservice_discovery_execute_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval]) / rate(monitoringservice_discovery_execute_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Duration"
      }
     ]
    },
    {
     "title": "Время сохранения результатов discovery в БД",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(monitoringservice_discovery_save_results_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval]) / rate(monitoringservice_discovery_save_results_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Duration"
      }
     ]
    },
    {
     "title": "Rate ошибок выполнения discovery",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(irate(monitoringservice_discovery_errors_total{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Discoveries"
      }
     ]
    },
    {
     "title": "Загруженность discovery poller-а",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "monitoringservice_discovery_poller_load",
       "legendFormat": "Duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Items",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate запуска опроса item",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(irate(monitoringservice_scheduled_items_total{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Items"
      },
      {
       "expr": "sum(irate(monitoringservice_scheduled_items_by_type_total{instance=~\"$instance\"}[$__rate_interval])) by (type)",
       "legendFormat": "Items: {{type}}"
      }
     ]
    },
    {
     "title": "Время опроса item",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(monitoringservice_item_poll_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval]) / rate(monitoringservice_item_poll_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Duration"
      }
     ]
    },
    {
     "title": "Время выборки item из БД",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(monitoringservice_item_schedule_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval]) / rate(monitoringservice_item_schedule_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Duration"
      }
     ]
    },
    {
     "title": "Rate ошибок выполнения опроса item",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum(irate(monitoringservice_item_errors_by_type_total{instance=~\"$instance\"}[$__rate_interval])) by (type)",
       "legendFormat": "Errors: {{type}}"
      }
     ]
    },
    {
     "title": "Загруженность item poller-а",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "monitoringservice_item_poller_load",
       "legendFormat": "Duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate собираемых метрик",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(irate(monitoringservice_produced_metrics_total{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Metrics"
      }
     ]
    },
    {
     "title": "Rate метрик, сохраняемых в БД",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
     "targets": [
      {
       "expr": "sum(rate(monitoringservice_save_metrics_total{instance=~\"$instance\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Количество сохраняемых метрик",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "monitoringservice_metric_buffer_size{instance=~\"$instance\"}",
       "legendFormat": "Ожидает в буфере"
      },
      {
       "expr": "monitoringservice_processing_metric_values{instance=~\"$instance\"}",
       "legendFormat": "В процессе сохранения в БД"
      }
     ]
    },
    {
     "title": "Время сохранения буфера метрик в БД",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(monitoringservice_flush_metrics_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval]) / \nrate(monitoringservice_flush_metrics_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Metrics"
      }
     ]
    }
   ]
  },
  {
   "title": "Problem Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate отправки метрик на problem-manager",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(rate(monitoringservice_problem_manager_messages_total{instance=~\"$instance\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Adapters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "SNMP Engine: rate SNMP-запросов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(monitoringservice_snmp_request_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "SNMP Engine: длительность выполнения SNMP запросов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(monitoringservice_snmp_request_duration_seconds_sum{method=\"GET\", instance=~\"$instance\"}[$__rate_interval])) / \nsum(rate(monitoringservice_snmp_request_duration_seconds_count{method=\"GET\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "GET"
      },
      {
       "expr": "sum(rate(monitoringservice_snmp_request_duration_seconds_sum{method=\"WALK\", instance=~\"$instance\"}[$__rate_interval])) / \nsum(rate(monitoringservice_snmp_request_duration_seconds_count{method=\"WALK\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "WALK"
      }
     ]
    },
    {
     "title": "SNMP Engine: таймауты SNMP-запросов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 *\nsum(rate(monitoringservice_snmp_request_errors_total{reason=\"timeout\", instance=~\"$instance\"}[$__rate_interval])) /\nsum(rate(monitoringservice_snmp_request_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Timeouts"
      }
     ]
    },
    {
     "title": "Accessor Queue: время ожидания блокировки",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(monitoringservice_device_accessor_queue_lock_wait_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval])) / \nsum(rate(monitoringservice_device_accessor_queue_lock_wait_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "ICMP"
      }
     ]
    },
    {
     "title": "SNMP4j: rate SNMP-пакетов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(monitoringservice_snmp4j_packets_total{instance=~\"$instance\"}[$__rate_interval])) by (direction)",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "SNMP4j: количество pending SNMP запросов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "monitoringservice_pending_snmp_requests{instance=~\"$instance\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "SNMP4j: таймауты SNMP-запросов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 *\nsum(rate(monitoringservice_snmp4j_request_timeouts_total{instance=~\"$instance\"}[$__rate_interval])) /\nsum(rate(monitoringservice_snmp4j_packets_total{instance=~\"$instance\", direction=\"out\"}[$__rate_interval]))",
       "legendFormat": "Timeouts"
      }
     ]
    },
    {
     "title": "Accessor Queue: максимальный размер очереди",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "monitoringservice_device_accessor_max_queue_size{instance=~\"$instance\"}",
       "legendFormat": "ICMP"
      }
     ]
    },
    {
     "title": "Длительность ICMP-запросов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(monitoringservice_icmp_request_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval])) / \nsum(rate(monitoringservice_icmp_request_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "expr": "sum(rate(monitoring_service_redisson_codec_total{instance=~\"$instance\", operation=\"decode\"}[$__rate_interval]))",
       "legendFormat": "ALL"
      },
      {
       "expr": "sum(rate(monitoring_service_redisson_codec_total{instance=~\"$instance\", operation=\"decode\"}[$__rate_interval])) by (object)",
       "legendFormat": "{{object}}"
      }
     ]
    },
    {
     "title": "Write rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      {
       "expr": "sum(rate(monitoring_service_redisson_codec_total{instance=~\"$instance\", operation=\"encode\"}[$__rate_interval]))",
       "legendFormat": "ALL"
      },
      {
       "expr": "sum(rate(monitoring_service_redisson_codec_total{instance=~\"$instance\", operation=\"encode\"}[$__rate_interval])) by (object)",
       "legendFormat": "{{object}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate вычисления шаблонных выражений",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sum(irate(monitoringservice_expression_eval_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Expressions"
      }
     ]
    },
    {
     "title": "Время вычисления шаблонных выражений",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(monitoringservice_expression_eval_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval]) / rate(monitoringservice_expression_eval_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Duration"
      }
     ]
    }
   ]
  }
 ]
}