{
 "title": "notification-service",
 "description": "Графики мониторинга сервиса оповещений ECCM",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "precision",
    "label": "Precision",
    "query": "15s, 30s, 1m, 2m, 5m, 15m, 30m, 1h"
   }
  ]
 },
 "panels": [
  {
   "title": "Rate создания уведомлений",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(notificationservice_create_notification_metric_total[$precision])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Время создания уведомления",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(notificationservice_get_create_notification_duration_seconds_sum[$precision]) / \nrate(notificationservice_get_create_notification_duration_seconds_count[$precision])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Rate на отправку уведомлений",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(notificationservice_send_telegram_notification_metric_total[$precision])",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "rate(notificationservice_send_mail_notification_metric_total[$precision])",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "rate(notificationservice_send_websocket_notification_metric_total[$precision])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Время отправки уведомления",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(notificationservice_telegram_message_sending_duration_seconds_sum[$precision]) / \nrate(notificationservice_telegram_message_sending_duration_seconds_count[$precision]) > 0",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "rate(notificationservice_mail_message_sending_duration_seconds_sum[$precision]) / \nrate(notificationservice_mail_message_sending_duration_seconds_count[$precision]) > 0",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "rate(notificationservice_websocket_message_sending_duration_seconds_sum[$precision]) / \nrate(notificationservice_websocket_message_sending_duration_seconds_count[$precision]) > 0",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Rate ошибок при отправке уведомлений",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(notificationservice_send_telegram_notification_error_metric_total[$precision])",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "rate(notificationservice_send_mail_notification_error_metric_total[$precision])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(notificationservice_send_websocket_notification_error_metric_total[$precision])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время связывания всех уведомлений",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(notificationservice_link_all_notifications_duration_seconds_sum[$precision]) / \nrate(notificationservice_link_all_notifications_duration_seconds_count[$precision])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Время связывания одного уведомления",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(notificationservice_link_notification_duration_seconds_sum[$precision]) / \nrate(notificationservice_link_notification_duration_seconds_count[$precision])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Время сохранения связывания в БД",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(notificationservice_link_notification_internal_duration_seconds_sum[$precision]) / \nrate(notificationservice_link_notification_internal_duration_seconds_count[$precision])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Время между созданием и отправкой уведомления",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(notificationservice_get_from_create_to_send_notification_duration_seconds_sum[$precision]) / \nrate(notificationservice_get_from_create_to_send_notification_duration_seconds_count[$precision])",
     "legendFormat": "{{reason}}"
    }
   ]
  }
 ]
}