{
 "title": "problem-manager",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Темпы получения всех сырых данных",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(problemmanager_received_data_total[$__rate_interval]))",
     "legendFormat": "Received Rate"
    }
   ]
  },
  {
   "title": "Темпы обработки сырых данных для которых найдено правило",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(problemmanager_processed_data_total[$__rate_interval]))",
     "legendFormat": "Processed Rate"
    }
   ]
  },
  {
   "title": "Время обработки сырых данных и генерации событий",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(problemmanager_message_processing_duration_seconds_sum[$__rate_interval])) / \nsum(rate(problemmanager_message_processing_duration_seconds_count[$__rate_interval])))",
     "legendFormat": "Processing Time"
    }
   ]
  },
  {
   "title": "Количество дропов сообщений в очереди P-M",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(problemmanager_flow_dropped_data_total[$__rate_interval]))",
     "legendFormat": "Drops rate"
    }
   ]
  },
  {
   "title": "Время поиска событий для анализа ПГП",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(problemmanager_events_searching_duration_seconds_sum[$__rate_interval])) / \nsum(rate(problemmanager_events_searching_duration_seconds_count[$__rate_interval])))",
     "legendFormat": "Events searching duration"
    }
   ]
  }
 ]
}