{
 "title": "syslog-receiver",
 "description": "Графики мониторинга syslog сервиса ECCM",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "precision",
    "label": "Precision",
    "query": "15s, 30s, 1m, 2m, 5m, 15m, 30m, 1h"
   }
  ]
 },
 "panels": [
  { "title": "Syslog Receiver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate TCP/UDP запросов",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(syslogreceiver_handle_tcp_syslog_metric_total[$precision])",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "rate(syslogreceiver_handle_udp_syslog_metric_total[$precision])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Время сохранения логов в БД",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(syslogreceiver_flush_internal_duration_seconds_sum[$precision]) / \nrate(syslogreceiver_flush_internal_duration_seconds_count[$precision])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Rate запросов в problem manager",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(syslogreceiver_handle_problem_manager_syslog_batch_metric_total[$precision])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(syslogreceiver_handle_problem_manager_syslog_batch_error_metric_total[$precision])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Rate ошибок сохранения логов в БД",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "rate(syslogreceiver_handle_flush_internal_errors_metric_total[$precision])",
     "legendFormat": "{{reason}}"
    }
   ]
  }
 ]
}