{
 "title": "terminal-manager",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"terminal-manager\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Websocket Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Активные сессии",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "terminalmanager_active_sessions{instance=\"$instance\"}",
     "legendFormat": "active"
    }
   ]
  },
  { "title": "Websocket Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Rate входящих Websocket-сообщений",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(terminalmanager_input_message_total{instance=\"$instance\"}[10s])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Rate исходящих Websocket-сообщений",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(terminalmanager_output_message_total{instance=\"$instance\"}[10s])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "SSH Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Время установки SSH-сессии",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(terminalmanager_ssh_session_connection_duration_seconds_sum{instance=~\"$instance\"}[10s]) / rate(terminalmanager_ssh_session_connection_duration_seconds_count{instance=~\"$instance\"}[10s]))",
     "legendFormat": "time"
    }
   ]
  }
 ]
}