# --- НАЧАЛО СЕКЦИИ GLOBAL ---
# Здесь находятся глобальные настройки, которые применяются ко всем задачам (jobs) по сбору метрик,
# если они не переопределены в самой задаче.
global:
  # --- Как часто VictoriaMetrics будет опрашивать (скрейпить) каждую цель.
  # В данном случае, раз в 10 секунд.
  scrape_interval: "10s"

  # --- Сколько времени VictoriaMetrics будет ждать ответа от цели, прежде чем считать попытку неудачной.
  # Таймаут должен быть меньше, чем scrape_interval.
  scrape_timeout: "5s"

  # --- Добавляет указанные метки ко всем метрикам, которые собирает данный экземпляр VictoriaMetrics.
  external_labels:
    # --- Добавляет метку 'host' со значением переменной окружения DOCKER_HOST.
    # Например, если DOCKER_HOST="my-server-1", то у всех собранных метрик будет label {host="my-server-1"}.
    # Это позволяет различать данные, пришедшие с разных хостов.
    host: "%{DOCKER_HOST}"

# Это ключевая директива для модульной и гибкой настройки.
scrape_config_files:
  # --- Эта строка говорит VictoriaMetrics: "Помимо этого файла, пожалуйста, загрузи
  # и обработай все файлы, которые ты найдешь по этому пути и которые заканчиваются на .yaml".
  # Путь "/etc/victoria-metrics/configs/" находится ВНУТРИ контейнера VictoriaMetrics.
  - "/etc/victoria-metrics/configs/*.yaml"
