{
 "title": "notification-service",
 "description": "Графики мониторинга сервиса оповещений ECCM",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values({app=\"eccm\"},host)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({application=\"notification-service\", host=\"$host\"},instance)"
    }
   },
   {
    "name": "precision",
    "label": "Precision",
    "query": "15s, 30s, 1m, 2m, 5m, 15m, 30m, 1h"
   }
  ]
 },
 "panels": [
  {
   "title": "Rate создания уведомлений",
   "type": "timeseries",
   "description": "Показывает частоту создания уведомлений.\n\n* Рост значения может означать увеличение пользовательской активности, запуск массовых рассылок или неконтролируемую генерацию уведомлений (возможно, из-за багов или повторных попыток).\n* Снижение может указывать на падение нагрузки, проблемы с сервисом или недоступность внешних источников событий.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(notificationservice_create_notification_metric_total{host=\"$host\", instance=\"$instance\"}[$precision])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Время создания уведомления",
   "type": "timeseries",
   "description": "Показывает среднее время выполнения операции создания уведомления.\n\n* Повышенные значения могут свидетельствовать о деградации производительности, задержках в обработке запросов, перегрузке сервиса или внешних зависимостях (например, базе данных или сторонних API).\n* Снижение среднего времени говорит о хорошем состоянии сервиса и быстрой обработке операций.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(notificationservice_get_create_notification_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[$precision]) / \nrate(notificationservice_get_create_notification_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[$precision])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Rate на отправку уведомлений",
   "type": "timeseries",
   "description": "Показывает частоту отправки уведомлений, разделённую по каналам доставки: Telegram, Email и WebSocket.\n\n* Резкий рост значений может указывать на массовую рассылку, всплеск активности пользователей или аномальное поведение (например, зацикливание попыток отправки).\n\n* Резкое снижение до нуля может свидетельствовать о сбое в конкретном канале или внешнем сервисе (например, недоступность SMTP-сервера или Telegram API).\n",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(notificationservice_send_telegram_notification_metric_total{host=\"$host\", instance=\"$instance\"}[$precision])",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "rate(notificationservice_send_mail_notification_metric_total{host=\"$host\", instance=\"$instance\"}[$precision])",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "rate(notificationservice_send_websocket_notification_metric_total{host=\"$host\", instance=\"$instance\"}[$precision])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Время отправки уведомления",
   "type": "timeseries",
   "description": "Показывает среднее время отправки уведомлений по трём каналам доставки: Telegram, Email и WebSocket.\n\n* Рост значений может свидетельствовать о деградации производительности (например, медленный отклик от внешнего API или проблемы с сетью).\n* Резкое увеличение на одном из каналов при нормальных значениях на остальных — хороший индикатор локальной проблемы (например, сбой у почтового провайдера).",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(notificationservice_telegram_message_sending_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[$precision]) / \nrate(notificationservice_telegram_message_sending_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[$precision]) > 0",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "rate(notificationservice_mail_message_sending_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[$precision]) / \nrate(notificationservice_mail_message_sending_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[$precision]) > 0",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "rate(notificationservice_websocket_message_sending_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[$precision]) / \nrate(notificationservice_websocket_message_sending_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[$precision]) > 0",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Rate ошибок при отправке уведомлений",
   "type": "timeseries",
   "description": "Показывает частоту возникновения ошибок при отправке уведомлений по трём каналам: Telegram, Email и WebSocket.\n\n* Устойчивый рост значений может указывать на проблемы с внешними сервисами (SMTP, Telegram API, соединения по websocket), внутренние ошибки логики обработки, превышение лимитов, таймауты или некорректные конфигурации.\n* Резкие всплески ошибок могут сигнализировать об инцидентах.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(notificationservice_send_telegram_notification_error_metric_total{host=\"$host\", instance=\"$instance\"}[$precision])",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "rate(notificationservice_send_mail_notification_error_metric_total{host=\"$host\", instance=\"$instance\"}[$precision])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(notificationservice_send_websocket_notification_error_metric_total{host=\"$host\", instance=\"$instance\"}[$precision])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время связывания всех уведомлений",
   "type": "timeseries",
   "description": "Показывает среднее время выполнения операции связывания всех уведомлений.\n\n* Рост значения может указывать на ухудшение производительности (например, из-за увеличения объёма данных, задержек в БД или проблем с алгоритмом связывания).\n* Стабильно высокое значение может говорить о неэффективной реализации или необходимости оптимизации.\n* Резкие скачки могут быть признаком временных сбоев, перегрузки или деградации сторонних компонентов.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(notificationservice_link_all_notifications_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[$precision]) / \nrate(notificationservice_link_all_notifications_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[$precision])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Время связывания одного уведомления",
   "type": "timeseries",
   "description": "Показывает среднее время выполнения операции связывания одного уведомления.\n\n* Рост времени связывания может свидетельствовать о деградации производительности, увеличении объёма данных, блокировках в базе или неэффективной логике сопоставления.\n* Стабильно высокие значения — индикатор потенциальных узких мест в архитектуре или необходимости оптимизации бизнес-логики.\n* Резкие всплески могут быть признаком временных инцидентов, например, проблем с БД, нагрузкой или зависимыми сервисами.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(notificationservice_link_notification_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[$precision]) / \nrate(notificationservice_link_notification_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[$precision])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Время сохранения связывания в БД",
   "type": "timeseries",
   "description": "Показывает среднее время выполнения операции связывания уведомления.\n\n* Увеличение среднего времени сохранения может свидетельствовать о проблемах с производительностью БД, блокировках, высокой нагрузке или неэффективных запросах.\n* Стабильно низкое время говорит о нормальной работе слоя хранения.\n* Резкие всплески могут указывать на временные сбои или деградацию инфраструктуры базы данных.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(notificationservice_link_notification_internal_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[$precision]) / \nrate(notificationservice_link_notification_internal_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[$precision])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Время между созданием и отправкой уведомления",
   "type": "timeseries",
   "description": "Показывает среднее время, затраченное на процесс от создания уведомления до его отправки в сервисе notificationservice.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(notificationservice_get_from_create_to_send_notification_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[$precision]) / \nrate(notificationservice_get_from_create_to_send_notification_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[$precision])",
     "legendFormat": "{{reason}}"
    }
   ]
  }
 ]
}