{
 "title": "terminal-manager",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values({app=\"eccm\"},host)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({application=\"terminal-manager\", host=\"$host\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Websocket Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Активные сессии",
   "type": "timeseries",
   "description": "Показывает текущее количество активных сессий.\n\n* Стабильное или умеренно растущее количество сессий свидетельствует о нормальной загрузке системы.\n* Резкое увеличение может указывать на всплеск пользовательской активности или возможные проблемы с завершением сессий.\n* Резкое снижение (до нуля или ниже ожидаемого уровня) может быть признаком сбоев в terminal manager, отключений или остановки сервиса.\n\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "terminalmanager_active_sessions{host=\"$host\", instance=\"$instance\"}",
     "legendFormat": "active"
    }
   ]
  },
  { "title": "Websocket Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Rate входящих Websocket-сообщений",
   "type": "timeseries",
   "description": "Показывает скорость поступления входящих сообщений по WebSocket-соединению.\n\n* Умеренное и стабильное значение соответствует нормальному взаимодействию клиентов с системой.\n* Рост значения может означать увеличение пользовательской активности или возможную нагрузку на обработку сообщений.\n* Падение до нуля может свидетельствовать о потере соединений, отсутствии клиентов или сбоях в системе приема сообщений.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(terminalmanager_input_message_total{host=\"$host\", instance=\"$instance\"}[10s])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Rate исходящих Websocket-сообщений",
   "type": "timeseries",
   "description": "Показывает скорость отправки исходящих сообщений по WebSocket-соединению.\n\n* Стабильное значение указывает на нормальную работу терминального сервиса и активную передачу данных клиентам.\n* Повышение может свидетельствовать о росте пользовательской активности или объема передаваемых данных.\n* Резкое снижение или нулевое значение может указывать на обрыв соединений, отсутствие клиентов, задержки в обработке или сбой компонента.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(terminalmanager_output_message_total{host=\"$host\", instance=\"$instance\"}[10s])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "SSH Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Время установки SSH-сессии",
   "type": "timeseries",
   "description": "Показывает среднее время необходимое для установления SSH-сессии.\n\n* Низкое и стабильное значение указывает на быструю и корректную установку SSH-сессий.\n* Повышение времени может свидетельствовать о задержках на сетевом уровне, проблемах с аутентификацией, высокой нагрузке на систему или медленном отклике удалённой стороны.\n* Резкие скачки или рост средней задержки требуют диагностики — возможно, сессии создаются медленно из-за узких мест в инфраструктуре.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(terminalmanager_ssh_session_connection_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[10s]) / rate(terminalmanager_ssh_session_connection_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[10s]))",
     "legendFormat": "time"
    }
   ]
  }
 ]
}