{
 "title": "problem-manager",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values({app=\"eccm\"},host)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({application=\"problem-manager\", host=\"$host\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Темпы получения всех сырых данных",
   "type": "timeseries",
   "description": "Показывает суммарные темпы поступления всех сырых данных.\n\n* Рост темпа может быть нормальным при увеличении нагрузки или сигналом потенциальной перегрузки, если сопровождается ростом ошибок или задержек.\n* Падение до нуля может означать потерю входящего трафика, сбои в интеграциях или проблемы с источниками данных.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(problemmanager_received_data_total{host=\"$host\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Received Rate"
    }
   ]
  },
  {
   "title": "Темпы обработки сырых данных для которых найдено правило",
   "type": "timeseries",
   "description": "Показывает суммарные темпы обработки сырых данных, для которых было успешно применено правило.\n\n* Рост значения может означать увеличение активности системы или расширение покрытия правилами.\n* Снижение темпа при наличии входящих данных может сигнализировать о проблемах в логике сопоставления, снижении эффективности правил или сбоях в обработке.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(problemmanager_processed_data_total{host=\"$host\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Processed Rate"
    }
   ]
  },
  {
   "title": "Время обработки сырых данных и генерации событий",
   "type": "timeseries",
   "description": "Показывает среднее время обработки одного входящего сыро́го сообщения.\nСколько в среднем времени занимает полный цикл обработки одного сообщения, включая:\nразбор входящих данных,\nпоиск и применение правил,\nгенерацию одного или нескольких событий.\n\n* Рост среднего времени может указывать на ухудшение производительности: перегрузку системы, блокировки в БД, неэффективные правила или проблемы с внешними сервисами.\n* Резкие всплески — возможный признак инцидента, замедления очередей или перегрузки потоков обработки.\n",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(problemmanager_message_processing_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[$__rate_interval])) / \nsum(rate(problemmanager_message_processing_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "Processing Time"
    }
   ]
  },
  {
   "title": "Количество дропов сообщений в очереди P-M",
   "type": "timeseries",
   "description": "Gоказывает, сколько сообщений теряется на этапе передачи или обработки в очереди P-M.\n\n- Появление значений выше 0 — критичный индикатор: сообщения не успевают обрабатываться и отбрасываются, что может привести к потере событий и деградации бизнес-функциональности.\n- Резкие всплески дропов часто связаны с:\n  - перегрузкой сервиса,\n  - медленной обработкой сообщений,\n  - нехваткой ресурсов (память, CPU),\n  - переполнением внутренних буферов/очередей.\n- Стабильно нулевое значение — норма: очередь работает корректно, потерь нет.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(problemmanager_flow_dropped_data_total{host=\"$host\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Drops rate"
    }
   ]
  },
  {
   "title": "Время поиска событий для анализа ПГП",
   "type": "timeseries",
   "description": "Показывает среднее время поиска событий.\n\n- Рост среднего времени может указывать на:\n  - увеличение объёма данных,\n  - замедление базы данных,\n  - неоптимальные условия выборки (например, по большим временным диапазонам),\n  - высокую конкуренцию за ресурсы.\n- Резкие скачки — возможный признак перегрузки системы или неэффективных алгоритмов анализа.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(problemmanager_events_searching_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[$__rate_interval])) / \nsum(rate(problemmanager_events_searching_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "Events searching duration"
    }
   ]
  }
 ]
}