{
 "title": "cron-manager",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values({app=\"eccm\"},host)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({application=\"cron-manager\", host=\"$host\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Rate запуска новых задач (Job)",
   "type": "timeseries",
   "description": "Показывает частоту выполнения задач.\n\n* Рост значения указывает на увеличение частоты запуска новых задач.\n* Падение или нулевое значение может означать отсутствие запускаемых задач или проблемы в планировщике.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(cronmanager_running_jobs{host=\"$host\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{ task_type }}"
    }
   ]
  },
  {
   "title": "Rate статусов задач (Job)",
   "type": "timeseries",
   "description": "Показывает частоту изменения общего количества выполненных заданий. \n\n* Повышение частоты изменения статусов может свидетельствовать о повышенной активности задач или нестабильности в их выполнении.\n* Стабильные низкие значения указывают на нормальную работу планировщика.\n* Всплески могут указывать на массовый запуск, завершение или ошибки задач и требуют дополнительного анализа.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(cronmanager_job_statuses_total{host=\"$host\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Активные задачи (Job)",
   "type": "timeseries",
   "description": "Показывает текущее количество запущенных задач.\n\n* Рост значения отражает увеличение числа параллельно запущенных задач.\n* Снижение или нулевое значение говорит о снижении активности или отсутствии выполняющихся задач.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cronmanager_running_jobs{host=\"$host\", instance=\"$instance\"}",
     "legendFormat": "{{task_type}}"
    }
   ]
  },
  {
   "title": "Продолжительность выполнения задач (Job)",
   "type": "timeseries",
   "description": "Показывает среднее время выполнения задач.\n\n*  Повышение среднего времени выполнения может указывать на рост сложности задач, перегрузку системы или проблемы с внешними зависимостями.\n* Снижение значения говорит о более быстрой обработке задач или уменьшении их объёма.\n* Резкие скачки требуют анализа — возможны зависания, ошибки в логике задач или нестабильность окружения.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(cronmanager_job_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[1m]) / rate(cronmanager_job_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{ task_type }}"
    }
   ]
  },
  {
   "title": "Активные задачи (SSH)",
   "type": "timeseries",
   "description": "Показывает текущее количество запущенных SSH-задач.\n\n* Рост значения может свидетельствовать об увеличении количества одновременно запущенных SSH-задач, возможной задержке в их выполнении или недостаточной параллельности.\n* Падение до нуля указывает на отсутствие активных SSH-задач в текущий момент.\n* Постоянно высокое значение может говорить о \"зависших\" задачах или проблемах с SSH-инфраструктурой.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cronmanager_running_ssh_tasks{host=\"$host\", instance=\"$instance\"}",
     "legendFormat": "{{task_type}}"
    }
   ]
  },
  {
   "title": "Продолжительность выполнения задач (SSH)",
   "type": "timeseries",
   "description": "Показывает среднее время выполнения SSH-задач.\n\n* Рост среднего времени выполнения может сигнализировать о проблемах с удалёнными хостами, задержках в сети, перегрузке, неэффективной логике задач или неудачных SSH-подключениях.\n* Снижение говорит о быстрой и эффективной обработке SSH-задач.\n* Резкие колебания требуют анализа: они могут быть связаны с нестабильной инфраструктурой или варьирующейся сложностью выполняемых команд.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(cronmanager_ssh_task_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[1m]) / rate(cronmanager_ssh_task_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{ task_type }}"
    }
   ]
  }
 ]
}