{
 "title": "syslog-receiver",
 "description": "Графики мониторинга syslog сервиса ECCM",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values({app=\"eccm\"},host)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({application=\"syslog-receiver\", host=\"$host\"},instance)"
    }
   },
   {
    "name": "precision",
    "label": "Precision",
    "query": "15s, 30s, 1m, 2m, 5m, 15m, 30m, 1h"
   }
  ]
 },
 "panels": [
  { "title": "Syslog Receiver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate TCP/UDP запросов",
   "type": "timeseries",
   "description": "Показывает частоту приёма syslog-сообщений по протоколам TCP и UDP.\n\n* Рост графиков указывает на увеличение количества входящих syslog-сообщений по соответствующему протоколу.\n* Резкое снижение или отсутствие активности может сигнализировать о сетевых проблемах, потере соединения или сбоях источников логов.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(syslogreceiver_handle_tcp_syslog_metric_total{host=\"$host\", instance=\"$instance\"}[$precision])",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "rate(syslogreceiver_handle_udp_syslog_metric_total{host=\"$host\", instance=\"$instance\"}[$precision])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Время сохранения логов в БД",
   "type": "timeseries",
   "description": "Показывает среднее время обработки и записи логов в базу данных.\n\n* Низкое значение — означает, что система быстро сохраняет логи, что свидетельствует о нормальной работе подсистемы записи.\n* Рост значения может указывать на задержки в записи, вызванные нагрузкой на БД или проблемы с производительностью.\n* Резкие скачки или тренды роста требуют дополнительного анализа для выявления узких мест и предотвращения потери данных.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(syslogreceiver_flush_internal_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[$precision]) / \nrate(syslogreceiver_flush_internal_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[$precision])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Rate запросов в problem manager",
   "type": "timeseries",
   "description": "Показывает частоту обработки и ошибок при передаче запросов в сервис problem manager.\n\n* Высокая частота успешных запросов при нулевом или низком уровне ошибок говорит о стабильной работе интеграции с problem manager.\n* Увеличение количества ошибок может указывать на проблемы взаимодействия между syslogreceiver и problem manager (например, ошибки в API, тайм-ауты или некорректные данные).\n* Отсутствие активности может быть признаком сбоев upstream-источников логов или приостановки потоков логирования.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(syslogreceiver_handle_problem_manager_syslog_batch_metric_total{host=\"$host\", instance=\"$instance\"}[$precision])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(syslogreceiver_handle_problem_manager_syslog_batch_error_metric_total{host=\"$host\", instance=\"$instance\"}[$precision])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Rate ошибок сохранения логов в БД",
   "type": "timeseries",
   "description": "Показывает частоту  возникновения ошибок при сохранении логов в базу данных.\n\n* Значение, близкое к нулю, указывает на отсутствие или минимальное количество ошибок при сохранении логов.\n* Повышение значения свидетельствует о возникновении проблем в подсистеме записи, что может привести к потере данных или нарушению целостности логов.\n* Постоянно растущие или скачкообразные значения требуют немедленного внимания и расследования причин ошибок.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "rate(syslogreceiver_handle_flush_internal_errors_metric_total{host=\"$host\", instance=\"$instance\"}[$precision])",
     "legendFormat": "{{reason}}"
    }
   ]
  }
 ]
}