{
 "title": "RabbitMQ Overview",
 "description": "A new RabbitMQ Management Overview",
 "tags": [ "rabbitmq-prometheus" ],
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values({app=\"eccm\"},host)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(rabbitmq_identity_info{host=\"$host\"},namespace)"
    }
   },
   {
    "name": "rabbitmq_cluster",
    "label": "RabbitMQ Cluster",
    "query": {
     "query": "label_values(rabbitmq_identity_info{namespace=\"$namespace\", host=\"$host\"},rabbitmq_cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ready messages",
   "type": "stat",
   "description": "Общее количество сообщений в состоянии *ready* (готовых к доставке).\n\nЭто количество показывает, сколько сообщений ожидает потребителей и готово к обработке.\n\nРекомендуется поддерживать это значение как можно ниже, так как постоянный рост может указывать на узкое место в потребителях, что в итоге приведёт к переполнению памяти и диска.\n\nДля управления ростом очередей рассмотрите использование ограничений длины очереди (Queue Length Limit) или времени жизни сообщений (TTL).\n\n* [Очереди (Queues)](https://www.rabbitmq.com/queues.html)\n* [Потребители (Consumers)](https://www.rabbitmq.com/consumers.html)\n* [Ограничение длины очереди (Queue Length Limit)](https://www.rabbitmq.com/maxlength.html)\n* [Время жизни сообщений (TTL)](https://www.rabbitmq.com/ttl.html)",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready{host=\"$host\"} * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", host=\"$host\"})"
    }
   ]
  },
  {
   "title": "Incoming messages / s",
   "type": "stat",
   "description": "Скорость входящих сообщений.\n\nПоказывает количество сообщений, поступающих в RabbitMQ за секунду, до применения каких-либо правил маршрутизации.\n\nВысокие значения указывают на активность отправителей сообщений. Если скорость поступления сообщений значительно выше скорости доставки, это может привести к росту очередей и повышенной нагрузке на систему.\n\n* [Издатели (Publishers)](https://www.rabbitmq.com/publishers.html)",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_published_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\"})"
    }
   ]
  },
  {
   "title": "Publishers",
   "type": "stat",
   "description": "Общее количество активных каналов, связанных с издателями (publishers).\n\nРасчёт ведётся как разница между общим числом открытых каналов и числом каналов, используемых потребителями (consumers), что позволяет оценить активность издателей сообщений.\n\nРост этого показателя может свидетельствовать об увеличении количества приложений, публикующих сообщения, или о возможных утечках каналов.\n\nРекомендуется мониторить вместе с метриками потребителей и каналов для выявления дисбаланса и проблем с ресурсами.\n\n* [Каналы (Channels)](https://www.rabbitmq.com/channels.html)\n* [Издатели (Publishers)](https://www.rabbitmq.com/publishers.html)\n* [Потребители (Consumers)](https://www.rabbitmq.com/consumers.html)",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_channels{host=\"$host\"} * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) - sum(rabbitmq_channel_consumers{host=\"$host\"} * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "description": "Общее количество клиентских подключений к RabbitMQ.\n\nЭта метрика показывает число активных соединений, через которые клиенты взаимодействуют с брокером.\n\nРост количества соединений может указывать на увеличение нагрузки или потенциальные утечки соединений в приложениях.\n\nРекомендуется контролировать эту метрику вместе с показателями открытия и закрытия соединений для выявления аномалий.\n\n* [Подключения (Connections)](https://www.rabbitmq.com/connections.html)\n* [Мониторинг соединений](https://www.rabbitmq.com/connections.html#monitoring)",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_connections{host=\"$host\"} * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "stat",
   "description": "бщее количество очередей RabbitMQ.\n\nЭта метрика помогает отслеживать распределение и количество активных очередей в кластере.\n\nРезкий рост или падение количества очередей может свидетельствовать о изменениях в нагрузке, конфигурации или возникновении проблем с производительностью.\n\nРекомендуется контролировать эту метрику вместе с другими показателями очередей для комплексного мониторинга.\n\n* [Очереди (Queues)](https://www.rabbitmq.com/queues.html)\n* [Высокодоступные очереди (HA Queues)](https://www.rabbitmq.com/ha.html)",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queues{host=\"$host\"} * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Unacknowledged messages",
   "type": "stat",
   "description": "Общее количество сообщений, доставленных потребителям, но ещё не подтверждённых ими (unacknowledged).\n\nЭти сообщения считаются «в полёте» — они либо обрабатываются потребителями, либо ожидают подтверждения. Высокое значение может указывать на задержки в обработке или проблемы с потребителями.\n\nДля оптимизации работы рассмотрите настройки подтверждений сообщений и мониторинг потребителей.\n\n* [Очереди (Queues)](https://www.rabbitmq.com/queues.html)\n* [Подтверждения сообщений (Confirms and Acknowledgements)](https://www.rabbitmq.com/confirms.html)\n* [Префетч (Consumer Prefetch)](https://www.rabbitmq.com/consumer-prefetch.html)",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacked * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Outgoing messages / s",
   "type": "stat",
   "description": "Общая скорость исходящих сообщений, включая:\n\n* Сообщения, доставленные потребителям (в том числе повторные доставки);\n* Подтверждённые сообщения;\n* Операции выборки сообщений потребителями (polling).\n\nЭтот показатель отражает интенсивность отдачи сообщений потребителям и показывает, насколько активно потребители обрабатывают сообщения.\n\nВысокие значения могут указывать на хорошую скорость обработки, однако слишком большое количество повторных доставок может свидетельствовать о проблемах с потребителями.\n\nРекомендуется мониторить баланс между входящими и исходящими сообщениями для поддержания стабильной работы.\n\n* [Потребители (Consumers)](https://www.rabbitmq.com/consumers.html)\n* [Подтверждения сообщений (Confirms and Acknowledgements)](https://www.rabbitmq.com/confirms.html)\n* [Повторные доставки (Redeliveries)](https://www.rabbitmq.com/confirms.html#consumer-nacks-requeue)",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_redelivered_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) +\nsum(rate(rabbitmq_channel_messages_delivered_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) +\nsum(rate(rabbitmq_channel_messages_delivered_ack_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{host=\"$host\",rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) +\nsum(rate(rabbitmq_channel_get_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) +\nsum(rate(rabbitmq_channel_get_ack_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "description": "Общее количество потребителей (consumers), подключенных к узлу `$host` в кластере `$rabbitmq_cluster`.\n\nЭта метрика отражает число активных каналов, через которые потребители получают сообщения из очередей.\n\nМониторинг количества потребителей помогает оценить нагрузку на систему и эффективность обработки сообщений.\n\nРекомендуется отслеживать вместе с метриками издателей и очередей для выявления дисбаланса или проблем с потреблением.\n\n* [Потребители (Consumers)](https://www.rabbitmq.com/consumers.html)\n* [Каналы (Channels)](https://www.rabbitmq.com/channels.html)\n* [Очереди (Queues)](https://www.rabbitmq.com/queues.html)",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_channel_consumers{host=\"$host\"} * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "stat",
   "description": "Общее количество открытых каналов (channels).\n\nКаналы — это легковесные виртуальные соединения внутри TCP-соединения, используемые для обмена сообщениями между клиентами и брокером.\n\nРост количества каналов может свидетельствовать о повышенной активности приложений или потенциальных утечках ресурсов.\n\nРекомендуется отслеживать совместно с метриками открытых и закрытых каналов для выявления аномалий.\n\n* [Каналы (Channels)](https://www.rabbitmq.com/channels.html)\n* [Утечки каналов](https://www.rabbitmq.com/channels.html#channel-leaks)",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_channels{host=\"$host\"} * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Общее количество узлов RabbitMQ.\n\nДанный показатель отражает число активных нод, участвующих в кластере.\n\nМониторинг количества узлов позволяет отслеживать состояние кластера и выявлять возможные отклонения, связанные с отключениями или добавлением новых нод.\n\n* [Кластеризация RabbitMQ](https://www.rabbitmq.com/clustering.html)\n* [Мониторинг узлов](https://www.rabbitmq.com/monitoring.html)",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_build_info{host=\"$host\"} * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "NODES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Показывает информацию о версиях и сборках RabbitMQ ",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "rabbitmq_build_info{host=\"$host\"} * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Memory available before publishers blocked",
     "type": "timeseries",
     "description": "Если значение равно нулю или меньше, сработает тревога по памяти, и все соединения на публикацию сообщений во всех узлах кластера будут заблокированы.\n\nЗначение может временно стать отрицательным, так как срабатывание тревоги происходит с небольшой задержкой.\n\nОценка используемой памяти ядром операционной системы может отличаться от той, что видит сам узел. Из-за этого значение может оставаться отрицательным в течение длительного времени.\n\nПо умолчанию узлы считают используемую память по размеру резидентного набора (RSS). Этот метод можно изменить (см. ссылки ниже).\n\n* [Тревоги](https://www.rabbitmq.com/alarms.html)\n* [Тревоги по памяти](https://www.rabbitmq.com/memory.html)\n* [Анализ использования памяти](https://www.rabbitmq.com/memory-use.html)\n* [Уведомления о заблокированных соединениях](https://www.rabbitmq.com/connection-blocked.html)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(rabbitmq_resident_memory_limit_bytes{host=\"$host\"} * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) -\n(rabbitmq_process_resident_memory_bytes{host=\"$host\"} * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "Disk space available before publishers blocked",
     "type": "timeseries",
     "description": "Эта метрика отображается для раздела диска, на котором хранится каталог данных RabbitMQ.\n\nЕсли значение равно нулю или меньше, сработает тревога по дисковому пространству, и все соединения для публикации сообщений на всех узлах кластера будут заблокированы.\n\nЗначение может временно стать отрицательным, так как тревога по свободному месту на диске срабатывает с небольшой задержкой.\n\n* [Тревоги](https://www.rabbitmq.com/alarms.html)\n* [Тревоги по дисковому пространству](https://www.rabbitmq.com/disk-alarms.html)\n* [Дисковое пространство](https://www.rabbitmq.com/production-checklist.html#resource-limits-disk-space)\n* [Настройка персистентности](https://www.rabbitmq.com/persistence-conf.html)\n* [Уведомления о заблокированных соединениях](https://www.rabbitmq.com/connection-blocked.html)",
     "gridPos": { "h": 8, "w": 8, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rabbitmq_disk_space_available_bytes{host=\"$host\"} * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "File descriptors available",
     "type": "timeseries",
     "description": "Когда это значение достигает нуля, новые подключения не принимаются, а операции записи на диск могут завершиться с ошибкой.\n\nКлиентские библиотеки, другие узлы кластера и командная строка не смогут подключиться к узлу, если на нём закончились доступные файловые дескрипторы.\n\n* [Ограничение на количество открытых файлов](https://www.rabbitmq.com/production-checklist.html#resource-limits-file-handle-limit)\n",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 85 },
     "targets": [
      {
       "expr": "(rabbitmq_process_max_fds{host=\"$host\"} * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) -\n(rabbitmq_process_open_fds{host=\"$host\"} * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "TCP sockets available",
     "type": "timeseries",
     "description": "Когда это значение достигает нуля, новые подключения не принимаются.\n\nКлиентские библиотеки, другие узлы кластера и инструменты командной строки не смогут подключиться к узлу, если на нём закончились доступные файловые дескрипторы.\n\n* [Сетевое взаимодействие и RabbitMQ](https://www.rabbitmq.com/networking.html)",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rabbitmq_process_max_tcp_sockets{host=\"$host\"} * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) -\n(rabbitmq_process_open_tcp_sockets{host=\"$host\"} * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "QUEUED MESSAGES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages ready to be delivered to consumers",
     "type": "timeseries",
     "description": "Общее количество готовых сообщений, ожидающих доставки потребителям.\n\nСтарайтесь удерживать это значение как можно ниже. RabbitMQ работает наиболее эффективно, когда сообщения непрерывно проходят через него. Допустимо, если издатели (publishers) временами опережают потребителей, но предполагается, что потребители в итоге обработают все готовые сообщения.\n\nЕсли это значение постоянно растёт, система в конечном итоге исчерпает доступную память и/или дисковое пространство. Рассмотрите возможность использования TTL или ограничения длины очереди, чтобы предотвратить неконтролируемый рост количества сообщений.\n\n* [Очереди](https://www.rabbitmq.com/queues.html)\n* [Потребители](https://www.rabbitmq.com/consumers.html)\n* [Ограничение длины очереди](https://www.rabbitmq.com/maxlength.html)\n* [Время жизни и срок действия сообщений (TTL)](https://www.rabbitmq.com/ttl.html)",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rabbitmq_queue_messages_ready{host=\"$host\"} * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "Messages pending consumer acknowledgement",
     "type": "timeseries",
     "description": "Общее количество сообщений, находящихся «в пути» к потребителям, в процессе обработки потребителями или ожидающих подтверждения от потребителей, которое ещё не было обработано очередью. Пока очередь не обработает подтверждение (ack), сообщение будет считаться неподтверждённым.\n\n* [Очереди](https://www.rabbitmq.com/queues.html)\n* [Подтверждения и подтверждения доставки](https://www.rabbitmq.com/confirms.html)\n* [Предзагрузка сообщений потребителем (Consumer Prefetch)](https://www.rabbitmq.com/consumer-prefetch.html)",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rabbitmq_queue_messages_unacked{host=\"$host\"} * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "INCOMING MESSAGES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages published / s",
     "type": "timeseries",
     "description": "Скорость входящих сообщений до применения каких-либо правил маршрутизации.\n\nЕсли это значение меньше, чем количество сообщений, доставленных в очереди, это может означать, что некоторые сообщения попадают сразу в несколько очередей.\n\nЕсли это значение больше, чем количество сообщений, доставленных в очереди, это означает, что сообщения не могут быть маршрутизированы и будут либо отброшены, либо возвращены издателю.\n\n* [Издатели (Publishers)](https://www.rabbitmq.com/publishers.html)",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_messages_published_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "Messages confirmed to publishers / s",
     "type": "timeseries",
     "description": "Скорость подтверждения сообщений брокером для издателей. Издатели должны явно включить получение подтверждений (publisher confirms).\n\nЕсли эта метрика стабильно равна нулю, это может указывать на то, что клиенты не используют подтверждения сообщений. В этом случае сохранность опубликованных сообщений может быть под угрозой.\n\n* [Подтверждения от издателя (Publisher Confirms)](https://www.rabbitmq.com/confirms.html#publisher-confirms)\n* [Подтверждения и надёжность доставки данных](https://www.rabbitmq.com/publishers.html#data-safety)\n* [Когда брокер подтверждает доставку сообщений?](https://www.rabbitmq.com/confirms.html#when-publishes-are-confirmed)",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_messages_confirmed_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "Messages routed to queues / s",
     "type": "timeseries",
     "description": "Скорость сообщений, полученных от издателей и успешно маршрутизированных в мастер-реплики очередей.\n\n* [Очереди](https://www.rabbitmq.com/queues.html)\n* [Издатели](https://www.rabbitmq.com/publishers.html)",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_queue_messages_published_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "Messages unconfirmed to publishers / s",
     "type": "timeseries",
     "description": "Скорость сообщений, полученных от издателей с включёнными подтверждениями (publisher confirms), которые брокер ещё не подтвердил.\n\n* [Издатели](https://www.rabbitmq.com/publishers.html)\n* [Подтверждения и подтверждения доставки](https://www.rabbitmq.com/confirms.html)\n* [Когда брокер подтверждает публикацию сообщений?](https://www.rabbitmq.com/confirms.html#when-publishes-are-confirmed)",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_messages_unconfirmed{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "Unroutable messages dropped / s",
     "type": "timeseries",
     "description": "Скорость сообщений, которые не удалось маршрутизировать и которые были отброшены.\n\nЛюбое значение выше нуля означает потерю сообщений и, вероятно, указывает на проблему с маршрутизацией на стороне издателя.\n\n* [Обработка не маршрутизируемых сообщений](https://www.rabbitmq.com/publishers.html#unroutable)\n",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_messages_unroutable_dropped_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "Unroutable messages returned to publishers / s",
     "type": "timeseries",
     "description": "Скорость сообщений, которые не удалось маршрутизировать и которые возвращаются обратно издателям.\n\nПостоянные значения выше нуля могут указывать на проблему с маршрутизацией на стороне издителя.\n\n* [Обработка не маршрутизируемых сообщений](https://www.rabbitmq.com/publishers.html#unroutable)\n* [Когда брокер подтверждает публикацию сообщений?](https://www.rabbitmq.com/confirms.html#when-publishes-are-confirmed)",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_messages_unroutable_returned_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OUTGOING MESSAGES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages delivered / s",
     "type": "timeseries",
     "description": "Скорость сообщений, доставленных потребителям. Включает повторно доставленные сообщения.\n\nЭта метрика не учитывает сообщения, полученные потребителями с помощью `basic.get` (потребление через опрос).\n\n* [Потребители](https://www.rabbitmq.com/consumers.html)",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  (rate(rabbitmq_channel_messages_delivered_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) +\n  (rate(rabbitmq_channel_messages_delivered_ack_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})\n) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "Messages redelivered / s",
     "type": "timeseries",
     "description": "Скорость сообщений, которые были повторно доставлены потребителям. Включает сообщения, автоматически помещённые обратно в очередь, а также повторные доставки из-за исключений каналов или разрывов соединения.\n\nНебольшое количество повторных доставок — это нормально, но если эта метрика постоянно ненулевая, стоит разобраться в причинах.\n\n* [Отрицательные подтверждения и повторное помещение сообщений в очередь](https://www.rabbitmq.com/confirms.html#consumer-nacks-requeue)\n* [Потребители](https://www.rabbitmq.com/consumers.html)",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_messages_redelivered_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "Messages delivered with manual ack / s",
     "type": "timeseries",
     "description": "Скорость доставки сообщений потребителям, использующим режим ручного подтверждения (manual acknowledgement).\n\nПри использовании этого режима RabbitMQ ожидает подтверждения от потребителей, прежде чем доставить им новые сообщения.\n\nЭто самый безопасный способ потребления сообщений.\n\n* [Подтверждения потребителей](https://www.rabbitmq.com/confirms.html)\n* [Предзагрузка сообщений потребителем (Consumer Prefetch)](https://www.rabbitmq.com/consumer-prefetch.html)\n* [Режимы подтверждения, предзагрузка и пропускная способность](https://www.rabbitmq.com/confirms.html#channel-qos-prefetch-throughput)\n* [Потребители](https://www.rabbitmq.com/consumers.html)",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_messages_delivered_ack_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "Messages delivered auto ack / s",
     "type": "timeseries",
     "description": "Скорость доставки сообщений потребителям, использующим режим автоматического подтверждения (automatic acknowledgement).\n\nВ этом режиме RabbitMQ не ждёт подтверждений от потребителей о доставке сообщений.\n\nЭтот режим «отправил и забыл» не обеспечивает гарантий доставки. Он обычно обеспечивает более высокую пропускную способность, но может привести к перегрузке потребителей и увеличению их потребления памяти.\n\n* [Режимы подтверждения, предзагрузка и пропускная способность](https://www.rabbitmq.com/confirms.html#channel-qos-prefetch-throughput)\n* [Потребители](https://www.rabbitmq.com/consumers.html)",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_messages_delivered_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "Messages acknowledged / s",
     "type": "timeseries",
     "description": "Скорость подтверждений сообщений, поступающих от потребителей, использующих режим ручного подтверждения (manual acknowledgement).\n\n* [Подтверждения потребителей](https://www.rabbitmq.com/confirms.html)\n* [Предзагрузка сообщений потребителем (Consumer Prefetch)](https://www.rabbitmq.com/consumer-prefetch.html)\n* [Режимы подтверждения, предзагрузка и пропускная способность](https://www.rabbitmq.com/confirms.html#channel-qos-prefetch-throughput)\n* [Потребители](https://www.rabbitmq.com/consumers.html)",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_messages_acked_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "Polling operations with auto ack / s",
     "type": "timeseries",
     "description": "Скорость доставки сообщений потребителям с опросом, использующим режим автоматического подтверждения.\n\nИспользование потребителей с опросом крайне неэффективно и поэтому настоятельно не рекомендуется.\n\n* [Получение отдельных сообщений](https://www.rabbitmq.com/consumers.html#fetching)\n* [Потребители](https://www.rabbitmq.com/consumers.html)",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_get_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "Polling operations that yield no result / s",
     "type": "timeseries",
     "description": "Скорость операций опроса потребителей, которые не возвращают результатов.\n\nЛюбое значение выше нуля означает, что ресурсы RabbitMQ тратятся впустую из-за таких потребителей.\n\nСравните эту метрику с другими метриками опроса потребителей, чтобы оценить уровень неэффективности.\n\nИспользование потребителей с опросом крайне неэффективно и настоятельно не рекомендуется.\n\n* [Получение отдельных сообщений](https://www.rabbitmq.com/consumers.html#fetching)\n* [Потребители](https://www.rabbitmq.com/consumers.html)",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_get_empty_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "Polling operations with manual ack / s",
     "type": "timeseries",
     "description": "Скорость доставки сообщений потребителям с опросом, использующим режим ручного подтверждения.\n\nИспользование потребителей с опросом крайне неэффективно и поэтому настоятельно не рекомендуется.\n\n* [Получение отдельных сообщений](https://www.rabbitmq.com/consumers.html#fetching)\n* [Потребители](https://www.rabbitmq.com/consumers.html)\n",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_get_ack_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "QUEUES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total queues",
     "type": "timeseries",
     "description": "Общее количество мастеров очередей на узел.\n\nЭта метрика помогает быстро выявить не оптимальное распределение очередей в кластере.\n\n* [Мастера очередей, локальность данных](https://www.rabbitmq.com/ha.html#master-migration-data-locality)\n* [Очереди](https://www.rabbitmq.com/queues.html)",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rabbitmq_queues{host=\"$host\"} * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "Queues declared / s",
     "type": "timeseries",
     "description": "Скорость создания очередей клиентами.\n\nНебольшие стабильные значения выше нуля являются нормой. Высокие значения могут указывать на частое создание и удаление очередей или высокий уровень восстановления соединений. Для подтверждения уровня восстановления соединений используйте метрику *Connections opened*.\n\n* [Очереди](https://www.rabbitmq.com/queues.html)",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_queues_declared_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "Queues created / s",
     "type": "timeseries",
     "description": "Скорость создания новых очередей (в отличие от повторных объявлений).\n\nНебольшие стабильные значения выше нуля являются нормой. Высокие значения могут указывать на частое создание и удаление очередей или высокий уровень восстановления соединений. Для подтверждения уровня восстановления соединений используйте метрику *Connections opened*.\n\n* [Очереди](https://www.rabbitmq.com/queues.html)",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_queues_created_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "Queues deleted / s",
     "type": "timeseries",
     "description": "Скорость удаления очередей.\n\nНебольшие стабильные значения выше нуля являются нормой. Высокие значения могут указывать на частое создание и удаление очередей или высокий уровень восстановления соединений. Для подтверждения уровня восстановления соединений используйте метрику *Connections opened*.\n\n* [Очереди](https://www.rabbitmq.com/queues.html)\n",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_queues_deleted_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CHANNELS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total channels",
     "type": "timeseries",
     "description": "Общее количество каналов на всех текущих открытых соединениях.\n\nЕсли эта метрика монотонно растёт, это с большой вероятностью указывает на утечку каналов в одном из приложений. Подтвердите утечки каналов, используя метрики *Channels opened* и *Channels closed*.\n\n* [Утечки каналов](https://www.rabbitmq.com/channels.html#channel-leaks)\n* [Каналы](https://www.rabbitmq.com/channels.html)",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rabbitmq_channels{host=\"$host\"} * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "Channels opened / s",
     "type": "timeseries",
     "description": "Скорость открытия новых каналов приложениями по всем соединениям. Ожидается, что каналы будут долгоживущими.\n\nНебольшие стабильные значения выше нуля являются нормой. Высокие значения могут указывать на частое создание и закрытие каналов или массовое восстановление соединений. Для подтверждения уровня восстановления соединений используйте метрику *Connections opened*.\n\n* [Высокая смена каналов](https://www.rabbitmq.com/channels.html#high-channel-churn)\n* [Каналы](https://www.rabbitmq.com/channels.html)\n",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channels_opened_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    },
    {
     "title": "Channels closed / s",
     "type": "timeseries",
     "description": "Скорость закрытия каналов приложениями по всем соединениям. Ожидается, что каналы будут долгоживущими.\n\nНебольшие стабильные значения выше нуля являются нормой. Высокие значения могут указывать на частое открытие и закрытие каналов или массовое восстановление соединений. Для подтверждения уровня восстановления соединений используйте метрику *Connections opened*.\n\n* [Высокая смена каналов](https://www.rabbitmq.com/channels.html#high-channel-churn)\n* [Каналы](https://www.rabbitmq.com/channels.html)\n",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channels_closed_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
       "legendFormat": "{{rabbitmq_node}}"
      }
     ]
    }
   ]
  },
  { "title": "CONNECTIONS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total connections",
   "type": "timeseries",
   "description": "Если эта метрика монотонно растёт, это с большой вероятностью указывает на утечку соединений в одном из приложений. Подтвердите утечки соединений, используя метрики *Connections opened* и *Connections closed*.\n\n* [Утечки соединений](https://www.rabbitmq.com/connections.html#monitoring)\n* [Соединения](https://www.rabbitmq.com/connections.html)\n",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_connections{host=\"$host\"} * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{rabbitmq_node}}"
    }
   ]
  },
  {
   "title": "Connections opened / s",
   "type": "timeseries",
   "description": "Скорость открытия новых соединений клиентами. Ожидается, что соединения будут долгоживущими.\n\nНебольшие стабильные значения выше нуля являются нормой. Высокие значения могут указывать на частое открытие и закрытие соединений или массовое восстановление соединений.\n\n* [Утечки соединений](https://www.rabbitmq.com/connections.html#monitoring)\n* [Соединения](https://www.rabbitmq.com/connections.html)",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_connections_opened_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
     "legendFormat": "{{rabbitmq_node}}"
    }
   ]
  },
  {
   "title": "Connections closed / s",
   "type": "timeseries",
   "description": "Скорость закрытия соединений. Ожидается, что соединения будут долгоживущими.\n\nНебольшие стабильные значения выше нуля являются нормой. Высокие значения могут указывать на частое открытие и закрытие соединений или массовое восстановление соединений.\n\n* [Соединения](https://www.rabbitmq.com/connections.html)",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_connections_closed_total{host=\"$host\"}[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{host=\"$host\", rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) by(rabbitmq_node)",
     "legendFormat": "{{rabbitmq_node}}"
    }
   ]
  }
 ]
}