{
 "title": "monitoring-service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values({app=\"eccm\"},host)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({application=\"monitoring-service\", host=\"$host\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "description": "Показывает, сколько времени сервис работает без перезапуска. Высокое значение указывает на надежную и непрерывную работу.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{host=\"$host\", instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap used",
     "type": "stat",
     "description": "Процент используемой heap-памяти JVM для приложения monitoring-service",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{host=\"$host\", area=\"heap\", instance=\"$instance\"}) / sum(jvm_memory_max_bytes{host=\"$host\", area=\"heap\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "CPU Usage (5m)",
     "type": "timeseries",
     "description": "График изменения процента использования процессора приложением monitoring-service",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "system_cpu_usage{host=\"$host\", instance=\"$instance\"}",
       "legendFormat": "Process (5m)"
      }
     ]
    },
    {
     "title": "JVM Heap",
     "type": "timeseries",
     "description": "График показывает  использование heap-памяти JVM приложением monitoring-service.\n\nИспользуемая память (Used) — текущий объём занятой heap-памяти\n\nВыделенная память (Committed) — объём памяти, зарезервированный JVM для heap\n\nМаксимальная память (Max) — максимальный объём heap-памяти, доступный JVM ",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{host=\"$host\", area=\"heap\", instance=\"$instance\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{host=\"$host\", area=\"heap\", instance=\"$instance\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{host=\"$host\", area=\"heap\", instance=\"$instance\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "description": "Показывает состояние потоков JVM приложения monitoring-service:\n\nLive — текущее количество активных (живых) потоков JVM\n\nDaemon — количество потоков-демонов, работающих в фоновом режиме\n\nPeak — пиковое количество одновременно существовавших потоков с момента запуска JVM",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_live{host=\"$host\", instance=\"$instance\"} or jvm_threads_live_threads{host=\"$host\", instance=~\"$instance\"}",
       "legendFormat": "live"
      },
      {
       "expr": "jvm_threads_daemon{host=\"$host\", instance=\"$instance\"} or jvm_threads_daemon_threads{host=\"$host\", instance=\"$instance\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "jvm_threads_peak{host=\"$host\", instance=\"$instance\"} or jvm_threads_peak_threads{host=\"$host\", instance=\"$instance\"}",
       "legendFormat": "peak"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "stat",
     "description": "Текущее использование CPU (%) для сервиса monitoring-service",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 221 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "system_cpu_usage{host=\"$host\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "LA 1m",
     "type": "stat",
     "description": "Значение системной средней нагрузки (load average) за 1 минуту для приложения monitoring-service",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 221 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "system_load_average_1m{host=\"$host\", instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Discoveries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate запуска discovery",
     "type": "timeseries",
     "description": "Частота запуска задач discovery. Используется для оценки нагрузки и стабильности работы discovery-процессов.\n\n* ~0 — Discovery не работает (возможно, служба упала или настроена слишком редкая проверка).\n* 0.1–0.5 — Нормальная работа (например, 0.3 = 3 запуска каждые 10 секунд).\n* Резко выросло — Discovery начал запускаться чаще, чем обычно (проверьте настройки или логи на ошибки).\n* Упало до нуля — Служба перестала запускаться. (проверьте настройки, проверьте сервис).",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(irate(monitoringservice_scheduled_discoveries_total{host=\"$host\", instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Discoveries"
      }
     ]
    },
    {
     "title": "Время выборки discovery из БД",
     "type": "timeseries",
     "description": "Среднее время выполнения операции выборки данных discovery из базы данных.\n\n* Низкое и стабильное значение времени выборки указывает на эффективную работу базы данных и быстродействие discovery-процессов.\n* Рост среднего времени может сигнализировать о проблемах с производительностью БД, увеличении нагрузки или узких местах в инфраструктуре.\n* Резкие скачки или нестабильность требуют дополнительного анализа и возможной оптимизации.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(monitoringservice_discovery_schedule_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[$__rate_interval]) / \nrate(monitoringservice_discovery_schedule_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Duration"
      }
     ]
    },
    {
     "title": "Время выполнения discovery",
     "type": "timeseries",
     "description": "Среднее время выполнения процесса discovery.\n\n* Низкие значения (например, < 1 сек) указывают на быстрое выполнение discovery, что считается нормальным.\n* Повышение значений может свидетельствовать о деградации производительности, задержках в ответах внешних сервисов или увеличении объёма обрабатываемых данных.\n* Резкие пики — повод проверить логи, метрики нагрузки и сетевые задержки.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(monitoringservice_discovery_execute_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[$__rate_interval]) / rate(monitoringservice_discovery_execute_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Duration"
      }
     ]
    },
    {
     "title": "Время сохранения результатов discovery в БД",
     "type": "timeseries",
     "description": "Среднее время, затрачиваемое на сохранение результатов discovery в базу данных.\n\n* Низкие значения (например, < 0.5 сек) означают, что сохранение результатов работает эффективно и стабильно.\n* Рост среднего времени может указывать на проблемы с производительностью базы данных, блокировки, рост объёма записываемых данных или сетевые задержки.\n* Резкие скачки требуют анализа логов, состояния БД и метрик I/O.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(monitoringservice_discovery_save_results_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[$__rate_interval]) / rate(monitoringservice_discovery_save_results_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Duration"
      }
     ]
    },
    {
     "title": "Rate ошибок выполнения discovery",
     "type": "timeseries",
     "description": "Частота возникновения ошибок при выполнении процессов discovery.\n\n* Низкая или нулевая частота ошибок свидетельствует о корректной работе discovery-механизма.\n* Рост значения может указывать на сбои в логике discovery, нестабильность инфраструктуры.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "sum(irate(monitoringservice_discovery_errors_total{host=\"$host\", instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Discoveries"
      }
     ]
    },
    {
     "title": "Загруженность discovery poller-а",
     "type": "timeseries",
     "description": "Отображение текущей загрузки процесса discovery poller в процентах. Позволяет оценить, насколько эффективно используются ресурсы системы при сканировании и обновлении целевых объектов.\n\n* -60% - Нормальная рабочая нагрузка\n(Система справляется, есть запас ресурсов).\n* 60-80% - Повышенная нагрузка\n(Рекомендуется мониторить динамику, возможны замедления)\n* 80-100% - Критическая загрузка\n(Процесс не справляется, требуется вмешательство: оптимизация или масштабирование)",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "monitoringservice_discovery_poller_load{host=\"$host\", instance=\"$instance\"}",
       "legendFormat": "Duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Items",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate запуска опроса item",
     "type": "timeseries",
     "description": "Показывает общее количество запусков и распределение по типам элементов.\n\n* Общее значение показывает, с какой частотой запускаются задачи опроса элементов в системе.\n* Разбивка по типам помогает понять, какие категории элементов нагружают систему больше всего.\n* Рост или аномалии в частоте запусков могут указывать на изменение нагрузки или проблемы в работе опроса.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "sum(irate(monitoringservice_scheduled_items_total{host=\"$host\", instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Items"
      },
      {
       "expr": "sum(irate(monitoringservice_scheduled_items_by_type_total{host=\"$host\", instance=\"$instance\"}[$__rate_interval])) by (type)",
       "legendFormat": "Items: {{type}}"
      }
     ]
    },
    {
     "title": "Время опроса item",
     "type": "timeseries",
     "description": "Показывает среднее время выполнения опроса элементов (item).\n\n- Низкие значения (например, < 0.1 сек) указывают на быстрое выполнение опросов.\n- Рост среднего времени опроса может указывать на:\n  - замедление сети или системы;\n  - высокую нагрузку на сервис мониторинга;\n- Значения, превышающие допустимые пороги (например, > 1–2 секунд), могут привести к задержкам в сборе метрик и потенциальным пропускам данных.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(monitoringservice_item_poll_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[$__rate_interval]) / rate(monitoringservice_item_poll_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Duration"
      }
     ]
    },
    {
     "title": "Время выборки item из БД",
     "type": "timeseries",
     "description": "Показывает среднее время выполнения запросов выборки items из базы данных.\n\n* Повышение значения может указывать на замедление выборки item'ов из БД — возможны проблемы с производительностью базы данных, увеличившаяся нагрузка или блокировки.\n* Стабильно низкие значения (например, < 0.1 сек) обычно свидетельствуют о нормальной работе и быстром времени отклика.\n* Резкие скачки могут указывать на временные деградации или пиковые нагрузки, требующие дополнительного анализа.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(monitoringservice_item_schedule_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[$__rate_interval]) / rate(monitoringservice_item_schedule_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Duration"
      }
     ]
    },
    {
     "title": "Rate ошибок выполнения опроса item",
     "type": "timeseries",
     "description": "Частота возникновения ошибок при выполнении опросов элементов(items).\n\n* Низкая или нулевая частота ошибок говорит о стабильной работе системы.\n* Повышенные значения у отдельных типов могут указывать на нестабильность конкретных источников данных.\n* Всплески требуют анализа причин: рост нагрузки, таймауты, ошибки сети или проблемы на стороне внешнего сервиса.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "sum(irate(monitoringservice_item_errors_by_type_total{host=\"$host\", instance=\"$instance\"}[$__rate_interval])) by (type)",
       "legendFormat": "Errors: {{type}}"
      }
     ]
    },
    {
     "title": "Загруженность item poller-а",
     "type": "timeseries",
     "description": "Показывает текущую загруженность item poller-а.\n\n* Значение 100% означает, что poller постоянно занят обработкой item’ов без свободного времени — это может указывать на перегрузку.\n* Значения, приближенные к 0%, могут свидетельствовать о недозагрузке poller-а или простое.\n* Оптимальный уровень зависит от конфигурации и целей, но обычно 80–90% — допустимая загруженность, при которой poller работает эффективно, но с резервом по производительности.\n* Резкое увеличение загруженности может быть связано с ростом числа item’ов, замедлением БД, нехваткой потоков или другими проблемами производительности.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "monitoringservice_item_poller_load{host=\"$host\", instance=\"$instance\"}",
       "legendFormat": "Duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate собираемых метрик",
     "type": "timeseries",
     "description": "Отображает общее количество метрик, собираемых системой мониторинга.\n\n* Рост значения означает, что сервис собирает метрики чаще — увеличивается нагрузка на систему.\n* Падение значения может указывать на уменьшение активности сбора или возможные проблемы.\n* Резкие изменения требуют дополнительного анализа для выявления причин.\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum(irate(monitoringservice_produced_metrics_total{host=\"$host\", instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Metrics"
      }
     ]
    },
    {
     "title": "Rate метрик, сохраняемых в БД",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
     "targets": [
      {
       "expr": "sum(rate(monitoringservice_save_metrics_total{host=\"$host\", instance=\"$instance\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Количество сохраняемых метрик",
     "type": "timeseries",
     "description": "Показывает текущее количество метрик на двух ключевых этапах обработки.\nОжидает в буфере — количество метрик, находящихся в буфере ожидания перед записью в базу данных.\nВ процессе сохранения в БД — количество метрик, которые в данный момент обрабатываются.\n\n* Рост значения \"Ожидает в буфере\" может свидетельствовать о задержках в записи метрик, перегрузке или проблемах с базой данных.\n* Высокое значение \"В процессе сохранения в БД\" показывает интенсивную обработку метрик.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "monitoringservice_metric_buffer_size{host=\"$host\", instance=\"$instance\"}",
       "legendFormat": "Ожидает в буфере"
      },
      {
       "expr": "monitoringservice_processing_metric_values{host=\"$host\", instance=\"$instance\"}",
       "legendFormat": "В процессе сохранения в БД"
      }
     ]
    },
    {
     "title": "Время сохранения буфера метрик в БД",
     "type": "timeseries",
     "description": "Показывает среднее время, затрачиваемое на сохранение буфера метрик в базу данных.\n\n* Повышение среднего времени сохранения может свидетельствовать о росте нагрузки на базу данных или задержках в процессе записи.\n* Резкие скачки или тренды на увеличение требуют проверки производительности и стабильности системы.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(monitoringservice_flush_metrics_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[$__rate_interval]) / \nrate(monitoringservice_flush_metrics_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Metrics"
      }
     ]
    }
   ]
  },
  {
   "title": "Problem Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate отправки метрик на problem-manager",
     "type": "timeseries",
     "description": "Показывает частоту  отправки сообщений с метриками сервисом monitoring-service в сервис problem-manager.\n\n* Повышение частоты отправки может указывать на рост количества проблем или событий, обрабатываемых системой.\n* Падение или остановка может сигнализировать о сбоях в отправке или проблемах с интеграцией problem-manager.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum(rate(monitoringservice_problem_manager_messages_total{host=\"$host\", instance=\"$instance\"}[$__rate_interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Adapters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "SNMP Engine: rate SNMP-запросов",
     "type": "timeseries",
     "description": "Показывает скорость обработки SNMP-запросов.\n\n* Повышение значения может указывать на рост SNMP-активности со стороны клиентов или систем мониторинга.\n* Падение может означать снижение нагрузки, проблемы с доступностью SNMP-агента или сети.\n* Значение, стабильно равное 0, может говорить о неработающем SNMP-сервисе, отсутствии трафика или ошибке сбора метрик.\n* Важно сопоставлять эти данные с логами и другими панелями (например, временем ответа или ошибками), чтобы понять причину отклонений.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(monitoringservice_snmp_request_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "SNMP Engine: длительность выполнения SNMP запросов",
     "type": "timeseries",
     "description": "Показывает среднюю длительность выполнения SNMP-запросов.\n\n* Повышенные значения могут свидетельствовать о деградации производительности SNMP-агента, проблемах с сетью или высоких задержках при обработке SNMP-запросов.\n* Стабильно низкие значения (в пределах нескольких миллисекунд) — нормальное поведение для исправно работающей системы.\n* Резкие скачки в графике могут быть индикатором перегрузки, временных сбоев или изменения конфигурации SNMP.\n* Полезно использовать вместе с панелью \"SNMP Engine: rate SNMP-запросов\" для выявления взаимосвязей между нагрузкой и временем обработки.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(monitoringservice_snmp_request_duration_seconds_sum{host=\"$host\", method=\"GET\", instance=\"$instance\"}[$__rate_interval])) / \nsum(rate(monitoringservice_snmp_request_duration_seconds_count{host=\"$host\", method=\"GET\", instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "GET"
      },
      {
       "expr": "sum(rate(monitoringservice_snmp_request_duration_seconds_sum{host=\"$host\", method=\"WALK\", instance=\"$instance\"}[$__rate_interval])) / \nsum(rate(monitoringservice_snmp_request_duration_seconds_count{host=\"$host\", method=\"WALK\", instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "WALK"
      }
     ]
    },
    {
     "title": "SNMP Engine: таймауты SNMP-запросов",
     "type": "timeseries",
     "description": "Показывает процент SNMP-запросов, завершившихся с ошибкой таймаута.\n\n* Рост процента таймаутов может указывать на проблемы с доступностью SNMP-агента, сетевые задержки, перегрузку системы или ошибки конфигурации.\n* Низкое или нулевое значение — ожидаемое поведение в стабильной среде.\n* Если значение превышает порог (например, >5%), рекомендуется провести диагностику сети или SNMP-инфраструктуры.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 *\nsum(rate(monitoringservice_snmp_request_errors_total{host=\"$host\", reason=\"timeout\", instance=\"$instance\"}[$__rate_interval])) /\nsum(rate(monitoringservice_snmp_request_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Timeouts"
      }
     ]
    },
    {
     "title": "Accessor Queue: время ожидания блокировки",
     "type": "timeseries",
     "description": "Показывает среднее время ожидания получения блокировки в очереди.\n\n* Повышенные значения означают увеличение времени ожидания блокировок, что может быть следствием высокой конкуренции за ресурсы, синхронизационных проблем или общего роста нагрузки.\n* Низкие значения говорят о том, что очередь обрабатывается эффективно, без значительных задержек.\n* Резкие всплески могут указывать на \"бутылочные горлышки\" в обработке устройств или необходимости масштабирования.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(monitoringservice_device_accessor_queue_lock_wait_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[$__rate_interval])) / \nsum(rate(monitoringservice_device_accessor_queue_lock_wait_duration_seconds_count{host=\"$host\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "ICMP"
      }
     ]
    },
    {
     "title": "SNMP4j: rate SNMP-пакетов",
     "type": "timeseries",
     "description": "Панель отображает скорость обработки SNMP-пакетов.\n\n* Рост значения указывает на увеличение SNMP-трафика в соответствующем направлении (например, больше входящих или исходящих пакетов).\n*  Падение значения может означать снижение активности SNMP, проблемы с сетью или обработкой пакетов.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(monitoringservice_snmp4j_packets_total{host=\"$host\", instance=\"$instance\"}[$__rate_interval])) by (direction)",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "SNMP4j: количество pending SNMP запросов",
     "type": "timeseries",
     "description": "Показывает текущее количество ожидающих обработки (pending) SNMP-запросов.\n\n* Рост количества pending-запросов может указывать на задержки в обработке, узкие места или перегрузку SNMP-агента или сервиса.\n* Низкие или нулевые значения — признак нормальной работы и своевременной обработки запросов.\n* Постоянно высокий уровень ожидающих запросов требует внимания для предотвращения деградации производительности или потери данных.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "monitoringservice_pending_snmp_requests{host=\"$host\", instance=\"$instance\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "SNMP4j: таймауты SNMP-запросов",
     "type": "timeseries",
     "description": "Показывает процент SNMP-запросов, обработанных с таймаутом.\n\n* Увеличение процента таймаутов может свидетельствовать о проблемах с сетью, недоступности SNMP-агентов или перегрузке системы.\n* Низкие или близкие к нулю значения — признак стабильной работы.\n*  Высокий уровень таймаутов требует проверки конфигурации, состояния сети и SNMP-инфраструктуры.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 *\nsum(rate(monitoringservice_snmp4j_request_timeouts_total{host=\"$host\", instance=\"$instance\"}[$__rate_interval])) /\nsum(rate(monitoringservice_snmp4j_packets_total{host=\"$host\", instance=\"$instance\", direction=\"out\"}[$__rate_interval]))",
       "legendFormat": "Timeouts"
      }
     ]
    },
    {
     "title": "Accessor Queue: максимальный размер очереди",
     "type": "timeseries",
     "description": "Показывает максимальный зафиксированный размер очереди.\n\n* Рост максимального размера очереди может указывать на увеличение нагрузки или узкие места в обработке запросов.\n* Низкие значения свидетельствуют об эффективной обработке очереди без значительных накоплений.\n* Длительно высокий максимальный размер очереди может привести к задержкам и деградации производительности системы.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "monitoringservice_device_accessor_max_queue_size{host=\"$host\", instance=\"$instance\"}",
       "legendFormat": "ICMP"
      }
     ]
    },
    {
     "title": "Длительность ICMP-запросов",
     "type": "timeseries",
     "description": "Показывает среднее время выполнения ICMP-запросов.\n\n* Повышение средней длительности может указывать на ухудшение сетевой задержки или проблемы с обработкой ICMP-запросов.\n* Низкие и стабильные значения свидетельствуют о нормальном состоянии сети и своевременной обработке запросов.\n* Всплески длительности могут сигнализировать о временных сбоях, перегрузках или проблемах с маршрутизацией.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(monitoringservice_icmp_request_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[$__rate_interval])) / \nsum(rate(monitoringservice_icmp_request_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Duration"
      }
     ]
    }
   ]
  },
  { "title": "Redis Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Read rate",
   "type": "timeseries",
   "description": "Показывает скорость операций чтения (decode). Позволяет отслеживать нагрузку на систему декодирования и выявлять объекты с наибольшим числом операций чтения.\n\n* Рост общей скорости чтения может свидетельствовать об увеличении нагрузки на сервис или усилении активности клиентов.\n* Если наблюдается значительный вклад отдельных объектов, это может указывать на узкие места, требующие оптимизации.\n* Снижение скорости чтения ниже ожидаемого уровня может говорить о проблемах в работе компонента декодирования или уменьшении пользовательской активности.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(monitoring_service_redisson_codec_total{host=\"$host\", instance=\"$instance\", operation=\"decode\"}[$__rate_interval]))",
     "legendFormat": "ALL"
    },
    {
     "expr": "sum(rate(monitoring_service_redisson_codec_total{host=\"$host\", instance=\"$instance\", operation=\"decode\"}[$__rate_interval])) by (object)",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "Write rate",
   "type": "timeseries",
   "description": "Показывает скорость операций записи.\n\n* Увеличение общей скорости записи свидетельствует о возрастании нагрузки на систему кодирования.\n* Высокая активность по отдельным объектам, может указывать на узкие места, требующие оптимизации.\n* Падение скорости записи может сигнализировать о снижении активности или проблемах в компонентах записи/кодирования.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(rate(monitoring_service_redisson_codec_total{host=\"$host\", instance=\"$instance\", operation=\"encode\"}[$__rate_interval]))",
     "legendFormat": "ALL"
    },
    {
     "expr": "sum(rate(monitoring_service_redisson_codec_total{host=\"$host\", instance=\"$instance\", operation=\"encode\"}[$__rate_interval])) by (object)",
     "legendFormat": "{{object}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Rate вычисления шаблонных выражений",
   "type": "timeseries",
   "description": "Показывает частоту вычисления шаблонных выражений.\n* Рост значения говорит об увеличении нагрузки на подсистему вычисления шаблонных выражений, что может влиять на общую производительность сервиса.\n* Резкие скачки могут указывать на всплески активности или потенциальные проблемы с оптимизацией шаблонов.\n* Стабильно низкие значения показывают относительно малую активность и низкую нагрузку в данном компоненте.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(irate(monitoringservice_expression_eval_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Expressions"
    }
   ]
  },
  {
   "title": "Время вычисления шаблонных выражений",
   "type": "timeseries",
   "description": "Показывает среднее время выполнения шаблонных выражений.\n\n* Увеличение среднего времени вычисления может указывать на рост сложности шаблонов или снижение производительности системы.\n* Стабильное или снижающееся время говорит о нормальной работе и оптимальной нагрузке.\n* Резкие скачки времени выполнения могут свидетельствовать о проблемах с конкретными выражениями или изменениях в инфраструктуре.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(monitoringservice_expression_eval_duration_seconds_sum{host=\"$host\", instance=\"$instance\"}[$__rate_interval]) / rate(monitoringservice_expression_eval_duration_seconds_count{host=\"$host\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Duration"
    }
   ]
  }
 ]
}