version: "3.8"

# Главная секция, где описываются сервисы (контейнеры).
services:
  # Определяем сервис для нашего приложения.
  my-first-app-service:
    # Жестко задаем имя контейнера, чтобы к нему было легко обращаться.
    container_name: "my-first-app"
    
    # Инструкция Docker'у: собери образ для этого сервиса из папки ./my-first-app-src,
    # используя Dockerfile, который там лежит.
    build: ./my-first-app-src
    
    # Подключаем контейнер к существующей сети.
    networks:
      # Подключаем к сети, которую мы логически назвали 'internal_network'
      - internal_network
      
    # Самая важная часть: "стикеры" для системы мониторинга.
    # Это метаданные, которые vmagent будет читать, чтобы понять, как опрашивать этот контейнер.
    labels:
      # Метка №1: Сообщает vmagent'у, что этот контейнер нужно мониторить и под каким именем (job).
      ru.eltex-co.metrics.job: "student-app"
      # Метка №2: Указывает, по какому пути (URL-path) находятся метрики.
      ru.eltex-co.metrics.path: "metrics"
      # Метка №3: Указывает, на каком порту внутри контейнера работает веб-сервер с метриками.
      ru.eltex-co.metrics.port: "9191"

# Секция, где мы описываем сети, используемые в этом файле.
networks:
  # Даем нашей сети логическое имя 'internal_network' для использования внутри этого файла.
  internal_network:
    # Ключевая директива: говорим Docker Compose "не создавай эту сеть".
    external: true
    # Указываем, к какой УЖЕ СУЩЕСТВУЮЩЕЙ сети нужно подключиться из основного композа
    name: "internal"
