{
 "title": "PostgreSQL Database",
 "description": "This dashboard works with postgres_exporter",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
    }
   },
   {
    "name": "release",
    "label": "Release",
    "query": {
     "query": "query_result(pg_exporter_last_scrape_duration_seconds{kubernetes_namespace=\"$namespace\"})"
    }
   },
   { "name": "host", "label": "Host", "query": { "query": "label_values(pg_up,host)" } },
   {
    "name": "dbms",
    "label": "DBMS",
    "query": {
     "query": "label_values(pg_up{host=\"$host\"},source_host)"
    }
   },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } },
   {
    "name": "mode",
    "label": "Lock table",
    "query": {
     "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"},mode)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Версия базы данных PostgreSQL",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{release=\"$release\",source_host=\"$dbms\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "description": "Время запуска docker-контейнера \"postgres-exporter\". Данный контейнер отправляет данные с клиента на сервер",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_postmaster_start_time_seconds{release=\"$release\",source_host=\"$dbms\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current fetch data",
   "type": "stat",
   "description": "Объем считанных блоков данных из базы данных. Необходимо для мониторинга эффективности кеширования и оценки нагрузки на базу данных. Использовать до 70% от доступного объема кэша во избежание перегрузки системы",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_tup_fetched{datname=~\"$datname\",source_host=~\"$dbms\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "stat",
   "description": "Количество данных, записываемых в БД. Необходимо для отслеживания нагрузки на запись и выявление проблем с диском. Использовать до 70% от доступного объема диска во избежание переполнения дискового пространства",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  pg_stat_database_tup_inserted{\n    release=\"$release\",datname=~\"$datname\",source_host=~\"$dbms\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "stat",
   "description": "Объем обновления данных в базе данных. Необходимо для отслеживания интенсивности изменений и нагрузки на диски. Использовать до 70% от доступного объема диска во избежание перегрузки дисковой подсистемы",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_tup_updated{datname=~\"$datname\",source_host=~\"$dbms\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "description": "Максимальное количество клиентов, которые могут подключиться к PostgreSQL одновременно",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{release=\"$release\",source_host=\"$dbms\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "description": "Средняя загрузка центрального процессора каждые 5 минут. Помогает выявлять перегрузку сервера. Использовать до 80% от доступной мощности CPU во избежание перегрева и перегрузки системы",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n  rate(process_cpu_seconds_total{release=\"$release\",source_host=\"$dbms\"}[5m])\n    *\n  1000\n)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "description": "Среднее использование виртуальной и постоянной памяти в байтах каждые 5 минут. Использовать до 75% от доступной оперативной памяти во избежание свопинга",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(\n  rate(\n    process_resident_memory_bytes{release=\"$release\",source_host=\"$dbms\"}[5m]\n  )\n)",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(\n  rate(\n    process_virtual_memory_bytes{release=\"$release\",source_host=\"$dbms\"}[5m]\n  )\n)",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Количество открытых файловых дескрипторов (уникальных идентификаторов файлов/ресурсов в ОС). Нужен для мониторинга, чтобы избежать утечки дескрипторов и перегрузки системы. Использовать до 80% от настройки \"max_files_per_process\" во избежание перегрузки системы",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{release=\"$release\",source_host=\"$dbms\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  { "title": "Settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "description": "Объем оперативной памяти, выделенной базой данных для кэширования. Нужна для мониторинга и настройки производительности СУБД, чтобы убедиться, что сервер эффективно использует память",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{source_host=\"$dbms\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "stat",
   "description": "Предполагаемый максимальный объем памяти, доступный для кеширования данных файловой системой и дисками. Нужна для оптимизации запросов, чтобы PostgreSQL корректно оценивал стоимость операций ввода-вывода при планировании выполнения",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{source_host=\"$dbms\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "stat",
   "description": "Объём памяти, выделенный PostgreSQL для операций обслуживания (VACUUM, CREATE INDEX и др.). Метрика нужна для контроля и настройки памяти, чтобы тяжёлые фоновые задачи не конкурировали с основными запросами за ресурсы.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{source_host=\"$dbms\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "stat",
   "description": "Объём памяти, выделяемый PostgreSQL для операций сортировки и хеширования при выполнении отдельных запросов. Нужна для балансировки производительности: слишком маленькое значение замедляет сложные запросы, а слишком большое — может привести к избыточному потреблению памяти при множестве одновременных операций",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{source_host=\"$dbms\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "description": "Максимальный размер WAL-журналов (журнал предварительной записи), используемых PostgreSQL для обеспечения надежности данных в базе данных. Нужна для контроля дискового пространства и настройки баланса между производительностью записи и безопасностью данных",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_wal_size_bytes{source_host=\"$dbms\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Random Page Cost",
   "type": "stat",
   "description": "Стоимость произвольного доступа к данным на диске при планировании запросов или условный коэффициент, используемый для сравнения операции произвольного доступа к диску относительно последовательного чтения данных. Нужна данная метрика для оптимизации работы планировщика PostgreSQL, помогая выбирать наиболее эффективные планы выполнения запросов в зависимости от типа хранилища (HDD/SSD)",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_random_page_cost{source_host=\"$dbms\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Seq Page Cost",
   "type": "stat",
   "description": "Стоимость последовательного чтения данных с диска при планировании запросов. Является основной единицей при оценке стоимости других операций.",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_seq_page_cost{source_host=\"$dbms\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "stat",
   "description": "Максимальное количество фоновых процессов, которые PostgreSQL может использовать для параллельных операций",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{source_host=\"$dbms\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "stat",
   "description": "Максимальное количество параллельных воркеров (потоки, выполняющие задачи по обработке запросов), которые могут использоваться для выполнения одного запроса. Нужна данная метрика для управления степенью параллелизма при обработке сложных запросов и оптимизации нагрузки на систему.",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers{source_host=\"$dbms\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "description": "Количество активных подключений к базам данных PostgreSQL в реальном времени. Нужна метрика для мониторинга нагрузки на сервер БД и выявления потенциальных проблем с подключениями. Использовать до 85% от настройки \"Максимальное количество подключений\" во избежание перегрузки сервера",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n  pg_stat_activity_count{\n    datname=~\"$datname\",source_host=~\"$dbms\",state=\"active\"\n  }\n) by(datname,instance,state)\n  !=\n0",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "timeseries",
   "description": "Количество блокировок разных типов (пессимистические, оптимистические, строчные и др.) в базах данных PostgreSQL. Нужна данная метрика для мониторинга конфликтов доступа к данным и выявления потенциальных проблем с параллельными транзакциями.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  pg_locks_count{datname=~\"$datname\",source_host=~\"$dbms\",mode=~\"$mode\"}\n) by(datname,instance,mode)\n  !=\n0",
     "legendFormat": "{{datname}},{{mode}}"
    }
   ]
  },
  {
   "title": "Idle sessions",
   "type": "timeseries",
   "description": "Состояния подключений к базе данных PostgreSQL. Он используется для получения количества подключений в различных состояниях (idle, idle in transaction, idle in transaction (aborted)) для указанных баз данных (eccm, postgres, template0, template1) с интервалом в 10 секунд.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  pg_stat_activity_count{\n    datname=~\"$datname\",\n    source_host=~\"$dbms\",\n    state=~\"idle|idle in transaction|idle in transaction (aborted)\"\n  }\n) by(datname,instance,state)",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "Скорость транзакций в базе данных PostgreSQL. Используется для получения данных о количестве транзакций в секунду для указанных баз данных (eccm, postgres, template0, template1) с интервалом в 10 секунд. Использовать до 70% от максимальной пропускной способности системы, чтобы избежать перегрузки CPU и дисковой подсистемы",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(\n  pg_stat_database_xact_commit{source_host=\"$dbms\",datname=~\"$datname\"}[5m]\n)",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(\n  pg_stat_database_xact_rollback{source_host=\"$dbms\",datname=~\"$datname\"}[5m]\n)",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Insert data",
   "type": "timeseries",
   "description": "Количество строк, добавленных в таблицы базы данных PostgreSQL.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=~\"$datname\",source_host=~\"$dbms\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Fetch data (SELECT)",
   "type": "timeseries",
   "description": "Количество строк, полученных из баз данных PostgreSQL. Метрика используется для мониторинга активности запросов и выявления потенциальных проблем с производительностью",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{datname=~\"$datname\",source_host=~\"$dbms\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Update data",
   "type": "timeseries",
   "description": "Количество строк, над которыми производились обновления в базе данных PostgreSQL. Используется для отслеживания изменений данных и анализа нагрузки на базу данных.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{datname=~\"$datname\",source_host=~\"$dbms\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Delete data",
   "type": "timeseries",
   "description": "Количество удаленных строк в базах данных PostgreSQL. Используется для мониторинга активности удаления данных и выявления аномалий",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_deleted{datname=~\"$datname\", source_host=~\"$dbms\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Return data",
   "type": "timeseries",
   "description": "Количество строк, прочитанных из баз данных PostgreSQL. Используется для анализа нагрузки на чтение и оптимизации запросов",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_returned{datname=~\"$datname\", source_host=~\"$dbms\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "description": "Метрика вычисляет cache hit ratio (эффективность кеширования) для баз данных PostgreSQL, показывая долю блоков, полученных из кеша, а не с диска. Используется для оценки производительности СУБД и настройки размера буферного кэша.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{source_host=\"$dbms\",datname=~\"$datname\"}\n  /\n(\n  pg_stat_database_blks_read{source_host=\"$dbms\",datname=~\"$datname\"}\n    +\n  pg_stat_database_blks_hit{source_host=\"$dbms\",datname=~\"$datname\"}\n)",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "timeseries",
   "description": "Активность фоновых процессов записи (bgwriter) в PostgreSQL, включая аллокацию буферов, запись на диск и контрольные точки. Используются для анализа нагрузки на ввод-вывод и оптимизации производительности СУБД:\n    buffers_alloc – выделение буферов бэкендами\n\n    buffers_backend – запись буферов бэкендами\n\n    buffers_backend_fsync – принудительная синхронизация на диск\n\n    buffers_checkpoint – запись буферов во время контрольных точек\n\n    buffers_clean – очистка буферов фоновым писателем\n\nИспользовать до 65-70% от доступной мощности дисковой подсистемы во избежание перегрузки системы",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_total{source_host=\"$dbms\"}[5m])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc_total{source_host=\"$dbms\"}[5m])",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync_total{source_host=\"$dbms\"}[5m])",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint_total{source_host=\"$dbms\"}[5m])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean_total{source_host=\"$dbms\"}[5m])",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "timeseries",
   "description": "Метрики, отслеживающие конфликты (отменённые запросы из-за конфликтов репликации/восстановления) и взаимоблокировки (обнаруженные взаимоблокировки, требующие вмешательства) в базах PostgreSQL, возникающие при конкуренции за ресурсы. Используются для выявления проблем с параллельными транзакциями и оптимизации workload",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts{source_host=\"$dbms\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{source_host=\"$dbms\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  },
  {
   "title": "Temp File (Bytes)",
   "type": "timeseries",
   "description": "Общий объем данных, записываемых во временные файлы запросами в этой базе данных. Учитываются все временные файлы, независимо от того, для чего был создан временный файл, и независимо от параметра log_temp_files. Использовать до 5-15% от доступного объема диска во избежание переполнения дискового пространства",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_temp_bytes{source_host=\"$dbms\",datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "timeseries",
   "description": "Время выполнения контрольных точек (checkpoints) в PostgreSQL, разделяя его на фазу записи на диск (write_time - физическая запись данных на диск) и синхронизации (sync_time - время принудительной синхронизации данных с диском). Используются для диагностики задержек ввода-вывода и настройки интервалов контрольных точек",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time_total{source_host=\"$dbms\"}[5m])",
     "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
    },
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time_total{source_host=\"$dbms\"}[5m])",
     "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
    }
   ]
  }
 ]
}