{
 "title": "HAProxy dashboard",
 "description": "HAProxy dashboard",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(haproxy_process_nbproc,host)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(haproxy_process_nbproc{host=\"$host\"},container)"
    }
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_status{container=\"$container\"},proxy)"
    }
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": {
     "query": "label_values(haproxy_frontend_status{container=\"$container\"},proxy)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(haproxy_server_status{container=\"$container\"},server)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_server_http_responses_total{container=\"$container\"},code)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "Basic General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP response / request",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    haproxy_frontend_http_responses_total{\n      proxy=~\"$frontend\",code=~\"$code\",container=\"$container\"\n    }[$__rate_interval]\n  )\n) by(code)",
     "legendFormat": "Front {{ code }}"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_backend_http_responses_total{\n      proxy=~\"$backend\",code=~\"$code\",container=\"$container\"\n    }[$__rate_interval]\n  )\n) by(code)",
     "legendFormat": "Back {{ code }}"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_frontend_http_requests_total{\n      proxy=~\"$frontend\",container=\"$container\"\n    }[$__rate_interval]\n  )\n) by(container)",
     "legendFormat": "Front requests"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_backend_http_requests_total{\n      proxy=~\"$backend\",container=\"$container\"\n    }[$__rate_interval]\n  )\n) by(container)",
     "legendFormat": "Back requests"
    }
   ]
  },
  {
   "title": "Front - Data transfer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    haproxy_frontend_bytes_in_total{proxy=~\"$frontend\",container=\"$container\"}[$__rate_interval]\n  )\n    *\n  8\n) by(container)",
     "legendFormat": "IN Front"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_frontend_bytes_out_total{proxy=~\"$frontend\",container=\"$container\"}[$__rate_interval]\n  )\n    *\n  8\n) by(container)",
     "legendFormat": "OUT Front"
    }
   ]
  },
  {
   "title": "Back - Data transfer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    haproxy_backend_bytes_in_total{proxy=~\"$backend\",container=\"$container\"}[$__rate_interval]\n  )\n    *\n  8\n) by(container)",
     "legendFormat": "IN Back"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_backend_bytes_out_total{proxy=~\"$backend\",container=\"$container\"}[$__rate_interval]\n  )\n    *\n  8\n) by(container)",
     "legendFormat": "OUT Back"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    haproxy_frontend_sessions_total{proxy=~\"$frontend\",container=\"$container\"}[$__rate_interval]\n  )\n) by(container)",
     "legendFormat": "Front"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_backend_sessions_total{proxy=~\"$backend\",container=\"$container\"}[$__rate_interval]\n  )\n) by(container)",
     "legendFormat": "Back"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    haproxy_frontend_connections_total{\n      proxy=~\"$frontend\",container=\"$container\"\n    }[$__rate_interval]\n  )\n) by(container)",
     "legendFormat": "Front"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_backend_connection_attempts_total{\n      proxy=~\"$backend\",container=\"$container\"\n    }[$__rate_interval]\n  )\n) by(container)",
     "legendFormat": "Back"
    }
   ]
  },
  {
   "title": "Status UP",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 22, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(haproxy_frontend_status{container=\"$container\",state=\"UP\"} == 1)",
     "legendFormat": "Front Up"
    },
    {
     "expr": "sum(haproxy_backend_status{container=\"$container\",state=\"UP\"} == 1)",
     "legendFormat": "Back Up"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - haproxy_process_start_time_seconds{container=\"$container\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests / Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - HTTP requests Total / Error / Denied",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1026 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_frontend_http_requests_total{\n    proxy=~\"$frontend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "rate(\n  haproxy_frontend_request_errors_total{\n    proxy=~\"$frontend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "Error {{ proxy }}"
      },
      {
       "expr": "rate(\n  haproxy_frontend_requests_denied_total{\n    proxy=~\"$frontend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - HTTP requests Total / Denied",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1026 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_backend_http_requests_total{proxy=~\"$backend\",container=\"$container\"}[$__rate_interval]\n)",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "rate(\n  haproxy_backend_requests_denied_total{\n    proxy=~\"$backend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - HTTP responses",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1040 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(\n  rate(\n    haproxy_frontend_http_responses_total{\n      proxy=~\"$frontend\",code=~\"$code\",container=\"$container\"\n    }[$__rate_interval]\n  )\n) by(proxy)",
       "legendFormat": "{{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - HTTP responses",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1040 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(\n  rate(\n    haproxy_backend_http_responses_total{\n      proxy=~\"$backend\",code=~\"$code\",container=\"$container\"\n    }[$__rate_interval]\n  )\n) by(proxy)",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - HTTP responses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1053 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(\n  rate(\n    haproxy_server_http_responses_total{\n      proxy=~\"$backend\",server=~\"$server\",code=~\"$code\",container=\"$container\"\n    }[$__rate_interval]\n  )\n) by(proxy,server)",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Front - HTTP responses code",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1061 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_frontend_http_responses_total{\n    proxy=~\"$frontend\",code=~\"$code\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "{{ code }} {{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - HTTP responses code",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1061 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_backend_http_responses_total{\n    proxy=~\"$backend\",code=~\"$code\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "{{ code }} {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - HTTP responses code",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1074 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_server_http_responses_total{\n    proxy=~\"$backend\",server=~\"$server\",code=~\"$code\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "{{ code }} - {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Front - HTTP responses denied",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1083 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_frontend_responses_denied_total{\n    proxy=~\"$frontend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - HTTP responses denied",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1083 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_backend_responses_denied_total{\n    proxy=~\"$backend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - HTTP responses denied",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1097 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_server_responses_denied_total{\n    proxy=~\"$backend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Back - Error / Redispatch / Retry",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1106 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_backend_redispatch_warnings_total{\n    proxy=~\"$backend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "Redispatch {{ proxy }}"
      },
      {
       "expr": "rate(\n  haproxy_backend_retry_warnings_total{proxy=~\"$backend\",container=\"$container\"}[$__rate_interval]\n)",
       "legendFormat": "Retry {{ proxy }}"
      },
      {
       "expr": "rate(\n  haproxy_backend_response_errors_total{\n    proxy=~\"$backend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "Error {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Error / Redispatch / Retry",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1120 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_server_redispatch_warnings_total{\n    proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "Redispatch {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(\n  haproxy_server_retry_warnings_total{\n    proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "Retry {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(\n  haproxy_server_response_errors_total{\n    proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "Error {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput / Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - Data transfer",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 1130 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_frontend_bytes_in_total{proxy=~\"$frontend\",container=\"$container\"}[$__rate_interval]\n)\n  *\n8",
       "legendFormat": "IN {{ proxy }}"
      },
      {
       "expr": "rate(\n  haproxy_frontend_bytes_out_total{proxy=~\"$frontend\",container=\"$container\"}[$__rate_interval]\n)\n  *\n8",
       "legendFormat": "OUT {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Data transfer",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 1130 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_backend_bytes_in_total{proxy=~\"$backend\",container=\"$container\"}[$__rate_interval]\n)\n  *\n8",
       "legendFormat": "IN {{ proxy }}"
      },
      {
       "expr": "rate(\n  haproxy_backend_bytes_out_total{proxy=~\"$backend\",container=\"$container\"}[$__rate_interval]\n)\n  *\n8",
       "legendFormat": "OUT {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Data transfer",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1145 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_server_bytes_in_total{\n    proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n  }[$__rate_interval]\n)\n  *\n8",
       "legendFormat": "IN {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(\n  haproxy_server_bytes_out_total{\n    proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n  }[$__rate_interval]\n)\n  *\n8",
       "legendFormat": "OUT {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Front - Connections Accepted / Denied",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 1152 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_frontend_connections_total{proxy=~\"$frontend\",container=\"$container\"}[$__rate_interval]\n)",
       "legendFormat": "Accepted {{ proxy }}"
      },
      {
       "expr": "rate(\n  haproxy_frontend_denied_connections_total{\n    proxy=~\"$frontend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Connections Attempts / Errors",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 1152 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_backend_connection_attempts_total{\n    proxy=~\"$backend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "Attempt {{ proxy }}"
      },
      {
       "expr": "rate(\n  haproxy_backend_connection_errors_total{\n    proxy=~\"$backend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "Error {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Connections Attempts / Error",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1167 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_server_connection_attempts_total{\n    proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "Attempts {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(\n  haproxy_server_connection_errors_total{\n    proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "Error {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Back - Connections reuses",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 1174 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_backend_connection_reuses_total{\n    proxy=~\"$backend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Connections reuses",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1189 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_server_connection_reuses_total{\n    proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "Reuses {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - Sessions",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1197 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_frontend_sessions_total{proxy=~\"$frontend\",container=\"$container\"}[$__rate_interval]\n)",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "rate(\n  haproxy_frontend_denied_sessions_total{\n    proxy=~\"$frontend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Sessions",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1197 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_backend_sessions_total{proxy=~\"$backend\",container=\"$container\"}[$__rate_interval]\n)",
       "legendFormat": "Total {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Session",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1210 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_server_sessions_total{\n    proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Front - Session usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1217 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(\n  max_over_time(\n    haproxy_frontend_current_sessions{proxy=~\"$frontend\",container=\"$container\"}[$__rate_interval]\n  )\n    /\n  haproxy_frontend_limit_sessions{proxy=~\"$frontend\",container=\"$container\"}\n)\n  *\n100",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Session usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1217 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(\n  max_over_time(\n    haproxy_backend_current_sessions{proxy=~\"$backend\",container=\"$container\"}[$__rate_interval]\n  )\n    /\n  haproxy_backend_limit_sessions{proxy=~\"$backend\",container=\"$container\"}\n)\n  *\n100",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Sessions Max",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1228 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "haproxy_frontend_max_sessions{proxy=~\"$frontend\",container=\"$container\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Sessions Max",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1228 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "haproxy_backend_max_sessions{proxy=~\"$backend\",container=\"$container\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Session Max",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1241 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "haproxy_server_max_sessions{\n  proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Front - Failed HTTP header rewrites",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1248 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_frontend_failed_header_rewriting_total{\n    proxy=~\"$frontend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Failed HTTP header rewrites",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1248 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_backend_failed_header_rewriting_total{\n    proxy=~\"$backend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Failed HTTP header rewrites",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1261 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_server_failed_header_rewriting_total{\n    proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "{{ proxy }} /  {{ server }}"
      }
     ]
    },
    {
     "title": "Back -  Data transfers aborted",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1268 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_client_aborts_total{proxy=~\"$backend\",container=\"$container\"}[$__rate_interval])",
       "legendFormat": "Client {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_server_aborts_total{proxy=~\"$backend\",container=\"$container\"}[$__rate_interval])",
       "legendFormat": "Server {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server -  Data transfers aborted",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1281 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_server_client_aborts_total{\n    proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "Client {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(\n  haproxy_server_server_aborts_total{\n    proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "Server {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Average connection time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1345 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_connect_time_average_seconds{\n  proxy=~\"$backend\",container=\"$container\"\n}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Average total conn. time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1345 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_total_time_average_seconds{\n  proxy=~\"$backend\",container=\"$container\"\n}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Average connection time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1359 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_connect_time_average_seconds{\n  proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Average total conn. time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1366 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_total_time_average_seconds{\n  proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Back - Average response time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1373 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_response_time_average_seconds{\n  proxy=~\"$backend\",container=\"$container\"\n}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Average queue time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1373 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_queue_time_average_seconds{\n  proxy=~\"$backend\",container=\"$container\"\n}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Average response time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1387 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_response_time_average_seconds{\n  proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Average queue time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1394 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_queue_time_average_seconds{\n  proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Health and Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - UP->DOWN transitions",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1402 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_backend_check_up_down_total{proxy=~\"$backend\",container=\"$container\"}[$__rate_interval]\n)",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Service weight",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1402 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_weight{proxy=~\"$backend\",container=\"$container\"}",
       "legendFormat": "{{ proxy }}"
      },
      {
       "expr": "haproxy_backend_uweight{proxy=~\"$backend\",container=\"$container\"}\n  -\nhaproxy_backend_weight{proxy=~\"$backend\",container=\"$container\"}",
       "legendFormat": "User diff - {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - UP->DOWN transitions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1416 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_server_check_up_down_total{\n    proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Service weight",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1423 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_server_weight{\n  proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_uweight{\n  proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n}\n  -\nhaproxy_server_weight{\n  proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n}",
       "legendFormat": "User diff - {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Checks failures",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1430 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_server_check_failures_total{\n    proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Checks duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1437 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_check_duration_seconds{\n  proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Last session assigned",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1444 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_last_session_seconds{\n  proxy=~\"$backend\",server=~\"$server\",container=\"$container\"\n}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache / Compressor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - Cache Lookups / Hits",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1452 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_frontend_http_cache_lookups_total{\n    proxy=~\"$frontend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "Lookups {{ proxy }} "
      },
      {
       "expr": "rate(\n  haproxy_frontend_http_cache_hits_total{\n    proxy=~\"$frontend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "Hits {{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Cache Lookups / Hits",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1452 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_backend_http_cache_lookups_total{\n    proxy=~\"$backend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "Lookups {{ proxy }} "
      },
      {
       "expr": "rate(\n  haproxy_backend_http_cache_hits_total{\n    proxy=~\"$backend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "Hits {{ proxy }} "
      }
     ]
    },
    {
     "title": "Front - Data transfer http compressor",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1463 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_frontend_http_comp_bytes_in_total{\n    proxy=~\"$frontend\",container=\"$container\"\n  }[$__rate_interval]\n)\n  *\n8",
       "legendFormat": "IN {{ proxy }} "
      },
      {
       "expr": "rate(\n  haproxy_frontend_http_comp_bytes_out_total{\n    proxy=~\"$frontend\",container=\"$container\"\n  }[$__rate_interval]\n)\n  *\n8",
       "legendFormat": "OUT {{ proxy }} "
      },
      {
       "expr": "rate(\n  haproxy_frontend_http_comp_bytes_bypassed_total{\n    proxy=~\"$frontend\",container=\"$container\"\n  }[$__rate_interval]\n)\n  *\n8",
       "legendFormat": "Bypass  {{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Data transfer http compressor",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1463 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_backend_http_comp_bytes_in_total{\n    proxy=~\"$backend\",container=\"$container\"\n  }[$__rate_interval]\n)\n  *\n8",
       "legendFormat": "IN {{ proxy }} "
      },
      {
       "expr": "rate(\n  haproxy_backend_http_comp_bytes_out_total{\n    proxy=~\"$backend\",container=\"$container\"\n  }[$__rate_interval]\n)\n  *\n8",
       "legendFormat": "OUT {{ proxy }} "
      },
      {
       "expr": "rate(\n  haproxy_backend_http_comp_bytes_bypassed_total{\n    proxy=~\"$backend\",container=\"$container\"\n  }[$__rate_interval]\n)\n  *\n8",
       "legendFormat": "Bypass  {{ proxy }} "
      }
     ]
    },
    {
     "title": "Front - Responses compressed",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1474 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_frontend_http_comp_responses_total{\n    proxy=~\"$frontend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "{{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Responses compressed",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1474 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_backend_http_comp_responses_total{\n    proxy=~\"$backend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "{{ proxy }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - Status",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1627 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "haproxy_frontend_status{proxy=~\"$frontend\",container=\"$container\",state=\"UP\"}",
       "legendFormat": "{{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Status",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1627 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "haproxy_backend_status{proxy=~\"$backend\",container=\"$container\",state=\"UP\"}",
       "legendFormat": "{{ proxy }} "
      }
     ]
    },
    {
     "title": "Server - Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1638 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "haproxy_server_status{\n  proxy=~\"$backend\",server=~\"$server\",container=\"$container\",state=\"UP\"\n}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Status other",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1646 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "haproxy_server_status{\n  proxy=~\"$backend\",server=~\"$server\",container=\"$container\",state!~\"UP|DOWN\"\n}",
       "legendFormat": "{{ proxy }} / {{ server }} - {{state}}"
      }
     ]
    },
    {
     "title": "Front - Internal errors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1654 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_frontend_internal_errors_total{\n    proxy=~\"$frontend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Internal errors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1654 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_backend_internal_errors_total{\n    proxy=~\"$backend\",container=\"$container\"\n  }[$__rate_interval]\n)",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Internal errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1665 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_server_internal_errors_total{proxy=~\"$backend\",container=\"$container\"}[$__rate_interval]\n)",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Sticktable usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1672 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_sticktable_size{proxy=~\"$backend\",container=\"$container\"}",
       "legendFormat": "{{ proxy }}"
      },
      {
       "expr": "haproxy_sticktable_used{proxy=~\"$backend\",container=\"$container\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Active servers",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1672 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_active_servers{proxy=~\"$backend\",container=\"$container\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Backup servers",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1683 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_backup_servers{proxy=~\"$backend\",container=\"$container\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - Connection rate limits",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1769 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_max_connection_rate{container=\"$container\"}",
       "legendFormat": "Highest ConnRate reached on this worker process since started (in connections per second)"
      },
      {
       "expr": "haproxy_process_limit_connection_rate{container=\"$container\"}",
       "legendFormat": "Hard limit for ConnRate (global.maxconnrate)"
      }
     ]
    },
    {
     "title": "Process - Connections limits",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1769 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_current_connections{container=\"$container\"}",
       "legendFormat": "Current number of connections on this worker process"
      },
      {
       "expr": "haproxy_process_hard_max_connections{container=\"$container\"}",
       "legendFormat": "Hard limit on the number of per-process connections (imposed by Memmax_MB or ulimit -n)"
      }
     ]
    },
    {
     "title": "Process - Sessions limits",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1769 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_max_session_rate{container=\"$container\"}",
       "legendFormat": "Highest SessRate reached on this worker process since started (in sessions per second)"
      },
      {
       "expr": "haproxy_process_limit_session_rate{container=\"$container\"}",
       "legendFormat": "Hard limit for SessRate (global.maxsessrate)"
      }
     ]
    },
    {
     "title": "Process - SSL conn. rate limits",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1779 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_max_ssl_rate{container=\"$container\"}",
       "legendFormat": "Highest ConnRate reached on this worker process since started (in connections per second)"
      },
      {
       "expr": "haproxy_process_limit_ssl_rate{container=\"$container\"}",
       "legendFormat": "Hard limit for SslRate (global.maxsslrate)"
      }
     ]
    },
    {
     "title": "Process - SSL conn. limits",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1779 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_current_ssl_connections{container=\"$container\"}",
       "legendFormat": "SSL endpoints"
      },
      {
       "expr": "haproxy_process_max_ssl_connections{container=\"$container\"}",
       "legendFormat": "Hard limit  SSL endpoints"
      }
     ]
    },
    {
     "title": "Process - SSL key rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1779 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "haproxy_process_current_frontend_ssl_key_rate{container=\"$container\"}",
       "legendFormat": "SSL keys created on frontends"
      },
      {
       "expr": "haproxy_process_current_backend_ssl_key_rate{container=\"$container\"}",
       "legendFormat": "SSL keys created on backend"
      }
     ]
    },
    {
     "title": "Process - SSL cache",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1789 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_process_ssl_cache_lookups_total{container=\"$container\"}[$__rate_interval]\n)",
       "legendFormat": "Lookups"
      },
      {
       "expr": "rate(\n  haproxy_process_ssl_cache_misses_total{container=\"$container\"}[$__rate_interval]\n)",
       "legendFormat": "Miss"
      },
      {
       "expr": "rate(\n  haproxy_process_ssl_connections_total{container=\"$container\"}[$__rate_interval]\n)",
       "legendFormat": "SSL Connections"
      }
     ]
    },
    {
     "title": "Process - SSL reuse ratio",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1789 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "haproxy_process_frontend_ssl_reuse{container=\"$container\"}",
       "legendFormat": "Frontend SSL connections which did not require a new key"
      }
     ]
    },
    {
     "title": "Process - Zlib (HTTP compression) memory limits",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1789 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_current_zlib_memory{container=\"$container\"}",
       "legendFormat": "Amount of memory currently used by HTTP compression"
      },
      {
       "expr": "haproxy_process_max_zlib_memory{container=\"$container\"}",
       "legendFormat": "Limit memory used by HTTP compression,  above is auto disabled (in bytes, see global.maxzlibmem)"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - Failed DNS resolutions",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1844 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_process_failed_resolutions{container=\"$container\"}[$__rate_interval]\n)",
       "legendFormat": "Total number of failed DNS resolutions in current worker process since started"
      }
     ]
    },
    {
     "title": "Process - Pipes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1844 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_max_pipes{container=\"$container\"}",
       "legendFormat": "Hard limit on the number of pipes for splicing, 0=unlimited"
      },
      {
       "expr": "rate(\n  haproxy_process_pipes_used_total{container=\"$container\"}[$__rate_interval]\n)",
       "legendFormat": "Used pipes"
      },
      {
       "expr": "rate(\n  haproxy_process_pipes_free_total{container=\"$container\"}[$__rate_interval]\n)",
       "legendFormat": "Free pipes"
      }
     ]
    },
    {
     "title": "Process - Listeners",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1844 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_listeners{container=\"$container\"}",
       "legendFormat": "Current number of active listeners"
      }
     ]
    },
    {
     "title": "Process - Memory",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1855 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "haproxy_process_max_memory_bytes{container=\"$container\"}",
       "legendFormat": "Memory limit; 0=unset"
      },
      {
       "expr": "haproxy_process_pool_allocated_bytes{container=\"$container\"}",
       "legendFormat": "Memory allocated in pools"
      },
      {
       "expr": "haproxy_process_pool_used_bytes{container=\"$container\"}",
       "legendFormat": "Memory used in pools"
      }
     ]
    },
    {
     "title": "Process - Pool allocations",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1855 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_process_pool_failures_total{container=\"$container\"}[$__rate_interval]\n)",
       "legendFormat": "Failed pool allocations"
      }
     ]
    },
    {
     "title": "Process - Jobs",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1855 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_jobs{container=\"$container\"}",
       "legendFormat": "Current number of active jobs (listeners, sessions, open devices)"
      },
      {
       "expr": "haproxy_process_unstoppable_jobs{container=\"$container\"}",
       "legendFormat": "Current number of active jobs that can't be stopped during a soft stop"
      }
     ]
    },
    {
     "title": "Process - Configured Threads / Processes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1866 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_nbthread{container=\"$container\"}",
       "legendFormat": "Threads"
      },
      {
       "expr": "haproxy_process_nbproc{container=\"$container\"}",
       "legendFormat": "Processes"
      }
     ]
    },
    {
     "title": "Process - Logs",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1866 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(\n  haproxy_process_dropped_logs_total{container=\"$container\"}[$__rate_interval]\n)",
       "legendFormat": "Total number of dropped logs"
      },
      {
       "expr": "rate(\n  haproxy_process_recv_logs_total{container=\"$container\"}[$__rate_interval]\n)",
       "legendFormat": "Total number of log messages received by log-forwarding listeners"
      }
     ]
    },
    {
     "title": "Process - Peers",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1866 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_active_peers{container=\"$container\"}",
       "legendFormat": "Active peers"
      },
      {
       "expr": "haproxy_process_connected_peers{container=\"$container\"}",
       "legendFormat": "Connected peers"
      }
     ]
    },
    {
     "title": "Process - Tasks / Runqueue",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1877 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_current_tasks{container=\"$container\"}",
       "legendFormat": "Total number of tasks in the current worker process (active + sleeping)"
      },
      {
       "expr": "haproxy_process_current_run_queue{container=\"$container\"}",
       "legendFormat": "Total number of active tasks+tasklets in the current worker process"
      }
     ]
    },
    {
     "title": "Process - Idle / Stopping",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1877 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "haproxy_process_idle_time_percent{container=\"$container\"}",
       "legendFormat": "Idle to total ratio over last sample (percent)"
      },
      {
       "expr": "haproxy_process_stopping{container=\"$container\"}",
       "legendFormat": "Non zero means stopping in progress"
      }
     ]
    },
    {
     "title": "Process - Uptime",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1877 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_process_uptime_seconds{container=\"$container\"}",
       "legendFormat": "How long ago this worker process was started"
      }
     ]
    }
   ]
  }
 ]
}