{
 "title": "Linux system dashboard",
 "description": "System dashboard - Telegraf metrics",
 "tags": [
  "linux",
  "overview",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "inter", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values({host=~\".*\"}, host)"
    }
   },
   { "name": "mountpoint", "label": "Mountpoint", "query": { "query": "label_values(disk_free,path)" } },
   {
    "name": "disk",
    "label": "Disk",
    "query": {
     "query": "label_values(diskio_io_time,name)"
    }
   },
   {
    "name": "netif",
    "label": "Network interface",
    "query": {
     "query": "label_values(net_bytes_recv,interface)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Время работы сервера от момента старта. Позволяет понять, как давно сервер перезагружался последний раз",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime{host=\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ __name__ }}",
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "LA medium",
   "type": "stat",
   "description": "Load Average за 5 минут. Показывает среднюю нагрузку на CPU со стороны сервисов. Если превышает число ядер в CPU, то это значит, что сервисам не хватает ресурсов CPU",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_load5{host=\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ __name__ }}",
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Zombies",
   "type": "stat",
   "description": "Число zombie процессов, которые завершили работу, но не удалены из дерева процессов. Должно быть равно 0. Большое количество может тормозить систему",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "processes_zombies{host=\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ __name__ }}",
     "measurement": "processes",
     "select": [
      [
       { "params": [ "zombies" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "description": "Число процессов в системе. Не должно превышать /proc/sys/kernel/pid_max, иначе система не сможет создавать новые процессы",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "processes_total{host=\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ __name__ }}",
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "Число потоков в системе. Не должно превышать /proc/sys/kernel/threads-max, иначе система не сможет создавать новые потоки",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "processes_total_threads{host=\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ __name__ }}",
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total_threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "description": "Нагрузка на все ядра CPU, выраженная в процентах.",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_idle{host=\"$host\", cpu=\"cpu-total\"} * -1 +100",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ __name__ }}",
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "stat",
   "description": "Процент использования оперативной памяти. 90% - критическая цифра, при которой нужно срочно наращивать оперативную память сервера",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_used_percent{host=\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ __name__ }}",
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "stat",
   "description": "Процент использования памяти подкачки (SWAP). В идеале должен стремиться к нулю, т.к. SWAP медленный по сравнению с RAM. Использование SWAP указывает на недостаток RAM",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "swap_used_percent{host=\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ __name__ }}",
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "RootFS used",
   "type": "stat",
   "description": "Процент использования файловой системы диска от корня. 90% - критическая цифра, при которой нужно срочно наращивать дисковую память сервера",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_used_percent{host=\"$host\", path=\"/\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ __name__ }}",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "stat",
   "description": "Процентное соотношение времени процессора, потраченное на ожидание ввода/вывода. При 20% и выше могут наблюдаться проблемы работоспособности системы. Необходим анализ скорости чтения/записи данных на диск",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_iowait{host=\"$host\", cpu=\"cpu-total\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ __name__ }}",
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Детализированный процент использования CPU различными типами служб.\n\n%user: Процент использования ЦП, возникший при выполнении на уровне пользователя (приложения).\n\n%system: Процент использования ЦП, возникший при выполнении на уровне системы (ядра).\n\n%softirq: Процент использования ЦП, возникший при обслуживании запросов прерываний ядром.\n\n%iowait: Процент времени, в течение которого ЦП или ЦП простаивали, в течение которого система имела невыполненный запрос на дисковый ввод-вывод.\n\n%guest: Процент времени, затраченного виртуальным CPU.\n\n%nice: Процент времени, затраченного на выполнение задач с приоритетом ниже нормального",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "expr": "cpu_usage_user{host=\"$host\", cpu=\"cpu-total\"}",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "legendFormat": "{{ __name__ }}",
     "measurement": "cpu_percentageBusy",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "cpu_usage_system{host=\"$host\", cpu=\"cpu-total\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "cpu_usage_softirq{host=\"$host\", cpu=\"cpu-total\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "cpu_usage_steal{host=\"$host\", cpu=\"cpu-total\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "cpu_usage_nice{host=\"$host\", cpu=\"cpu-total\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "cpu_usage_irq{host=\"$host\", cpu=\"cpu-total\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "cpu_usage_iowait{host=\"$host\", cpu=\"cpu-total\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "cpu_usage_guest{host=\"$host\", cpu=\"cpu-total\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "cpu_usage_guest_nice{host=\"$host\", cpu=\"cpu-total\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Load averages",
   "type": "timeseries",
   "description": "Load Average за 5(short), 10(medium) и 15(long) минут. Показывает среднюю нагрузку на CPU со стороны сервисов за период времени",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "expr": "system_load1{host=\"$host\"}",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "legendFormat": "{{ __name__ }}",
     "measurement": "system_load1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "system_load5{host=\"$host\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "system_load15{host=\"$host\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "description": "Количество выполняемых (running), заблокированных (blocked), спящих (sleeping) и zombie процессов в системе.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "expr": "processes_running{host=\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ __name__ }}",
     "measurement": "processes",
     "select": [
      [
       { "params": [ "blocked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "expr": "processes_blocked{host=\"$host\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "processes_sleeping{host=\"$host\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "processes_stopped{host=\"$host\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "processes_zombies{host=\"$host\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "processes_paging{host=\"$host\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "processes_uncknown{host=\"$host\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Использование оперативной памяти.\n\ntotal - общий размер оперативной памяти\n\nused - память, использованная приложениями\n\ncached - память, закэшированная ОС\n\nfree - свободная неиспользованная память\n\nbuffered - временная буферизированная память\n\nНеобходимо следить по большей части за used памятью. И нужно помнить, что система при отсутствии free памяти может высвобождать часть cached памяти для приложений",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "expr": "mem_available{host=\"$host\"}",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "legendFormat": "{{ __name__ }}",
     "measurement": "mem_inactive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "mem_used{host=\"$host\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "mem_cached{host=\"$host\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "mem_free{host=\"$host\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "mem_buffered{host=\"$host\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Context switches",
     "type": "timeseries",
     "description": "Количество переключений в секунду процессора с одного процесса или потока на другой. Чем больше переключений, тем менее эффективно работает система. Большое количество указывает на высокую конкуренцию между процессами за процессорное время. Количество >10000 в секунду можно считать опасным",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "alias": "$tag_host: $col",
       "expr": "rate(kernel_context_switches{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "kernel_context_switches",
       "measurement": "processes",
       "select": [
        [
         { "params": [ "blocked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Forks",
     "type": "timeseries",
     "description": "Интенсивность создания новых процессов. Значение >100 в секунду можно считать опасным. Может привести к исчерпанию лимита количества процессов в системе, усилить конкуренцию процессов за процессорное время и снизить эффективность работы системы",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "alias": "$tag_host: $col",
       "expr": "rate(kernel_processes_forked{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "kernel_processes_forked",
       "measurement": "kernel",
       "select": [
        [
         { "params": [ "processes_forked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "File descriptors",
     "type": "timeseries",
     "description": "Количество файловых дескрипторов в системе (максимальное и открытое). Каждый процесс, сокет или канал имеет уникальный файловый дескриптор. Количество дескрипторов в системе ограничено. Исчерпание лимита файловых дескрипторов приведет к невозможности создания нового процесса или сокета. Количество >10000 можно считать опасным",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$tag_host: $col",
       "expr": "linux_sysctl_fs_file\\-max{host=\"$host\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "kernel",
       "select": [
        [
         { "params": [ "processes_forked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "$tag_host: $col",
       "expr": "linux_sysctl_fs_file\\-nr{host=\"$host\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "kernel",
       "select": [
        [
         { "params": [ "processes_forked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Conntrack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Netfilter conntrack usage",
     "type": "timeseries",
     "description": "Количество записей о соединениях в таблице conntrack. При переполнении таблицы новые соединения не будут создаваться",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$server: current",
       "expr": "conntrack_ip_conntrack_count{host=\"$host\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "conntrack",
       "select": [
        [
         { "params": [ "ip_conntrack_count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "expr": "conntrack_ip_conntrack_max{host=\"$host\"}",
       "legendFormat": "{{ __name__ }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network stack (TCP)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP connections",
     "type": "timeseries",
     "description": "Количество сетевых соединений в различных состояниях",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$tag_host: $col",
       "expr": "netstat_tcp_close{host=\"$host\"}",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "net_bytes_recv",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "netstat_tcp_close_wait{host=\"$host\"}",
       "legendFormat": "{{ __name__ }}"
      },
      {
       "expr": "netstat_tcp_closing{host=\"$host\"}",
       "legendFormat": "{{ __name__ }}"
      },
      {
       "expr": "netstat_tcp_established{host=\"$host\"}",
       "legendFormat": "{{ __name__ }}"
      },
      {
       "expr": "netstat_tcp_fin_wait1{host=\"$host\"}",
       "legendFormat": "{{ __name__ }}"
      },
      {
       "expr": "netstat_tcp_fin_wait2{host=\"$host\"}",
       "legendFormat": "{{ __name__ }}"
      },
      {
       "expr": "netstat_tcp_last_ack{host=\"$host\"}",
       "legendFormat": "{{ __name__ }}"
      },
      {
       "expr": "netstat_tcp_syn_recv{host=\"$host\"}",
       "legendFormat": "{{ __name__ }}"
      },
      {
       "expr": "netstat_tcp_syn_sent{host=\"$host\"}",
       "legendFormat": "{{ __name__ }}"
      },
      {
       "expr": "netstat_tcp_time_wait{host=\"$host\"}",
       "legendFormat": "{{ __name__ }}"
      }
     ]
    },
    {
     "title": "TCP aborts",
     "type": "timeseries",
     "description": "Термин TCP aborts относится к ситуациям, когда TCP-соединение прерывается или завершается аварийно до того, как оно успешно завершит свою работу. Рост числа TCP aborts указывает на нестабильность работы сети или приложения",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "alias": "on close",
       "expr": "rate(nstat_TcpExtTCPAbortOnClose{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "TcpExtTCPAbortOnClose" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "on data",
       "expr": "rate(nstat_TcpExtTCPAbortOnData{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "TcpExtTCPAbortOnData" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "timeout",
       "expr": "rate(nstat_TcpExtTCPAbortOnTimeout{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "TcpExtTCPAbortOnTimeout" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "failed",
       "expr": "rate(nstat_TcpExtTCPAbortFailed{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "TcpExtTCPAbortFailed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "linger",
       "expr": "rate(nstat_TcpExtTCPAbortOnLinger{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "TcpExtTCPAbortOnLinger" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "memory",
       "expr": "rate(nstat_TcpExtTCPAbortOnMemory{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "TcpExtTCPAbortOnMemory" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "TCP handshake issues",
     "type": "timeseries",
     "description": "Динамика количества открываемых TCP соединений",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "alias": "estabresets",
       "expr": "rate(net_tcp_estabresets{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "net_tcp_estabresets",
       "measurement": "net",
       "select": [
        [
         { "params": [ "tcp_estabresets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "outrsts",
       "expr": "rate(net_tcp_outrsts{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "net_tcp_outrsts",
       "measurement": "net",
       "select": [
        [
         { "params": [ "tcp_estabresets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "activeopens",
       "expr": "rate(net_tcp_activeopens{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "net_tcp_activeopens",
       "measurement": "net",
       "select": [
        [
         { "params": [ "tcp_estabresets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "passiveopens",
       "expr": "rate(net_tcp_passiveopens{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "net_tcp_passiveopens",
       "measurement": "net",
       "select": [
        [
         { "params": [ "tcp_estabresets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "TCP SYN cookies",
     "type": "timeseries",
     "description": "Динамика работы SYN cookie на сервере. Рост числа TcpExtSyncookiesFailed может указавать на попытку атаки на сервер с целью исчерпания числа сетевых соединений",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "failed",
       "expr": "rate(nstat_TcpExtSyncookiesFailed{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "TcpExtSyncookiesFailed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "received",
       "expr": "rate(nstat_TcpExtSyncookiesRecv{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "TcpExtSyncookiesRecv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "sent",
       "expr": "rate(nstat_TcpExtSyncookiesSent{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "TcpExtSyncookiesSent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "ICMP packets",
     "type": "timeseries",
     "description": "Статистика приема и передачи ICMP пакетов на хосте",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "in echos",
       "expr": "rate(nstat_IcmpInEchos{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IcmpInEchos" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out echos",
       "expr": "rate(nstat_IcmpOutEchos{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IcmpOutEchos" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in echo responses",
       "expr": "rate(nstat_IcmpInEchoReps{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IcmpInEchoReps" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out echo responses",
       "expr": "rate(nstat_IcmpOutEchoReps{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IcmpOutEchoReps" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "ICMP errors",
     "type": "timeseries",
     "description": "Статистика ошибок при приеме или отправке ICMP пакетов",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "in errors",
       "expr": "rate(nstat_IcmpInErrors{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IcmpInErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out errors",
       "expr": "rate(nstat_IcmpOutErrors{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IcmpOutErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "checksum errors",
       "expr": "rate(nstat_IcmpInCsumErrors{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IcmpInCsumErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "IPv4 errors",
     "type": "timeseries",
     "description": "Статистика ошибок при отправке или приеме IPv4 пакетов",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "in discards",
       "expr": "rate(nstat_IpInDiscards{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IpInDiscards" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out discards",
       "expr": "rate(nstat_IpOutDiscards{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IpOutDiscards" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in hdr errors",
       "expr": "rate(nstat_IpInHdrErrors{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IpInHdrErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in addr errors",
       "expr": "rate(nstat_IpInAddrErrors{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IpInAddrErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out no routes",
       "expr": "rate(nstat_IpOutNoRoutes{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IpOutNoRoutes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in unknown protocol",
       "expr": "rate(nstat_IpInUnknownProtos{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "IpInUnknownProtos" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "IPv6 errors",
     "type": "timeseries",
     "description": "Статистика ошибок при отправке или приеме IPv6 пакетов",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "in discards",
       "expr": "rate(nstat_Ip6InDiscards{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "Ip6InDiscards" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out discards",
       "expr": "rate(nstat_Ip6OutDiscards{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "Ip6OutDiscards" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in hdr errors",
       "expr": "rate(nstat_Ip6InHdrErrors{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "Ip6InHdrErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in addr errors",
       "expr": "rate(nstat_Ip6InAddrErrors{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "Ip6InAddrErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "out no routes",
       "expr": "rate(nstat_Ip6OutNoRoutes{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "Ip6OutNoRoutes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in unknown protocol",
       "expr": "rate(nstat_Ip6InUnknownProtos{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "Ip6InUnknownProtos" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network stack (UDP)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "UDP datagrams",
     "type": "timeseries",
     "description": "Статистика отправки и приема UDP пакетов",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "alias": "$tag_host: $col",
       "expr": "rate(net_udp_indatagrams{host=\"$host\"}[1m])",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "legendFormat": "net_udp_indatagrams",
       "measurement": "net_bytes_recv",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $col",
       "expr": "rate(net_udp_outdatagrams{host=\"$host\"}[1m])",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "legendFormat": "net_udp_outdatagrams",
       "measurement": "net_bytes_recv",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "UDP buffer errors",
     "type": "timeseries",
     "description": "Статистика ошибок принятия или отправки UDP пакетов в результате невозможности выделения памяти в буфере.  Ошибки возникают, когда буфер переполнен, когда сеть перегружена или когда приложение генерирует больше UDP пакетов, чем сеть может пропустить",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "alias": "Send buffer errors",
       "expr": "rate(nstat_UdpSndbufErrors{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "nstat_UdpSndbufErrors",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "UdpSndbufErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "Receive buffer errors",
       "expr": "rate(nstat_UdpRcvbufErrors{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "nstat_UdpRcvbufErrors",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "UdpRcvbufErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "UDP errors",
     "type": "timeseries",
     "description": "Статистика ошибок приема UDP пакетов",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "alias": "checksum errors",
       "expr": "rate(nstat_UdpInCsumErrors{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "nstat_UdpInCsumErrors",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "UdpInCsumErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in errors",
       "expr": "rate(nstat_UdpInErrors{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "nstat_UdpInErrors",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "UdpInErrors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "no ports",
       "expr": "rate(nstat_UdpNoPorts{host=\"$host\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "nstat_UdpNoPorts",
       "measurement": "nstat",
       "select": [
        [
         { "params": [ "UdpNoPorts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network interface stats for $netif",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "repeat": "netif",
   "collapsed": true,
   "panels": [
    {
     "title": "Network Usage",
     "type": "timeseries",
     "description": "Статистика приема и передачи данных (в битах) по сети",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "expr": "rate(net_bytes_recv{host=\"$host\", interface=\"$netif\"}[1m]) * 8",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "legendFormat": "net_bytes_recv",
       "measurement": "net_bytes_recv",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "expr": "rate(net_bytes_sent{host=\"$host\", interface=\"$netif\"}[1m]) * 8",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "legendFormat": "net_bytes_sent",
       "measurement": "net_bytes_recv",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network Packets",
     "type": "timeseries",
     "description": "Статистика приема и передачи сетевых пакетов",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "expr": "rate(net_packets_recv{host=\"$host\", interface=\"$netif\"}[1m])",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "legendFormat": "net_packets_recv",
       "measurement": "net_bytes_recv",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "expr": "rate(net_packets_sent{host=\"$host\", interface=\"$netif\"}[1m])",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "legendFormat": "net_packets_sent",
       "measurement": "net_bytes_recv",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network drops",
     "type": "timeseries",
     "description": "Статистика дропов (отброски) пакетов на приеме или при передаче",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "expr": "rate(net_drop_in{host=\"$host\", interface=\"$netif\"}[1m])",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "legendFormat": "net_drop_in",
       "measurement": "net_bytes_recv",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "expr": "rate(net_drop_out{host=\"$host\", interface=\"$netif\"}[1m])",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "legendFormat": "net_drop_out",
       "measurement": "net_bytes_recv",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network errors",
     "type": "timeseries",
     "description": "Статистика ошибок приема и передачи сетевых пакетов",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "alias": "$tag_host: $tag_interface: $col",
       "expr": "rate(net_err_in{host=\"$host\", interface=\"$netif\"}[1m])",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "legendFormat": "net_err_in",
       "measurement": "net_bytes_recv",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_interface: $col",
       "expr": "rate(net_err_out{host=\"$host\", interface=\"$netif\"}[1m])",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "legendFormat": "net_err_out",
       "measurement": "net_bytes_recv",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Swap I/O bytes",
     "type": "timeseries",
     "description": "Статистика чтения и записи данных в SWAP",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "alias": "$tag_host: $col",
       "expr": "rate(swap_in{host=\"$host\"}[1m])",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "legendFormat": "swap_in",
       "measurement": "swap_in",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "rate(swap_out{host=\"$host\"}[1m])",
       "legendFormat": "swap_out"
      }
     ]
    },
    {
     "title": "Swap usage (bytes)",
     "type": "timeseries",
     "description": "Максимальный размер SWAP и размер данных, записанных в SWAP (в память). Исчерпание SWAP может привести к нарушению работы сисемы. Необходимо контролировать размер SWAP, чтобы он не переполнялся",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "alias": "$tag_host: $col",
       "expr": "swap_total{host=\"$host\"}",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "legendFormat": "swap_total",
       "measurement": "swap_in",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "swap_used{host=\"$host\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk IOPS for /dev/$disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "repeat": "disk",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O requests for /dev/$disk",
     "type": "timeseries",
     "description": "Статистика количества запросов к диску на чтение и запись ",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
     "targets": [
      {
       "alias": "$tag_host: $tag_name: $col",
       "expr": "rate(diskio_reads{host=\"$host\", name=\"$disk\"}[1m])",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "legendFormat": "diskio_reads",
       "measurement": "io_reads",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_name: $col",
       "expr": "rate(diskio_writes{host=\"$host\", name=\"$disk\"}[1m])",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "legendFormat": "diskio_writes",
       "measurement": "io_reads",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk I/O bytes for /dev/$disk",
     "type": "timeseries",
     "description": "Скорость чтения и записи данных на диск",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
     "targets": [
      {
       "alias": "$tag_host: $tag_name: $col",
       "expr": "rate(diskio_read_bytes{host=\"$host\", name=\"$disk\"}[1m])",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "legendFormat": "diskio_read_bytes",
       "measurement": "io_reads",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_name: $col",
       "expr": "rate(diskio_write_bytes{host=\"$host\", name=\"$disk\"}[1m])",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "legendFormat": "diskio_write_bytes",
       "measurement": "io_reads",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk I/O time for /dev/$disk",
     "type": "timeseries",
     "description": "Статистика времени чтения и записи данных на диск",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
     "targets": [
      {
       "alias": "$tag_host: $tag_name: $col",
       "expr": "rate(diskio_read_time{host=\"$host\", name=\"$disk\"}[1m])",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "legendFormat": "diskio_read_time",
       "measurement": "io_reads",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_name: $col",
       "expr": "rate(diskio_write_time{host=\"$host\", name=\"$disk\"}[1m])",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "legendFormat": "diskio_write_time",
       "measurement": "io_reads",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk space usage for $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "repeat": "mountpoint",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk usage for $mountpoint",
     "type": "timeseries",
     "description": "Количество данных, записанных  раздел диска и максимальный размер раздела диска. В случае переполнения размера диска возникнет авария. Необходимо контролировать размер раздела диска и не допускать его переполнения",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "expr": "disk_total{host=\"$host\", path=\"$mountpoint\"}",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "legendFormat": "{{ __name__ }}",
       "measurement": "disk_total",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "disk_used{host=\"$host\", path=\"$mountpoint\"}",
       "legendFormat": "{{ __name__ }}"
      }
     ]
    },
    {
     "title": "Disk inodes for $mountpoint",
     "type": "timeseries",
     "description": "Количество использованных inode и максимальное количество inode. Файловая система может исчерпать доступные inode, даже если есть свободное место на диске. Это происходит, если создается большое количество маленьких файлов. Решение: Увеличить количество inode при создании файловой системы или удалить ненужные файлы.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "expr": "disk_inodes_used{host=\"$host\", path=\"$mountpoint\"}",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "legendFormat": "disk_inodes_used",
       "measurement": "disk_inodes_free",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: mountpoint $tag_path - $col",
       "expr": "disk_inodes_free{host=\"$host\", path=\"$mountpoint\"} + disk_inodes_used{host=\"$host\", path=\"$mountpoint\"}",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "legendFormat": "disk_inodes_free",
       "measurement": "disk_inodes_free",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}