{
 "title": "Docker dashboard",
 "description": "Docker dashboard - Telegraf metrics",
 "tags": [
  "overview",
  "docker",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": { "query": "label_values(host)" } },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values({host=\"$host\"},container_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "All Containers",
   "type": "stat",
   "description": "Общее число контейнеров на хосте",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(docker_n_containers{host=\"$host\"}) by(host)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "description": "Количество запущенных контейнеров",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(docker_n_containers_running{host=\"$host\"}) by(host)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Images",
   "type": "stat",
   "description": "Количество образов (шаблонов) docker контейнеров",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(docker_n_images{host=\"$host\"}) by(host)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "description": "Общее количество CPU ядер, доступных для Docker на хосте. Используется для контроля ресурсов и планирования нагрузки в контейнеризованных средах. Использовать до 80% во избежание критической нагрузки, которая повлечет за собой лаги и отказ сервисов",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(docker_n_cpus{host=\"$host\"}) by(host)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "description": "Общий объем оперативной памяти (RAM), доступной для Docker на хосте.  Используется для контроля ресурсов и предотвращения исчерпания памяти контейнерами. Использовать до 80% во избежание остановки контейнеров и деградации сервисов ",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(docker_memory_total{host=\"$host\"}) by(host)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used File Descriptors",
   "type": "stat",
   "description": "Общее количество используемых файловых дескрипторов (открытых файлов, сокетов, пайпов) всеми контейнерами Docker на хосте. Используется для предотвращения исчерпания лимитов и сбоев. Использовать до 85% от общего лимита во исбежание отказа сервисов",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(docker_n_used_file_descriptors{host=\"$host\"}) by(host)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "bargauge",
   "description": "Cредняя загрузка CPU (в процентах) для контейнеров на хосте в течении 40 секунд. Использовать до 80% от общего количества во избежание замедления работы и/или отказа сервисов",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  avg_over_time(\n    docker_container_cpu_usage_percent{\n      host=\"$host\",container_name=~\"$container\"\n    }[$__rate_interval]\n  )\n) by(container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Cкорость потребления CPU (в условных единицах/секунду) для контейнеров на хосте.",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 3 },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    docker_container_cpu_usage_total{host=\"$host\",container_name=~\"$container\"}[$__rate_interval]\n  )\n) by(container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "bargauge",
   "description": "Средний процент использования оперативной памяти (RAM) контейнерами за 40-секундный интервал, относительно установленного для каждого лимита. Используется для контроля нехватки памяти и выявления утечек. Использовать до 85% от лимита во избежание отказа контейнера ",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  docker_container_mem_usage{host=\"$host\",container_name=~\"$container\"}\n    /\n  docker_container_mem_limit{host=\"$host\",container_name=~\"$container\"}\n)[$__rate_interval]\n  *\n100",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Фактическое потребление оперативной памяти (RAM) контейнерами на хосте в МБ и усреднённое за 40 секунд. Используется для сравнения нагрузки между контейнерами и мониторинга потребления RAM.",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(\n  avg_over_time(\n    docker_container_mem_usage{host=\"$host\",container_name=~\"$container\"}[$__rate_interval]\n  )\n) by(container_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network RX",
   "type": "timeseries",
   "description": "Cкорость входящего сетевого трафика (прием данных) для контейнеров в байтах в секунду, усреднённую за 40 секунд. Используется для контроля нагрузки на сеть, поиска утечек, DDoS-атак и др. Использовать до 85% от максимальной пропускной способности сети во избежание потери пакетов",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    docker_container_net_rx_bytes{host=\"$host\",container_name=~\"$container\"}[$__rate_interval]\n  )\n) by(container_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network TX",
   "type": "timeseries",
   "description": "Скорость исходящего сетевого трафика (передача данных) контейнерами в байтах в секунду, усредненное за 40 секунд). Используется для мониторинга исходящей нагрузки и выявления аномалий (утечка данных с неожиданно высоким трафиком), планирования пропускной способности сети. Использовать до 75% от максимальной пропускной способности во избежание перегрузки сети",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    docker_container_net_tx_bytes{host=\"$host\",container_name=~\"$container\"}[$__rate_interval]\n  )\n) by(container_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BlkIO Read",
   "type": "timeseries",
   "description": "Скорость чтения данных с диска для контейнеров на хосте. Используется для мониторинга нагрузки на диск и выявления потенциальных узких мест в производительности. Предельное значение должно быть до 70% от максимальной пропускной способности диска, чтобы избежать перегрузки дисковой подсистемы.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    docker_container_blkio_io_service_bytes_recursive_read{\n      host=\"$host\",container_name=~\"$container\"\n    }[$__rate_interval]\n  )\n) by(container_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BlkIO Write",
   "type": "timeseries",
   "description": "Скорость записи данных на диск для контейнеров на хосте. Используется для мониторинга нагрузки на диск и выявления потенциальных узких мест в производительности. Предельное значение должно быть до 70% от максимальной пропускной способности диска, чтобы избежать перегрузки дисковой подсистемы.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    docker_container_blkio_io_service_bytes_recursive_write{\n      host=\"$host\",container_name=~\"$container\"\n    }[$__rate_interval]\n  )\n) by(container_name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}