{
 "title": "ECCM Details",
 "tags": [
  "eccm",
  "details"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values({app=\"eccm\"},host)"
    }
   },
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values({application=\"$application\"},container)"
    }
   },
   {
    "name": "prometheus",
    "query": "victoriametrics-metrics-datasource"
   },
   { "name": "precision", "label": "Precision", "query": "15s, 30s, 1m, 2m, 5m" }
  ]
 },
 "panels": [
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "description": "Время работы процесса.",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{host=\"$host\", application=\"$application\", container=\"$container\"}"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "stat",
     "description": "Время запуска процесса.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{host = \"$host\", application=\"$application\", container=\"$container\"} * 1000"
      }
     ]
    },
    {
     "title": "Heap used",
     "type": "stat",
     "description": "Процент использования heap-памяти JVM",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{host = \"$host\", application=\"$application\", area=\"heap\", container=\"$container\"}) * 100 / sum(jvm_memory_max_bytes{application=\"$application\", area=\"heap\", container=\"$container\"})"
      }
     ]
    },
    {
     "title": "Non-Heap used",
     "type": "stat",
     "description": "Процент использования nonheap-памяти JVM",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{host=\"$host\", application=\"$application\", area=\"nonheap\", container=\"$container\"}) * 100 / sum(jvm_memory_max_bytes{application=\"$application\", area=\"nonheap\", container=\"$container\"})"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "stat",
     "description": "Показывает использование CPU системой для выбранного контейнера.",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "system_cpu_usage{host= \"$host\",application=\"$application\", container=\"$container\"}"
      }
     ]
    },
    {
     "title": "LA",
     "type": "stat",
     "description": "Средняя нагрузка на систему за 1 минуту для выбранного контейнера",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "system_load_average_1m{host=\"$host\", application=\"$application\", container=\"$container\"}"
      }
     ]
    },
    {
     "title": "Memory Usage Overall",
     "type": "timeseries",
     "description": "Суммарное потребление памяти JVM по приложению, включая выделенную память, активные потоки  и буферы.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1773 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_committed_bytes{host=\"$host\"}) by (application) +\nsum(jvm_threads_live_threads{host=\"$host\"} * 1024 * 1024) by (application) +\nsum(jvm_buffer_memory_used_bytes{host=\"$host\"}) by (application)",
       "legendFormat": "{{application}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "Сравнение системного  и пользовательского использования CPU. Позволяет оценить распределение нагрузки между системными и прикладными процессами.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1773 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_cpu_usage{host=\"$host\", container=\"$container\", application=\"$application\"}",
       "legendFormat": "System CPU Usage"
      },
      {
       "expr": "process_cpu_usage{host=\"$host\", container=\"$container\", application=\"$application\"}",
       "legendFormat": "Process CPU Usage"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "timeseries",
     "description": "Показывает среднюю загрузку системы за 1 минуту  и количество CPU-ядер. Сравнение этих показателей позволяет оценить нагрузку на систему относительно доступных ресурсов процессора.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1773 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_load_average_1m{host=\"$host\", container=\"$container\", application=\"$application\"}",
       "legendFormat": "Load Average [1m]"
      },
      {
       "expr": "system_cpu_count{host=\"$host\", container=\"$container\", application=\"$application\"}",
       "legendFormat": "CPU Core Size"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP I/O Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate",
     "type": "timeseries",
     "description": "Частота входящих HTTP-запросов.\n\n*  Рост значения указывает на увеличение нагрузки на сервер, что может быть связано с повышенной активностью пользователей или автоматизированными запросами.\n* Резкие скачки или падение могут свидетельствовать о проблемах в работе приложения, перегрузках или сбоях.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision]))",
       "legendFormat": "HTTP"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "timeseries",
     "description": "Показывает два ключевых показателя производительности обработки HTTP-запросов. \n1) HTTP - AVG - среднее время отклика сервера в секунду.\n2) HTTP - MAX - максимальное зарегистрированное время обработки отдельного запроса за текущий момент.\n\n* Средняя длительность отражает общую производительность и загруженность сервера.\n* Максимальная длительность помогает выявлять отдельные \"тяжёлые\" или медленные запросы, которые могут влиять на качество обслуживания.\n* Рост обоих показателей сигнализирует о возможных проблемах с производительностью, задержках в обработке или узких местах.\n* Резкие всплески максимальной длительности требуют анализа конкретных запросов и причин замедления.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{host=\"$host\", application=\"$application\", status!~\"5..\", container=\"$container\"}[$precision])) / sum(rate(http_server_requests_seconds_count{host=\"$host\", application=\"$application\", status!~\"5..\", container=\"$container\"}[$precision]))",
       "legendFormat": "HTTP - AVG"
      },
      {
       "expr": "max(http_server_requests_seconds_max{host=\"$host\", application=\"$application\", status!~\"5..\", container=\"$container\"})",
       "legendFormat": "HTTP - MAX"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "description": "Частота HTTP-ошибок с кодами 5xx.\n* Значение показывает количество ошибок сервера в секунду.\n* Увеличение скорости ошибок свидетельствует о проблемах на стороне сервера, которые могут влиять на доступность и стабильность приложения.\n* Резкие всплески ошибок требуют немедленного внимания и расследования причин сбоев.\n* Низкий или равный нулю показатель означает стабильную работу без критических ошибок.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{host=\"$host\", application=\"$application\", status=~\"5..\", container=\"$container\"}[$precision]))",
       "legendFormat": "HTTP - 5xx"
      }
     ]
    }
   ]
  },
  {
   "title": "RabbitMQ I/O Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processing Rate",
     "type": "timeseries",
     "description": "Суммарная частота обработки сообщений RabbitMQ",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_messages_seconds_count{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision]))",
       "legendFormat": "Messages"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "timeseries",
     "description": "Средняя частота обработки сообщений RabbitMQ",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_messages_seconds_sum{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision])) / sum(rate(rabbitmq_messages_seconds_count{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision]))",
       "legendFormat": "Messages - AVG"
      },
      {
       "expr": "max(rabbitmq_messages_seconds_max{application=\"$application\", container=\"$container\"})",
       "legendFormat": "Messages - MAX"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "description": "Суммарная частота появления не подтверждённых (непринятых) сообщений.\n* Повышенные значения на графике могут указывать на сбои в доставке сообщений, ошибки на стороне потребителей или проблемы с подтверждением сообщений в очередях RabbitMQ.\n* Периодические всплески могут быть нормой при пиковых нагрузках, но устойчиво высокий уровень требует внимания — возможна потеря данных или перегрузка потребителей.\n* Низкие или нулевые значения обычно означают стабильную обработку и корректную работу механизмов подтверждения.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_not_acknowledged_published_total{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision]))",
       "legendFormat": "Acknowlege failure"
      },
      {
       "expr": "sum(rate(rabbitmq_failed_to_publish_total{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision]))",
       "legendFormat": "Publish failure"
      },
      {
       "expr": "sum(rate(rabbitmq_rejected_total{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision]))",
       "legendFormat": "Rejected"
      }
     ]
    },
    {
     "title": "I/O Rate",
     "type": "timeseries",
     "description": "Разница между частотой публикации и частотой потребления сообщений в RabbitMQ.\n\n* Если значения графика стремятся к нулю, это означает, что система сбалансирована: сообщения потребляются с той же скоростью, с которой публикуются.\n* Положительные значения указывают на избыток входящего трафика — сообщения накапливаются, возможно, из-за медленной работы потребителей.\n* Отрицательные значения (если потребление быстрее публикации) — редкая, но потенциально нормальная ситуация, например, при опустошении очереди.\n* Длительное отклонение от нуля может свидетельствовать о дисбалансе в системе и потребовать оперативного вмешательства.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 234 },
     "targets": [
      {
       "expr": "rate(rabbitmq_published_total{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision])",
       "legendFormat": "Published"
      },
      {
       "expr": "-rate(rabbitmq_consumed_total{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision])",
       "legendFormat": "Consumed"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "description": "Количество активных соединений и каналов RabbitMQ. Позволяет мониторить текущую нагрузку и состояние коммуникаций в брокере сообщений.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 234 },
     "targets": [
      {
       "expr": "rabbitmq_connections{host=\"$host\", application=\"$application\", container=\"$container\"}",
       "legendFormat": "Connections"
      },
      {
       "expr": "rabbitmq_channels{host=\"$host\", application=\"$application\", container=\"$container\"}",
       "legendFormat": "Channels"
      }
     ]
    }
   ]
  },
  {
   "title": "Rpc Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate исходящих RPC-запросов",
     "type": "timeseries",
     "description": "Показывает частоту исходящих RPC-запросов от клиентов RabbitMQ.\n\n* Высокое значение на графике означает, что приложение активно отправляет много RPC-запросов — это может свидетельствовать о высокой нагрузке или пиковом использовании сервиса.\n* Низкое или близкое к нулю значение говорит о низкой активности или отсутствии RPC-вызовов в выбранный период.\n* Резкие всплески могут указывать на аномалии или проблемы, требующие дополнительного анализа (например, неожиданный рост нагрузки).\n* Стабильный уровень запросов указывает на нормальную работу системы.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(rabbitmq_client_rpc_time_seconds_count{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Время выполнения RPC-запросов (клиент)",
     "type": "timeseries",
     "description": "Показывает среднее время выполнения исходящих RPC-запросов на стороне клиента RabbitMQ.\n\n* Рост значения указывает на увеличение времени отклика RPC-запросов, что может свидетельствовать о замедлении работы сервиса или нагрузке.\n* Стабильное и низкое значение — признак нормальной и быстрой обработки запросов.\n* Резкие скачки времени выполнения требуют дополнительного анализа и могут сигнализировать о проблемах в инфраструктуре или приложении.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(rabbitmq_client_rpc_time_seconds_sum{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision]) / \nrate(rabbitmq_client_rpc_time_seconds_count{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Rate входящих RPC-запросов",
     "type": "timeseries",
     "description": "Частота входящих RPC-запросов, обрабатываемых сервисом RabbitMQ.\n\n* Высокая частота обработки указывает на интенсивную нагрузку на сервис и активное поступление RPC-запросов.\n* Низкая частота или нулевые значения означают низкую активность или отсутствие входящих запросов в выбранный интервал.\n* Резкие изменения могут свидетельствовать о всплесках нагрузки или аномалиях в работе сервиса.\n* Стабильный уровень запросов говорит о нормальной и предсказуемой работе сервиса.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 236 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(rabbitmq_server_messages_handling_time_seconds_count{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Время выполнения RPC-запросов (сервер)",
     "type": "timeseries",
     "description": "Показывает среднее время обработки входящих RPC-запросов на стороне сервиса RabbitMQ.\n\n* Увеличение среднего времени обработки может указывать на замедление сервиса, перегрузку или проблемы в инфраструктуре.\n* Низкие и стабильные значения свидетельствуют о нормальной работе и быстрой обработке запросов.\n* Резкие изменения времени обработки требуют дополнительного анализа для выявления возможных узких мест или сбоев.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 236 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(rabbitmq_server_messages_handling_time_seconds_sum{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision])/rate(rabbitmq_server_messages_handling_time_seconds_count{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Rate отправки RPC-ответов",
     "type": "timeseries",
     "description": "Частота отправки RPC-ответов сервисом RabbitMQ.\n\n* Высокое значение указывает на активную обработку и отправку ответов клиентам, что соответствует высокой нагрузке или интенсивному взаимодействию.\n* Низкие значения могут означать уменьшение активности или потенциальные проблемы с отправкой ответов.\n* Резкие изменения скорости отправки могут свидетельствовать о сбоях, задержках или всплесках нагрузки.\n* Стабильная частота — признак нормального функционирования системы.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 244 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(rabbitmq_server_messages_response_time_seconds_count{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Время отправки RPC-ответов",
     "type": "timeseries",
     "description": "Показывает среднее время отправки RPC-ответов сервисом RabbitMQ.\n\n* Повышение среднего времени отправки ответов может свидетельствовать о задержках в обработке или проблемах с сетью.\n* Низкие и стабильные значения указывают на нормальное и быстрое отправление ответов.\n* Внезапные скачки времени отправки требуют дополнительного анализа для выявления причин замедлений или сбоев.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 244 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(rabbitmq_server_messages_response_time_seconds_sum{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision]) /\nrate(rabbitmq_server_messages_response_time_seconds_count{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections Size",
     "type": "stat",
     "description": "Показывает текущее общее количество соединений в пуле HikariCP.\n\n- Значение отражает фактический размер пула соединений в текущий момент времени.\n- Если метрика часто достигает или близка к максимальному размеру пула (maximumPoolSize), это может указывать на:\n  - постоянную высокую нагрузку;\n  - необходимость увеличения размера пула;\n  - адержки в выполнении запросов к БД.\n- Стабильно низкие значения могут указывать на избыточно большой пул (неэффективное использование ресурсов).",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections{host=\"$host\", container=\"$container\", application=\"$application\"}"
      }
     ]
    },
    {
     "title": "Hikari Connections",
     "type": "timeseries",
     "description": "Показывает текущее состояние пула соединений HikariCP.\nВключает три метрики:\n\nActive — количество активных (используемых) соединений,\nIdle — количество простаивающих (свободных) соединений,\nPending — количество ожидающих получения соединения потоков.\n\n* Высокое значение Active при низком Idle может указывать на высокую нагрузку на пул или его недостаточную ёмкость.\n* Увеличение Pending сигнализирует о нехватке доступных соединений — возможен риск деградации производительности приложения.\n* Слишком большое значение Idle при низком Active может означать избыточный размер пула и неэффективное использование ресурсов.",
     "gridPos": { "h": 6, "w": 8, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hikaricp_connections_active{host=\"$host\", container=\"$container\", application=\"$application\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "hikaricp_connections_idle{host=\"$host\", container=\"$container\", application=\"$application\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "hikaricp_connections_pending{host=\"$host\", container=\"$container\", application=\"$application\"}",
       "legendFormat": "Pending"
      }
     ]
    },
    {
     "title": "Hikari Connection Acquire Duration",
     "type": "timeseries",
     "description": "Среднее время получения подключения из пула HikariCP\n\n* Низкие значения (~< 0.01 сек) — соединения выдаются быстро, пул работает стабильно.\n* Повышение значения может свидетельствовать о нехватке свободных соединений или блокировках при получении — возможный индикатор перегрузки пула.\n* Резкие пики могут указывать на кратковременные проблемы с базой данных или ошибочную конфигурацию пула (например, слишком маленький max pool size).",
     "gridPos": { "h": 6, "w": 8, "x": 14, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(hikaricp_connections_acquire_seconds_sum{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision]))/sum(rate(hikaricp_connections_acquire_seconds_count{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision]))",
       "legendFormat": "Acquire duration"
      }
     ]
    },
    {
     "title": "Connection Timeout Count",
     "type": "stat",
     "description": "Общее количество таймаутов при попытке получить соединение из пула HikariCP.\n\n- Отсутствие роста метрики — нормальное поведение, все соединения выдаются вовремя.\n- Рост значения означает, что соединения недоступны в течение времени, заданного в конфигурации, и попытка подключения завершилась ошибкой.\n- Может указывать на:\n  - недостаточный размер пула;\n  - утечки соединений (не возвращаются в пул);\n  - резкое увеличение нагрузки;\n  - долгие SQL-запросы, удерживающие соединения.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 143 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections_timeout_total{host=\"$host\", container=\"$container\", application=\"$application\"}"
      }
     ]
    },
    {
     "title": "Hikari Connection Usage Duration",
     "type": "timeseries",
     "description": "Среднее время использования подключения из пула HikariCP.\n\n* Низкие значения (~0.01–0.1 сек) обычно свидетельствуют о быстром выполнении запросов к БД.\n* Рост значений может указывать на замедление SQL-запросов, блокировки в базе данных, или неэффективные транзакции.\n* Постоянно высокое значение может сигнализировать о необходимости оптимизации бизнес-логики или настройки БД.",
     "gridPos": { "h": 6, "w": 8, "x": 6, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(hikaricp_connections_usage_seconds_sum{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision]))/sum(rate(hikaricp_connections_usage_seconds_count{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision]))",
       "legendFormat": "Usage duration"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage Full",
     "type": "timeseries",
     "description": "Использование памяти JVM: выделенная, потоковая и буферная.",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_committed_bytes{host=\"$host\", application=\"$application\", container=\"$container\"}",
       "legendFormat": "{{area}}:{{id}}"
      },
      {
       "expr": "jvm_threads_live_threads{host=\"$host\", application=\"$application\", container=\"$container\"} * 1024 * 1024",
       "legendFormat": "thread stacks"
      },
      {
       "expr": "jvm_buffer_memory_used_bytes{host=\"$host\", application=\"$application\", container=\"$container\"}",
       "legendFormat": "buffers: {{id}}"
      }
     ]
    },
    {
     "title": "JVM Heap",
     "type": "timeseries",
     "description": "Показывает использование heap-памяти JVM: фактически используемую, зарезервированную и максимально доступную.\n\n* used - показывает текущее использование heap. Постоянный рост между сборками мусора может свидетельствовать о возможных утечках памяти.\n* commited - может увеличиваться или уменьшаться в зависимости от политики управления памятью JVM (например, G1GC может динамически изменять объём выделенной памяти).\n* max - обычно фиксированное значение. Если used приближается к max, это может указывать на нехватку памяти и потенциальный OutOfMemoryError.",
     "gridPos": { "h": 10, "w": 5, "x": 9, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{host=\"$host\", application=\"$application\", area=\"heap\", container=\"$container\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{host=\"$host\", application=\"$application\", area=\"heap\", container=\"$container\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{host=\"$host\", application=\"$application\", area=\"heap\", container=\"$container\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "timeseries",
     "description": "Показывает использование nonheap-памяти JVM: фактически используемую, зарезервированную и максимально доступную.\n\n* used -объём фактически используемой non-heap памяти, включает метаинформацию классов, кэш, JIT-компиляцию и другие внутренние структуры JVM. Рост может указывать на увеличение количества загружаемых классов или активную JIT-компиляцию.\n* committed - объём non-heap памяти, зарезервированной JVM у операционной системы. Может увеличиваться по мере роста потребностей JVM, но не превышает max.\n* max -  максимально доступный объём non-heap памяти.\n",
     "gridPos": { "h": 10, "w": 5, "x": 14, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{host=\"$host\", application=\"$application\", area=\"nonheap\", container=\"$container\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{host=\"$host\", application=\"$application\", area=\"nonheap\", container=\"$container\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{host=\"$host\", application=\"$application\", area=\"nonheap\", container=\"$container\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Total",
     "type": "timeseries",
     "description": "Показывает суммарное использование памяти JVM(включая heap и non-heap области): фактически используемую, выделенную и максимально доступную.\n\n* used -  общее текущее использование памяти JVM. Включает как heap-, так и non-heap-память. Растущая кривая может указывать на общую нагрузку, утечки или неэффективную работу GC.\n* committed - объём памяти, который JVM зарезервировала у ОС. Может колебаться в зависимости от поведения GC и политики управления памятью. Может быть больше, чем used, но меньше или равно max.\n* max - общий максимально доступный объём памяти, который JVM может использовать. Если JVM не имеет ограничений по какой-либо области памяти, значение может быть null или 0. Приближение used к max сигнализирует о потенциальной нехватке памяти.",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{host=\"$host\", application=\"$application\", container=\"$container\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{host=\"$host\", application=\"$application\", container=\"$container\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{host=\"$host\", application=\"$application\", container=\"$container\"})",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Eden Space",
     "type": "timeseries",
     "description": "Показывает использование памяти в области Eden Space(heap) JVM. Отображаются текущий объём используемой памяти, выделенной и максимальной доступной памяти.\n\n* Если значение Used близко к Committed, значит Eden Space заполнена, что может приводить к частым сборкам мусора (GC), особенно minor GC.\n* Резкие скачки или стабильное высокое использование Used без освобождения могут сигнализировать о проблемах с утечками памяти или неэффективным управлением объектами.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{host=\"$host\", application=\"$application\", container=\"$container\", id=~\".*Eden Space\", area=\"heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{host=\"$host\", application=\"$application\", container=\"$container\", id=~\".*Eden Space\", area=\"heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{host=\"$host\", application=\"$application\", container=\"$container\", id=~\".*Eden Space\", area=\"heap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Survivor Space",
     "type": "timeseries",
     "description": "Показывает использование памяти в области Survivor Space(heap) JVM. Отображаются текущий объём используемой памяти, выделенной и максимальной доступной памяти.\n\n* Если значение Used близко к Committed, это значит, что Survivor Space заполнена, и объекты либо будут перемещены в Old Gen, либо удалены при следующем цикле сборки мусора.\n* Частое или постоянное заполнение Survivor Space может привести к повышенной частоте minor GC и/или продвижению большого числа объектов в Old Gen, что может негативно сказаться на производительности.\n* Низкое использование Survivor Space при высоком использовании Eden Space обычно указывает на быстрое продвижение объектов в Survivor или их быструю утилизацию.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{host=\"$host\", application=\"$application\", container=\"$container\", id=~\".*Survivor Space\", area=\"heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{host=\"$host\", application=\"$application\", container=\"$container\", id=~\".*Survivor Space\", area=\"heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{host=\"$host\", application=\"$application\", container=\"$container\", id=~\".*Survivor Space\", area=\"heap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Old Gen",
     "type": "timeseries",
     "description": "Показывает использование памяти в области Old Generation(heap) JVM. Отображаются текущий объём используемой памяти, выделенной и максимальной доступной памяти.\n\n* Постоянное или растущее высокое значение Used, приближающееся к Committed и Max, может свидетельствовать о накоплении долгоживущих объектов и риске нехватки памяти.\n* Если Used стабильно близко к Committed, это может привести к частым полным сборкам мусора (Full GC), которые обычно более дорогие по времени.\n* Рост Used без последующего снижения после Full GC может указывать на утечки памяти или проблемы с управлением объектами.\n* Наличие запаса между Committed и Max означает, что JVM может расширить область Old Gen при необходимости.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{host=\"$host\", application=\"$application\", container=\"$container\", id=~\".*Old Gen\", area=\"heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{host=\"$host\", application=\"$application\", container=\"$container\", id=~\".*Old Gen\", area=\"heap\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_max_bytes{host=\"$host\", application=\"$application\", container=\"$container\", id=~\".*Old Gen\", area=\"heap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metaspace",
     "type": "timeseries",
     "description": "Показывает использование памяти в области Metaspace JVM (nonheap). Отображаются текущий объём используемой памяти, выделенной и максимальной доступной памяти.\n\n* Рост Used указывает на загрузку новых классов или увеличение метаданных.\n* Если Used стабильно приближается к Committed, JVM может расширить выделенный объем Metaspace, если это позволяет Max.\n* Резкие скачки или постоянный рост использования могут сигнализировать о проблемах с загрузкой классов или утечках метаданных.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{host=\"$host\", application=\"$application\",container=\"$container\", id=\"Metaspace\", area=\"nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{host=\"$host\", application=\"$application\",container=\"$container\", id=\"Metaspace\", area=\"nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{host=\"$host\", application=\"$application\",container=\"$container\", id=\"Metaspace\", area=\"nonheap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Compressed Class Space",
     "type": "timeseries",
     "description": "Показывает использование памяти в области Compressed Class Space JVM(nonheap). Отображаются текущий объём используемой памяти, выделенной и максимальной доступной памяти.\n\n* Рост значения Used указывает на загрузку новых классов и увеличение метаданных в сжатом формате.\n* Если Used близко к Committed, JVM может выделить дополнительную память до значения Max, если это разрешено настройками.\n* При достижении значений Used близко к Max возможны ошибки OutOfMemoryError, что требует анализа и настройки JVM параметров, например, -XX:CompressedClassSpaceSize.\n*  Постоянное увеличение или резкие скачки могут свидетельствовать о проблемах с загрузкой классов или утечках метаданных.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{host=\"$host\", application=\"$application\",container=\"$container\", id=\"Compressed Class Space\", area=\"nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{host=\"$host\", application=\"$application\",container=\"$container\", id=\"Compressed Class Space\", area=\"nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{host=\"$host\", application=\"$application\",container=\"$container\", id=\"Compressed Class Space\", area=\"nonheap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "CodeHeap 'profiled nmethods'",
     "type": "timeseries",
     "description": "Показывает использование памяти в области CodeHeap 'profiled nmethods' JVM(nonheap). Отображаются текущий объём используемой памяти, выделенной и максимальной доступной памяти.\n\n* Увеличение Used отражает компиляцию и хранение профилированных JIT-методов.\n* Если Used приближается к Committed и Max, это может указывать на необходимость увеличения размера CodeHeap для предотвращения ошибок и потери производительности.\n* Недостаток памяти в этой области может привести к ограничению компиляции и снижению эффективности работы JIT-компилятора.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{host=\"$host\", application=\"$application\",container=\"$container\", id=\"CodeHeap 'profiled nmethods'\", area=\"nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{host=\"$host\", application=\"$application\",container=\"$container\", id=\"CodeHeap 'profiled nmethods'\", area=\"nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{host=\"$host\", application=\"$application\",container=\"$container\", id=\"CodeHeap 'profiled nmethods'\", area=\"nonheap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "CodeHeap 'non-profiled nmethods'",
     "type": "timeseries",
     "description": "Показывает использование памяти в области CodeHeap 'non-profiled nmethods' JVM(nonheap). Отображаются текущий объём используемой памяти, выделенной и максимальной доступной памяти.\n\n* Рост значения Used указывает на увеличение количества скомпилированных JIT-методов без профилирования.\n* При приближении Used к Committed и Max может возникнуть нехватка памяти, что приведет к ограничениям в компиляции и потенциальному снижению производительности JVM.\n* ",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{host=\"$host\", application=\"$application\",container=\"$container\", id=\"CodeHeap 'non-profiled nmethods'\", area=\"nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{host=\"$host\", application=\"$application\",container=\"$container\", id=\"CodeHeap 'non-profiled nmethods'\", area=\"nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{host=\"$host\", application=\"$application\",container=\"$container\", id=\"CodeHeap 'non-profiled nmethods'\", area=\"nonheap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "CodeHeap 'non-nmethods'",
     "type": "timeseries",
     "description": "Показывает использование памяти в области CodeHeap 'non-nmethods' JVM(nonheap). Отображаются текущий объём используемой памяти, выделенной и максимальной доступной памяти.\n\n* Увеличение значения Used указывает на рост объема данных, не связанных с JIT-компилированными методами, например, байткода или вспомогательных структур.\n* Если Used приближается к Committed и Max, это может сигнализировать о необходимости увеличения размера этой области для предотвращения ошибок и ухудшения производительности JVM.\n* ",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{host=\"$host\", application=\"$application\",container=\"$container\", id=\"CodeHeap 'non-nmethods'\", area=\"nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{host=\"$host\", application=\"$application\",container=\"$container\", id=\"CodeHeap 'non-nmethods'\", area=\"nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{host=\"$host\", application=\"$application\",container=\"$container\", id=\"CodeHeap 'non-nmethods'\", area=\"nonheap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "description": "График отображает и сравнивает загрузку CPU на уровне системы и конкретного процесса:\n\nsystem — общая загрузка CPU, включая все процессы\n\nprocess — текущая загрузка CPU отслеживаемым процессом\n\nprocess-1h — среднее значение загрузки CPU этим процессом за последний час\n\n* Высокое значение system может указывать на общую нагрузку на сервер.\n* Если process близко к системному уровню, значит приложение потребляет значительную часть CPU.\n* process-1h помогает выявить тенденции в использовании CPU — стабильность или пики нагрузки.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "system_cpu_usage{host=\"$host\", application=\"$application\", container=\"$container\"}",
       "legendFormat": "system"
      },
      {
       "expr": "process_cpu_usage{host=\"$host\", application=\"$application\", container=\"$container\"}",
       "legendFormat": "process"
      },
      {
       "expr": "avg_over_time(process_cpu_usage{host=\"$host\", application=\"$application\", container=\"$container\"}[1h])",
       "legendFormat": "process-1h"
      }
     ]
    },
    {
     "title": "Load",
     "type": "timeseries",
     "description": "Показывает среднюю системную нагрузку за 1 минуту и общее количество CPU-ядер. Помогает сопоставить текущую нагрузку с доступными вычислительными ресурсами.\n\n* Значение system_1m показывает, насколько загружена система: нагрузка выше количества ядер указывает на возможное CPU-узкое место.\n* Отношение нагрузки к количеству ядер помогает понять степень загрузки и определить, перегружена ли система.\n* Высокая нагрузка при небольшом количестве CPU может приводить к снижению производительности и задержкам в обработке задач.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
     "targets": [
      {
       "expr": "system_load_average_1m{host=\"$host\", application=\"$application\", container=\"$container\"}",
       "legendFormat": "system-1m"
      },
      {
       "expr": "system_cpu_count{host=\"$host\", application=\"$application\", container=\"$container\"}",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "description": "Позволяет комплексно оценивать состояние многопоточности как на уровне JVM, так и на уровне процесса, что помогает быстро обнаруживать аномалии, утечки потоков или перегрузки, влияющие на производительность и стабильность приложений.\n\nJVM Live Threads (Активные потоки JVM):\nПоказывает текущее количество живых потоков в JVM. Показывает все запущенные потоки в JVM в реальном времени. Эта метрика помогает понять, сколько потоков активно обрабатывают задачи.\n\nJVM Daemon Threads (Демонические потоки JVM):\nОтображает количество демонических потоков JVM. Демонические потоки — это фоновые потоки JVM, которые не препятствуют завершению работы JVM, поэтому их количество важно для анализа поведения приложения.\n\nJVM Peak Threads (Пиковое число потоков JVM):\nПредставляет максимальное зафиксированное количество потоков JVM за выбранный период. Помогает выявлять пиковые нагрузки и возможные точки перегрузки по числу потоков.\n\nProcess Threads (Потоки процесса):\nПоказывает общее число потоков, используемых процессом приложения внутри контейнера. Это важно для оценки общей нагрузки на процесс и ресурсов ОС.\n",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "jvm_threads_live{host=\"$host\", application=\"$application\", container=\"$container\"} or jvm_threads_live_threads{host=\"$host\", application=\"$application\", container=\"$container\"}",
       "legendFormat": "live"
      },
      {
       "expr": "jvm_threads_daemon{host=\"$host\", application=\"$application\", container=\"$container\"} or jvm_threads_daemon_threads{host=\"$host\", application=\"$application\", container=\"$container\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "jvm_threads_peak{host=\"$host\", application=\"$application\", container=\"$container\"} or jvm_threads_peak_threads{host=\"$host\", application=\"$application\", container=\"$container\"}",
       "legendFormat": "peak"
      },
      {
       "expr": "process_threads{application=\"$application\", container=\"$container\"}",
       "legendFormat": "process"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "timeseries",
     "description": "График отображает распределение потоков JVM по состояниям. \n\n* Мониторинг состояний потоков позволяет выявлять узкие места и потенциальные проблемы с многопоточностью.\n* Повышенное количество потоков в состоянии BLOCKED или WAITING может указывать на проблемы с блокировками или задержками.\n* Состояния RUNNABLE показывают активные потоки, использующие процессорное время.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
     "targets": [
      {
       "expr": "jvm_threads_states_threads{host=\"$host\", application=\"$application\", container=\"$container\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Log Events (1m)",
     "type": "timeseries",
     "description": "Показывает количество событий логирования, зарегистрированных в системе.\n\n* Рост количества лог-событий может свидетельствовать о повышенной активности приложения или возникновении ошибок.\n* Резкие пики могут указывать на аномалии, сбои или важные события, требующие внимания.\n* Стабильное количество логов помогает контролировать нормальное состояние приложения.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "increase(logback_events_total{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision])",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "timeseries",
     "description": "График показывает текущее и максимальное количество открытых файловых дескрипторов и файлов.\n\n* Мониторинг открытых файловых дескрипторов позволяет выявлять утечки ресурсов и контролировать использование системных ресурсов приложением.\n* Рост числа открытых дескрипторов, приближающийся к максимальному значению, может привести к исчерпанию лимитов и сбоям в работе приложения.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "process_open_fds{host=\"$host\", application=\"$application\", container=\"$container\"}",
       "legendFormat": "open"
      },
      {
       "expr": "process_max_fds{host=\"$host\", application=\"$application\", container=\"$container\"}",
       "legendFormat": "max"
      },
      {
       "expr": "process_files_open{host=\"$host\", application=\"$application\", container=\"$container\"} or process_files_open_files{host=\"$host\", application=\"$application\", container=\"$container\"}",
       "legendFormat": "open"
      },
      {
       "expr": "process_files_max{host=\"$host\", application=\"$application\", container=\"$container\"} or process_files_max_files{host=\"$host\", application=\"$application\", container=\"$container\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collections",
     "type": "timeseries",
     "description": "График отображает частоту  возникновения пауз сборщика мусора (GC) в JVM.\n\n* Высокие значения указывают на частые или интенсивные паузы сборщика мусора, что может негативно влиять на производительность приложения из-за задержек в работе JVM.\n* Низкие значения — признак того, что сборка мусора происходит редко или с минимальной нагрузкой.\n* Резкие всплески могут свидетельствовать о пиковых нагрузках, изменениях в поведении приложения или необходимости оптимизации управления памятью.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision])",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "timeseries",
     "description": "Показывает характеристики длительности пауз сборщика мусора (GC) в JVM.\n\n* Средняя длительность показывает, сколько в среднем времени занимает одна пауза сборщика мусора, что помогает понять общую нагрузку на JVM.\n* Максимальная длительность позволяет выявлять редкие, но потенциально критичные паузы, способные вызывать задержки или остановки приложения.\n* Рост этих метрик может указывать на ухудшение производительности или необходимость оптимизации параметров сборщика мусора.\n",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision])/rate(jvm_gc_pause_seconds_count{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision])",
       "legendFormat": "avg {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{host=\"$host\", application=\"$application\", container=\"$container\"}",
       "legendFormat": "max {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "timeseries",
     "description": "Показывает частоту выделения и продвижения памяти в JVM GC.\n\n* Высокая частота выделения памяти указывает на интенсивную работу приложения с созданием новых объектов.\n* Частота продвижения памяти отражает, насколько много объектов переживают сборку мусора молодой генерации и переходят в старую, что влияет на частоту и длительность Full GC.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision])",
       "legendFormat": "allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision])",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classes loaded",
     "type": "timeseries",
     "description": "Показывает количество загруженных классов JVM.\n\n* Увеличение количества загруженных классов может указывать на активную работу приложения с динамической загрузкой классов, например, при использовании плагинов или фреймворков.\n* Резкие скачки или постоянный рост числа классов могут свидетельствовать о проблемах с утечками классов (classloader leaks), что ведет к увеличению потребления памяти.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "jvm_classes_loaded{host=\"$host\", application=\"$application\", container=\"$container\"} or jvm_classes_loaded_classes{host=\"$host\", application=\"$application\", container=\"$container\"}",
       "legendFormat": "loaded"
      }
     ]
    },
    {
     "title": "Class delta (5m)",
     "type": "timeseries",
     "description": "Показывает изменение количества загруженных классов JVM за пятиминутный интервал времени.\n\n* Положительное значение означает, что за указанный интервал времени были загружены новые классы.\n* Отрицательное значение — классы были выгружены (например, при переработке classloader'ов или очистке памяти).\n* Постоянный рост значения без последующего снижения может указывать на утечки classloader'ов и потенциальные проблемы с управлением памятью.\n* Колебания метрики являются нормой для систем, активно использующих динамическую загрузку классов.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "delta(jvm_classes_loaded{host=\"$host\", application=\"$application\", container=\"$container\"}[5m]) or delta(jvm_classes_loaded_classes{host=\"$host\", application=\"$application\", container=\"$container\"}[$precision])",
       "legendFormat": "delta"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Direct Buffers Count",
     "type": "timeseries",
     "description": "Показывает использование и общую ёмкость прямых (direct) буферов JVM.\nused — объем используемой памяти прямых буферов.\ncapacity — общая емкость прямых буферов.\n\n* Высокое значение используемой памяти относительно общей емкости может указывать на активное использование прямых буферов, что характерно для интенсивных операций ввода-вывода или сетевого взаимодействия.\n* Резкое увеличение или постоянное приближение используемой памяти к общей емкости может сигнализировать о потенциальном риске исчерпания ресурсов, что стоит контролировать для предотвращения деградации производительности приложения.\n",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{host=\"$host\", application=\"$application\", id=\"direct\", container=\"$container\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{host=\"$host\", application=\"$application\", id=\"direct\", container=\"$container\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Direct Buffers Memory",
     "type": "timeseries",
     "description": "Показывает количество буферов JVM с идентификатором direct. \n\n* Увеличение количества прямых буферов может свидетельствовать о росте активности операций ввода-вывода или сетевого взаимодействия.\n* Постоянно высокий уровень или устойчивый рост количества буферов может указывать на неэффективное управление памятью (например, утечки буферов), что требует анализа и возможной оптимизации работы с NIO/DirectByteBuffer.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_count{host=\"$host\", application=\"$application\", id=\"direct\", container=\"$container\"} or jvm_buffer_count_buffers{host=\"$host\", application=\"$application\", id=\"direct\", container=\"$container\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Mapped Buffers Count",
     "type": "timeseries",
     "description": "Показывает использование памяти JVM буферов типа \"mapped\" .\nused — текущий объем используемой буферной памяти.\ncapacity — общий объем доступной буферной памяти.\n\n* Высокий уровень использования отображённых буферов обычно связан с интенсивной работой с файлами или другими источниками данных, где применяется память, отображённая в адресное пространство JVM.\n* Если используемая память постоянно приближается к общей ёмкости, это может указывать на необходимость проверки работы с ресурсами, чтобы избежать потенциальных проблем с производительностью или утечками памяти.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{host=\"$host\", application=\"$application\", id=\"mapped\", container=\"$container\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{host=\"$host\", application=\"$application\", id=\"mapped\", container=\"$container\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Mapped Buffers Memory",
     "type": "timeseries",
     "description": "Показывает количество отображённых (mapped) буферов JVM.\n\n* Отображённые буферы используются JVM при работе с файлами и памятью, отображённой в адресное пространство (например, через FileChannel.map).\n* Рост количества отображённых буферов может указывать на увеличение интенсивности работы с файловыми ресурсами.\n* Постоянно высокий или увеличивающийся тренд может свидетельствовать о потенциальных утечках отображённых ресурсов или отсутствии корректного освобождения буферов — такие случаи требуют анализа и возможной оптимизации кода, особенно в частях, работающих с MappedByteBuffer.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_count{host=\"$host\", application=\"$application\", id=\"mapped\", container=\"$container\"} or jvm_buffer_count_buffers{host=\"$host\", application=\"$application\", id=\"mapped\", container=\"$container\"}",
       "legendFormat": "count"
      }
     ]
    }
   ]
  }
 ]
}