{
 "title": "ECCM Overview",
 "tags": [
  "eccm",
  "overview"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Datasource",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values({app=\"eccm\"},host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service health",
   "type": "state-timeline",
   "description": "Показывает доступность сервисов.\nЗначение 1 означает, что сервис доступен; 0 — сервис недоступен или не отвечает.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{host=\"$host\"}",
     "legendFormat": "{{container}} {{instance}}"
    }
   ]
  },
  {
   "title": "Container RAM usage",
   "type": "timeseries",
   "description": "Показывает объём используемой оперативной памяти каждым Docker-контейнером.\nМетрика помогает отслеживать потребление ресурсов контейнерами и выявлять контейнеры с аномально высоким использованием памяти.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "docker_container_mem_usage{container_name=~\"eccm.*|postgres.*|peeper.*\", host=\"$host\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "timeseries",
   "description": "Показывает использование CPU (%) Docker-контейнерами за последние 1 мин.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(docker_container_cpu_usage_total{container_name=~\"eccm.*|postgres.*|peeper.*\"}/1000000000[1m])) by (container_name) * 100",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Container uptime",
   "type": "timeseries",
   "description": "Показывает время работы Docker-контейнеров.\nИспользуется для отслеживания перезапусков контейнеров и стабильности работы сервисов.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "docker_container_status_uptime_ns{host=\"$host\", container_name=~\"eccm.*|postgres.*|peeper.*\"}/1000000000",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}