{
 "title": "WiFi-Cab Dashboard",
 "description": "Access Point Binder monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   { "name": "node", "label": "node", "query": { "query": "label_values(instance)" } },
   {
    "name": "wcab_rate_interval",
    "label": "WiFi cab rate interval",
    "query": "5s,10s,15s,30s,1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=~\"$node\", application=\"$application\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(system_cpu_usage{instance=~\"$node\", application=\"$application\"})"
    }
   ]
  },
  {
   "title": "LA",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(system_load_average_1m{instance=~\"$node\", application=\"$application\"} / system_cpu_count{instance=~\"$node\", application=\"$application\"})"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=~\"$node\", application=\"$application\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{instance=~\"$node\", application=\"$application\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(process_files_open_files{instance=~\"$node\", application=\"$application\"})*100/sum(process_files_max_files{instance=~\"$node\", application=\"$application\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=~\"$node\", application=\"$application\"}*1000"
    }
   ]
  },
  {
   "title": "Keycloak Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Authorization Results",
     "type": "piechart",
     "description": "Counter of authorization results by status",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sso_authorization_results_count_total{instance=~\"$node\", application=\"$application\"}",
       "legendFormat": "Status: {{status}}"
      }
     ]
    },
    {
     "title": "Token Requests Count",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sso_token_requests_count_total{instance=~\"$node\", application=\"$application\"}",
       "legendFormat": "Code: {{status}}"
      }
     ]
    },
    {
     "title": "User Info Requests Count",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sso_user_info_requests_count_total{instance=~\"$node\", application=\"$application\"}",
       "legendFormat": "Code: {{status}}"
      }
     ]
    },
    {
     "title": "Backward Redirects Count",
     "type": "stat",
     "description": "Counter of reverse redirects from the SSO provider towards the Portal Constructor",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sso_redirects_back_count_total{instance=~\"$node\", application=\"$application\"}",
       "legendFormat": "Backward Redirects Count"
      }
     ]
    },
    {
     "title": "Auth Requests Count",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 9, "x": 5, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sso_auth_requests_count_total{instance=~\"$node\", application=\"$application\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Refresh Token Request Processed Count",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sso_refresh_tokens_requests_count_total{instance=~\"$node\", application=\"$application\"}",
       "legendFormat": "Status: {{status}}"
      }
     ]
    },
    {
     "title": "User Info Request Processed Seconds Count Rate [$wcab_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(sso_user_info_request_processed_seconds_count{instance=~\"$node\", application=\"$application\"}[$wcab_rate_interval])",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Backward Redirects Count Rate [$wcab_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "rate(sso_redirects_back_count_total{instance=~\"$node\", application=\"$application\"}[$wcab_rate_interval])",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "User Info Request Processed Seconds Max Rate [$wcab_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(sso_user_info_request_processed_seconds_max{instance=~\"$node\", application=\"$application\"}[$wcab_rate_interval])",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Auth Requests Statuses Counts Rates [$wcab_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "rate(sso_auth_requests_count_total{instance=~\"$node\", application=\"$application\"}[$wcab_rate_interval])",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "User Info Request Processed Seconds Sum Rate [$wcab_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(sso_user_info_request_processed_seconds_sum{instance=~\"$node\", application=\"$application\"}[$wcab_rate_interval])",
       "legendFormat": "Sum"
      }
     ]
    },
    {
     "title": "Authorization Results Statuses Counts Rate [$wcab_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "rate(sso_authorization_results_count_total{instance=~\"$node\", application=\"$application\"}[$wcab_rate_interval])",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Authorization Processed Seconds Counts Rate [$wcab_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(sso_authorization_processed_seconds_count{instance=~\"$node\", application=\"$application\"}[$wcab_rate_interval])",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "User Info Requests Code Count Rates [$wcab_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "expr": "rate(sso_user_info_requests_count_total{instance=~\"$node\", application=\"$application\"}[$wcab_rate_interval])",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Authorization Processed Seconds Max Rates [$wcab_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(sso_authorization_processed_seconds_max{instance=~\"$node\", application=\"$application\"}[$wcab_rate_interval])",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Refresh Token Request Processed Seconds Sum Rate [$wcab_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(sso_refresh_token_request_processed_seconds_sum{instance=~\"$node\", application=\"$application\"}[$wcab_rate_interval])",
       "legendFormat": "Sum"
      }
     ]
    },
    {
     "title": "Authorization Processed Seconds Sum Rate [$wcab_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(sso_authorization_processed_seconds_sum{instance=~\"$node\", application=\"$application\"}[$wcab_rate_interval])",
       "legendFormat": "Sum"
      }
     ]
    },
    {
     "title": "Refresh Token Request Processed Seconds Count Rate [$wcab_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(sso_refresh_token_request_processed_seconds_count{instance=~\"$node\", application=\"$application\"}[$wcab_rate_interval])",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Token Request Processed Seconds Max Rate [$wcab_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(sso_token_request_processed_seconds_max{instance=~\"$node\", application=\"$application\"}[$wcab_rate_interval])",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Refresh Token Request Processed Seconds Max Rate [$wcab_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(sso_refresh_token_request_processed_seconds_max{instance=~\"$node\", application=\"$application\"}[$wcab_rate_interval])",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Token Request Processed Seconds Sum Rate [$wcab_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(sso_token_request_processed_seconds_sum{instance=~\"$node\", application=\"$application\"}[$wcab_rate_interval])",
       "legendFormat": "Sum"
      }
     ]
    },
    {
     "title": "Token Requests Statuses Counts Rates [$wcab_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "targets": [
      {
       "expr": "rate(sso_token_requests_count_total{instance=~\"$node\", application=\"$application\"}[$wcab_rate_interval])",
       "legendFormat": "Code: {{status}}"
      }
     ]
    },
    {
     "title": "Token Request Processed Seconds Count Rate [$wcab_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(sso_token_request_processed_seconds_count{instance=~\"$node\", application=\"$application\"}[$wcab_rate_interval])",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Refresh Token Requests Codes Counts Rates [$wcab_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "targets": [
      {
       "expr": "rate(sso_refresh_tokens_requests_count_total{instance=~\"$node\", application=\"$application\"}[$wcab_rate_interval])",
       "legendFormat": "Code: {{status}}"
      }
     ]
    }
   ]
  }
 ]
}