{
 "title": "Mercury dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "node", "label": "node", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Mercury common metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "UpTime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(system_cpu_usage{instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "LA",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(system_load_average_1m{instance=~\"$node\"} / system_cpu_count{instance=~\"$node\"})",
       "legendFormat": "LA 1m avg"
      }
     ]
    },
    {
     "title": "Heap usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{instance=~\"$node\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{instance=~\"$node\", area=\"heap\"})"
      }
     ]
    },
    {
     "title": "File descriptors usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(process_files_open_files{instance=~\"$node\"})*100/sum(process_files_max_files{instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Mysql connections usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(hikaricp_connections{instance=~\"$node\"})/sum(hikaricp_connections_max{instance=~\"$node\"})*100"
      }
     ]
    },
    {
     "title": "HTTP requests rate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{instance=~\"$node\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{instance=~\"$node\"}*1000"
      }
     ]
    },
    {
     "title": "GRPC calls rate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_calls_seconds_count{instance=~\"$node\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "GRPC calls rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(grpc_server_calls_seconds_count{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{method}} {{result}}"
      }
     ]
    },
    {
     "title": "GRPC calls latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_calls_seconds_sum{instance=~\"$node\"}[$__rate_interval])) / sum(rate(grpc_server_calls_seconds_count{instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "All"
      },
      {
       "expr": "sum(rate(grpc_server_calls_seconds_sum{instance=~\"$node\", method=~\"grpc.UserService.*\"}[$__rate_interval])) / sum(rate(grpc_server_calls_seconds_count{instance=~\"$node\", method=~\"grpc.UserService.*\"}[$__rate_interval]))",
       "legendFormat": "UserService"
      },
      {
       "expr": "sum(rate(grpc_server_calls_seconds_sum{instance=~\"$node\", method=~\"grpc.TariffService.*\"}[$__rate_interval])) / sum(rate(grpc_server_calls_seconds_count{instance=~\"$node\", method=~\"grpc.TariffService.*\"}[$__rate_interval]))",
       "legendFormat": "TariffService"
      },
      {
       "expr": "sum(rate(grpc_server_calls_seconds_sum{instance=~\"$node\",method=~\"grpc.InternalService.*\"}[$__rate_interval])) / sum(rate(grpc_server_calls_seconds_count{instance=~\"$node\",method=~\"grpc.InternalService.*\"}[$__rate_interval]))",
       "legendFormat": "InternalService"
      }
     ]
    }
   ]
  },
  {
   "title": "Hikari pool metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections counters by state (summary all pools)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hikaricp_connections_active{instance=~\"$node\"}",
       "legendFormat": "Active connect"
      },
      {
       "expr": "hikaricp_connections_idle{instance=~\"$node\"}",
       "legendFormat": "Idle connections"
      },
      {
       "expr": "hikaricp_connections_pending{instance=~\"$node\"}",
       "legendFormat": "Pending connections"
      },
      {
       "expr": "hikaricp_connections_max{instance=~\"$node\"}",
       "legendFormat": "Max connections"
      }
     ]
    },
    {
     "title": "Connections acquire time rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_acquire_seconds_sum{instance=~\"$node\"}[$__rate_interval]) / rate(hikaricp_connections_acquire_seconds_count{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "rate"
      }
     ]
    },
    {
     "title": "Connections creation time rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_creation_seconds_sum{instance=~\"$node\"}[$__rate_interval]) / rate(hikaricp_connections_creation_seconds_count{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "rate"
      }
     ]
    },
    {
     "title": "Connections usage time rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_usage_seconds_sum{instance=~\"$node\"}[$__rate_interval]) / rate(hikaricp_connections_usage_seconds_count{ instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Memory Total",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{instance=~\"$node\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{instance=~\"$node\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{instance=~\"$node\"})",
       "legendFormat": "max possible"
      }
     ]
    },
    {
     "title": "JVM heap",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{instance=~\"$node\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{instance=~\"$node\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{instance=~\"$node\", area=\"heap\"})",
       "legendFormat": "max possible"
      }
     ]
    },
    {
     "title": "JVM threads states counters",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_states_threads{instance=~\"$node\"}",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Log4j2 metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log4j2 level events counters",
     "type": "stat",
     "gridPos": { "h": 11, "w": 4, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "log4j2_events_total{instance=~\"$node\"}",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Log4j2 level events rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 20, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(log4j2_events_total{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{level}}"
      }
     ]
    }
   ]
  }
 ]
}