{
 "title": "PCRF",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "node", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process CPU rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=~\"$node\"} * 100",
     "legendFormat": "{{instance}} {{id}}"
    }
   ]
  },
  {
   "title": "Sum JVM mem",
   "type": "piechart",
   "description": "sum without pool splitted",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}} {{id}}"
    }
   ]
  },
  {
   "title": "Rate JVM mem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(jvm_memory_used_bytes{instance=~\"$node\"}[5m])",
     "legendFormat": "{{instance}} {{id}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Cache entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "cache_entries{instance=~\"$node\"}",
     "legendFormat": "{{cache}} ({{instance}})"
    }
   ]
  },
  { "title": "CoA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CoA error ratio ",
   "type": "timeseries",
   "description": "Delta errors to delta processed last 5m",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(CoAMetrics_error_total[$__rate_interval]))/sum(rate(CoAMetrics_processed_total[$__rate_interval]))",
     "legendFormat": "sum delta ration"
    },
    {
     "expr": "rate(CoAMetrics_error_total{instance=~\"$node\"}[$__rate_interval])/rate(CoAMetrics_processed_total{instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}} delta ratio"
    }
   ]
  },
  {
   "title": "CoA in ratio",
   "type": "timeseries",
   "description": "CoA accepted to send at last 5m",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(CoAMetrics_accepted_total{instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "delta {{instance}}"
    }
   ]
  },
  {
   "title": "CoA type in ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(CoAMetrics_activateService_accepted_total[$__rate_interval])",
     "legendFormat": "activateService"
    },
    {
     "expr": "rate(CoAMetrics_dataTunnelCreate_accepted_total[$__rate_interval])",
     "legendFormat": "dataTunnelCreate"
    },
    {
     "expr": "rate(CoAMetrics_dataTunnelUpLocation_accepted_total[$__rate_interval])",
     "legendFormat": "dataTunnelUpLocation"
    },
    {
     "expr": "rate(CoAMetrics_deactivateService_accepted_total[$__rate_interval])",
     "legendFormat": "deactivateService"
    },
    {
     "expr": "rate(CoAMetrics_disconnect_accepted_total[$__rate_interval])",
     "legendFormat": "disconnect"
    },
    {
     "expr": "rate(CoAMetrics_domainUpdate_accepted_total[$__rate_interval])",
     "legendFormat": "domainUpdate"
    },
    {
     "expr": "rate(CoAMetrics_filtersReauth_accepted_total[$__rate_interval])",
     "legendFormat": "filtersReauth"
    },
    {
     "expr": "rate(CoAMetrics_servicesReauth_accepted_total[$__rate_interval])",
     "legendFormat": "servicesReauth"
    }
   ]
  },
  { "title": "Accounting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Acct ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(AcctMetrics_command_processed_seconds_count{instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "acct {{instance}}"
    }
   ]
  },
  {
   "title": "Acct await",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "AcctMetrics_command_awaiting{instance=~\"$node\"}",
     "legendFormat": "acct {{instance}}"
    }
   ]
  },
  {
   "title": "Auth await",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "AuthMetrics_command_awaiting{instance=~\"$node\"}",
     "legendFormat": "auth {{instance}}"
    }
   ]
  },
  {
   "title": "MacAuth request count ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "rate(MacAuth_request_seconds_count{instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{request}} {{instance}}"
    }
   ]
  },
  { "title": "Freeradius", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Freeradius await",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "FreeradiusVerticle_auth_awaiting{instance=~\"$node\"}",
     "legendFormat": "auth {{instance}}"
    },
    {
     "expr": "FreeradiusVerticle_postauth_awaiting{instance=~\"$node\"}",
     "legendFormat": "postauth {{instance}}"
    }
   ]
  },
  {
   "title": "Freeradius auth rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(FreeradiusVerticle_auth_processed_seconds_count{instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "auth {{instance}}"
    }
   ]
  },
  { "title": "Data tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Data Tunnel Create processed ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "rate(CoAMetrics_dataTunnelCreate_processed_total{instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "processed {{instance}}"
    }
   ]
  },
  {
   "title": "Data Tunnel Create error ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
   "targets": [
    {
     "expr": "rate(CoAMetrics_dataTunnelCreate_error_total{instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "error {{instance}}"
    }
   ]
  },
  {
   "title": "Data Tunnel Create accepted ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 62 },
   "targets": [
    {
     "expr": "rate(CoAMetrics_dataTunnelCreate_accepted_total{instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "accepted {{instance}}"
    }
   ]
  },
  {
   "title": "OTT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ott processed  [5m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "rate(OttMetrics_processed_total{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{processed}} {{instance}}"
      }
     ]
    },
    {
     "title": "Ott error [5m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
     "targets": [
      {
       "expr": "rate(OttMetrics_error_total{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{error}} {{instance}}"
      }
     ]
    },
    {
     "title": "Ott received [5m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
     "targets": [
      {
       "expr": "rate(OttMetrics_received_total{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{received}} {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}