{
 "title": "NGW Metrics Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "node", "label": "node", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "NGW common metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "UpTime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(system_cpu_usage{instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "LA",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " sum(system_load_average_1m{instance=~\"$node\"} / system_cpu_count{instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Heap usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{instance=~\"$node\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{instance=~\"$node\", area=\"heap\"})"
      }
     ]
    },
    {
     "title": "File descriptors usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(process_files_open_files{instance=~\"$node\"})/sum(process_files_max_files{instance=~\"$node\"})*100"
      }
     ]
    },
    {
     "title": "Mysql connection usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hikaricp_connections{instance=~\"$node\"})/sum(hikaricp_connections_max{instance=~\"$node\"})*100"
      }
     ]
    },
    {
     "title": "log4j events counters",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "log4j2_events_total{instance=~\"$node\"}",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{instance=~\"$node\"}*1000"
      }
     ]
    }
   ]
  },
  {
   "title": "Outgoing SMS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outgoing SMS Request Type Distribution",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ngw_outgoing_sms_request_count_total{instance=~\"$node\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Outgoing SMS Response Distribution",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 2 },
     "targets": [
      {
       "expr": "ngw_outgoing_sms_response_count_total{instance=~\"$node\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Outgoing SMS Successful response rate",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 16, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(ngw_outgoing_sms_response_count_total{instance=~\"$node\",status='SUCCESS'}) or on() vector(0))/max(sum(ngw_outgoing_sms_response_count_total{instance=~\"$node\"}))",
       "legendFormat": "Outgoing SMS Successful response rate"
      }
     ]
    },
    {
     "title": "Outgoing SMS Handling Rate",
     "type": "gauge",
     "description": "If it's much bigger than 1, means that NGW is not working properly.",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(ngw_outgoing_sms_request_count_total{instance=~\"$node\"})/max(sum(ngw_outgoing_sms_response_count_total{instance=~\"$node\"}))) or on() vector(0)"
      }
     ]
    },
    {
     "title": "Outgoing SMS Successful response rate",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(ngw_outgoing_sms_response_count_total{instance=~\"$node\",status='SUCCESS'})/max(sum(ngw_outgoing_sms_response_count_total{instance=~\"$node\"}))) or on() vector(0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Outgoing Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outgoing Call Request Answers Distribution",
     "type": "piechart",
     "description": "Answer distribution for all outgoing calls.",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ngw_outgoing_call_execute_count_total{instance=~\"$node\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Outgoing Call Success Percentage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(ngw_outgoing_call_execute_count_total{instance=~\"$node\"})/max(sum(ngw_outgoing_call_execute_count_total{instance=~\"$node\",status='SUCCESS'})))"
      }
     ]
    }
   ]
  },
  {
   "title": "SMG Gateway metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "SMG Send Count Distribution",
     "type": "piechart",
     "description": "SMG CoA requests send distribution.",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "ngw_smg_radius_send_count_total{instance=~\"$node\"}",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "SMG Radius Receive Distribution Chart",
     "type": "piechart",
     "description": "SMG Radius Receive Distribution Chart.\nRadius packets that came as answers to CoA Requests.",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 4 },
     "targets": [
      {
       "expr": "ngw_smg_radius_receive_count_total{instance=~\"$node\"}",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "SMG Send-Receive CoA Rate",
     "type": "gauge",
     "description": "If this rate goes significantly higher than, it means\nthat NGW or SMG is not working properly.\n0 means that there are no requests for now.",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(ngw_smg_radius_send_count_total{instance=~\"$node\",result=\"ACK\"})/max(sum(ngw_smg_radius_receive_count_total{instance=~\"$node\"}))) or on() vector(0)"
      }
     ]
    },
    {
     "title": "SMG Radius Send-Receive CoA Rate",
     "type": "timeseries",
     "description": "If this rate goes upper than 1, it means that SMG or\nNGW is not working properly.\nIf it's absent - there is no requests to SMG or it's \ndisabled.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "(sum(ngw_smg_radius_send_count_total{instance=~\"$node\",result=\"ACK\"})/max(sum(ngw_smg_radius_receive_count_total{instance=~\"$node\"}))) or on() vector(0)",
       "legendFormat": "SMG Radius Send-Receive CoA Rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Incoming Event Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count of Incoming Events to Process",
     "type": "piechart",
     "description": "Number of Incoming Events to Process from Gateways.\nIs Requested means that this event was already requested by NGW client.",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "ngw_incoming_event_process_event_count_total{instance=~\"$node\"}",
       "legendFormat": "{{type}} - {{isRequested}}"
      }
     ]
    },
    {
     "title": "Count of Requests That is Awaiting Event",
     "type": "piechart",
     "description": "Count of Requests that is came from NGW clients.\nTag has subscription means that this requested was \nanswered before the request came to NGW.\nIt can mean that it was requested before, or action was performed earlier that NGW client has made a request.",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 5 },
     "targets": [
      {
       "expr": "ngw_incoming_event_process_request_count_total{instance=~\"$node\"}",
       "legendFormat": "{{type}} = {{hasSubscription}}"
      }
     ]
    },
    {
     "title": "Event to Request rate",
     "type": "gauge",
     "description": "Event to Request Rate.\nIf equals 1, everything is fine.\nIf less than 1, NGW is overloaded or gateway is overloaded.\nIf more than 1, events are coming faster than actual requests.",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(ngw_incoming_event_process_event_count_total{instance=~\"$node\"})/max(sum(ngw_incoming_event_process_request_count_total{instance=~\"$node\"}))) or on() vector(0)"
      }
     ]
    },
    {
     "title": "Event to Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "(sum(ngw_incoming_event_process_event_count_total{instance=~\"$node\"})/max(sum(ngw_incoming_event_process_request_count_total{instance=~\"$node\"})))",
       "legendFormat": "Event to Request Rate"
      }
     ]
    }
   ]
  },
  {
   "title": "SBC Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "SBC Successful Radius Packets count",
     "type": "gauge",
     "description": "Percent of a successful of send-receive",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(ngw_sbc_radius_processed_count_total{instance=~\"$node\",status='success'})/max(sum(ngw_sbc_radius_processed_count_total{instance=~\"$node\"}))) or on() vector(1)"
      }
     ]
    }
   ]
  },
  {
   "title": "Outgoing E-Mail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outgoing E-Mail Send Success Percentage",
     "type": "gauge",
     "description": "Percentage of successful e-mail without attachments.\n",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(sum(ngw_outgoing_mail_send_count_total{instance=~\"$node\",status=\"success\"})/max(sum(ngw_outgoing_mail_send_count_total{instance=~\"$node\"}))) or on() vector(1)"
      }
     ]
    },
    {
     "title": "Outgoing E-Mail With Attachments Send Success Percentage",
     "type": "gauge",
     "description": "Percentage of successful e-mail with attachments.\n",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(sum(ngw_outgoing_mail_send_with_attachment_count_total{instance=~\"$node\",status=\"success\"})/max(sum(ngw_outgoing_mail_send_with_attachment_count_total{instance=~\"$node\"}))) or on() vector(1)"
      }
     ]
    },
    {
     "title": "Outgoing mails sent rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 7 },
     "targets": [
      {
       "expr": "rate(ngw_outgoing_mail_send_count_total{instance=~\"$node\"}[5m])",
       "legendFormat": "{{status}}"
      },
      {
       "expr": "rate(ngw_outgoing_mail_send_with_attachment_count_total{instance=~\"$node\"}[5m])",
       "legendFormat": "with attach {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "WebSocket Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "WebSocket Failure Total Percentage",
     "type": "gauge",
     "description": "Percentage of overall WebSocket failures.\n",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(sum(ngw_api_session_websocket_failure_count_total{instance=~\"$node\"})/(sum(ngw_api_session_response_count_total{instance=~\"$node\"})+sum(ngw_api_session_error_count_total{instance=~\"$node\"}))) or on() vector(0)"
      }
     ]
    },
    {
     "title": "WebSocket Success Send-Receive Percentage",
     "type": "gauge",
     "description": "Percent of a successful of send-receive",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(ngw_api_session_response_count_total{instance=~\"$node\"})/max(sum(ngw_api_session_response_count_total{instance=~\"$node\"})+sum(ngw_api_session_websocket_failure_count_total{instance=~\"$node\"}))) or on() vector(1)"
      }
     ]
    },
    {
     "title": "NGW Erroneous responses distribution",
     "type": "piechart",
     "description": "NGW Erroneous responses distribution",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ngw_api_session_error_count_total{instance=~\"$node\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "WebSocket Failure Reason Distribution Chart",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ngw_api_session_websocket_failure_count_total{instance=~\"$node\"}",
       "legendFormat": "{{cause}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hikari pool metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections counters by state",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hikaricp_connections_active{instance=~\"$node\"}",
       "legendFormat": "Active connections"
      },
      {
       "expr": "hikaricp_connections_idle{instance=~\"$node\"}",
       "legendFormat": "Idle connections"
      },
      {
       "expr": "hikaricp_connections_pending{instance=~\"$node\"}",
       "legendFormat": "Pending connections"
      },
      {
       "expr": "hikaricp_connections_max{instance=~\"$node\"}",
       "legendFormat": "Max connections"
      }
     ]
    },
    {
     "title": "Connections acquire time by pool (rate)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_acquire_seconds_sum{instance=~\"$node\"}[5m]) / rate(hikaricp_connections_acquire_seconds_count{instance=~\"$node\"}[5m])",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Connections creation time by pool (rate)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_creation_seconds_sum{instance=~\"$node\"}[5m]) / rate(hikaricp_connections_creation_seconds_count{instance=~\"$node\"}[5m])",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Connections usage time by pool (rate)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_usage_seconds_sum{instance=~\"$node\"}[5m]) / rate(hikaricp_connections_usage_seconds_count{ instance=~\"$node\"}[5m])",
       "legendFormat": "{{pool}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Memory Total",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{instance=~\"$node\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{instance=~\"$node\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{instance=~\"$node\"})",
       "legendFormat": "max possible"
      }
     ]
    },
    {
     "title": "JVM heap",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{instance=~\"$node\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{instance=~\"$node\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{instance=~\"$node\", area=\"heap\"})",
       "legendFormat": "max possible"
      }
     ]
    },
    {
     "title": "JVM threads states counters",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_states_threads{instance=~\"$node\"}",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SKK Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "SKK SMS sent rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(ngw_skk_sms_sent_total{instance=~\"$node\"}[5m])",
       "legendFormat": "SMS sent rate"
      }
     ]
    },
    {
     "title": "SKK received statuses",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ngw_skk_received_statuses_total{instance=~\"$node\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "SKK received statuses",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ngw_skk_received_statuses_total{instance=~\"$node\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "SMS status requests",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ngw_skk_status_requests_total{instance=~\"$node\"}"
      }
     ]
    }
   ]
  }
 ]
}