{
 "title": "bruce",
 "description": "bruce",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(open_sessions{application=\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(system_cpu_usage{application=\"$application\"})"
    }
   ]
  },
  {
   "title": "LA",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(system_load_average_1m{application=\"$application\"} / system_cpu_count{application=\"$application\"})"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",area=\"heap\"})"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(process_files_open_files{application=\"$application\"})*100/sum(process_files_max_files{application=\"$application\"})"
    }
   ]
  },
  {
   "title": "log4j Events Counters",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "log4j2_events_total{application=\"$application\"}",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\"}*1000"
    }
   ]
  },
  { "title": "Job Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Schedule Attempts Status",
   "type": "piechart",
   "description": "Number of attempts to add a job to the Quartz scheduler. They may fail, for example, when the DB is down.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bruce_schedule_attempts_count_total{application=\"$application\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Fired Jobs Status",
   "type": "piechart",
   "description": "Number of attempts eltex-bruce did to start a scheduled job.",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bruce_fired_jobs_count_total{application=\"$application\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Status of Jobs Sent to eltex-jobs",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bruce_sent_jobs_count_total{application=\"$application\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Threads Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Server Thread Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jetty_threads_config_max{application=\"$application\"}",
     "legendFormat": "Config Max"
    },
    {
     "expr": "jetty_threads_config_min{application=\"$application\"}",
     "legendFormat": "Config Min"
    },
    {
     "expr": "jetty_threads_current{application=\"$application\"}",
     "legendFormat": "Actual"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{application=\"$application\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{application=\"$application\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{application=\"$application\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{application=\"$application\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_states_threads", "legendFormat": "{{state}}" }
   ]
  },
  { "title": "Memory Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "JVM Memory Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{application=\"$application\"}[1h])",
     "legendFormat": "process-1h"
    }
   ]
  },
  {
   "title": "LA (2m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(system_load_average_1m{application=\"$application\"}[2m]))",
     "legendFormat": "LA 1m avg"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{application=\"$application\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_files_max_files{application=\"$application\"}",
     "legendFormat": "max"
    }
   ]
  }
 ]
}