{
 "title": "NBI dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "node", "label": "node", "query": { "query": "label_values(instance)" } },
   {
    "name": "nbi_rate_interval",
    "label": "NBI rate interval",
    "query": "5s,10s,15s,30s,1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "NBI common metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "UpTime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{instance=~\"$node\"}",
       "legendFormat": "UpTime"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(system_cpu_usage{instance=~\"$node\"})",
       "legendFormat": "CPU usage"
      }
     ]
    },
    {
     "title": "LA",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(system_load_average_1m{instance=~\"$node\"}/system_cpu_count{instance=~\"$node\"})",
       "legendFormat": "LA"
      }
     ]
    },
    {
     "title": "Heap usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{instance=~\"$node\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{instance=~\"$node\", area=\"heap\"})",
       "legendFormat": "Heap usage"
      }
     ]
    },
    {
     "title": "File descriptors usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(process_files_open_files{instance=~\"$node\"})/sum(process_files_max_files{instance=~\"$node\"})*100",
       "legendFormat": "File descriptors usage"
      }
     ]
    },
    {
     "title": "Mysql connection usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hikaricp_connections{instance=~\"$node\"})/sum(hikaricp_connections_max{instance=~\"$node\"})*100",
       "legendFormat": "Mysql connection usage"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{instance=~\"$node\"}*1000",
       "legendFormat": "Start time"
      }
     ]
    }
   ]
  },
  {
   "title": "NBI request and response counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests by IP-address counters",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nbi_requests_ip_total{instance=~\"$node\"}",
       "legendFormat": "IP: {{ip}}"
      }
     ]
    },
    {
     "title": "Authentication requests statuses counters",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nbi_requests_auth_total{instance=~\"$node\"}",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Response time(s) max, age (15 min)",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nbi_response_time_seconds_max{instance=~\"$node\"}",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Response counters by ip, action, code",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nbi_response_code_total{instance=~\"$node\"}",
       "legendFormat": "{{ip}} | {{action}} | {{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NBI requests rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests rate [$nbi_rate_interval]",
     "type": "timeseries",
     "description": "Requests rate with NBI rate interval",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nbi_requests_total{instance=~\"$node\"}[$nbi_rate_interval])",
       "legendFormat": "Requests"
      }
     ]
    },
    {
     "title": "Requests rates by IP [$nbi_rate_interval]",
     "type": "timeseries",
     "description": "Requests rates by IP with NBI rate interval",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nbi_requests_ip_total{instance=~\"$node\"}[$nbi_rate_interval])",
       "legendFormat": "IP:{{ip}}"
      }
     ]
    },
    {
     "title": "Authentication requests rates by status codes [$nbi_rate_interval]",
     "type": "timeseries",
     "description": "Authentication requests rates by status codes with NBI rate interval",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nbi_requests_auth_total{instance=~\"$node\"}[$nbi_rate_interval])",
       "legendFormat": "{{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NBI responses rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response time (s) by action (age 15m)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "nbi_response_time_seconds{instance=~\"$node\"}",
       "legendFormat": "{{action}} {{quantile}}"
      }
     ]
    },
    {
     "title": "Response time (s) average by action (age 15m)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "nbi_response_time_seconds_sum{instance=~\"$node\"}/nbi_response_time_seconds_count{instance=~\"$node\"}",
       "legendFormat": "{{action}} {{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hikari pool metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections counters by state (summary all pools)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum(hikaricp_connections_active{instance=~\"$node\"})",
       "legendFormat": "Active connections"
      },
      {
       "expr": "sum(hikaricp_connections_idle{instance=~\"$node\"})",
       "legendFormat": "Idle connections"
      },
      {
       "expr": "sum(hikaricp_connections_pending{instance=~\"$node\"})",
       "legendFormat": "Pending connections"
      },
      {
       "expr": "sum(hikaricp_connections_max{instance=~\"$node\"})",
       "legendFormat": "Max connections"
      }
     ]
    },
    {
     "title": "Current connections counters",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections{instance=~\"$node\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Max possible connections",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections_max{instance=~\"$node\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Total timeout connections counter",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections_timeout_total{instance=~\"$node\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Connections acquire time by pool rate [$nbi_rate_interval]",
     "type": "timeseries",
     "description": "NBI rate interval is used",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_acquire_seconds_sum{instance=~\"$node\"}[$nbi_rate_interval]) / rate(hikaricp_connections_acquire_seconds_count{instance=~\"$node\"}[$nbi_rate_interval])",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Connections creation time by pool rate [$nbi_rate_interval]",
     "type": "timeseries",
     "description": "NBI rate interval is used",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_creation_seconds_sum{instance=~\"$node\"}[$nbi_rate_interval]) / rate(hikaricp_connections_creation_seconds_count{instance=~\"$node\"}[$nbi_rate_interval])",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Connections usage time by pool rate [$nbi_rate_interval]",
     "type": "timeseries",
     "description": "NBI rate interval is used",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_usage_seconds_sum{instance=~\"$node\"}[$nbi_rate_interval]) / rate(hikaricp_connections_usage_seconds_count{instance=~\"$node\"}[$nbi_rate_interval])",
       "legendFormat": "{{pool}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Memory Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{instance=~\"$node\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{instance=~\"$node\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{instance=~\"$node\"})",
       "legendFormat": "max possible"
      }
     ]
    },
    {
     "title": "JVM heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{instance=~\"$node\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{instance=~\"$node\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{instance=~\"$node\", area=\"heap\"})",
       "legendFormat": "max possible"
      }
     ]
    },
    {
     "title": "JVM threads states counters",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_states_threads{instance=~\"$node\"}",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Keycloak metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Authorization Requests",
     "type": "stat",
     "description": "SSO authorization requests counter",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nbi_sso_authorization_requests_total{instance=~\"$node\"}",
       "legendFormat": "Requests"
      }
     ]
    },
    {
     "title": " Authorization Requests Statuses",
     "type": "piechart",
     "description": "SSO request HTTP statuses counters",
     "gridPos": { "h": 9, "w": 10, "x": 5, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " nbi_sso_authorization_code_total{instance=~\"$node\"}",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "User Info Response HTTP Codes",
     "type": "piechart",
     "description": "Counter of http response codes from sso when requesting 'GET userInfo'",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nbi_sso_user_info_response_code_total{instance=~\"$node\"}",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Authorization Requests Rate [$nbi_rate_interval]",
     "type": "timeseries",
     "description": "SSO authorization requests rate ",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "rate(nbi_sso_authorization_requests_total{instance=~\"$node\"}[$nbi_rate_interval])",
       "legendFormat": "Requests"
      }
     ]
    },
    {
     "title": " Authorization Request Statuses Rates [$nbi_rate_interval]",
     "type": "timeseries",
     "description": "SSO requests rates by statuses",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 16 },
     "targets": [
      {
       "expr": "rate(nbi_sso_authorization_code_total{instance=~\"$node\"}[$nbi_rate_interval])",
       "legendFormat": "Status: {{code}}"
      }
     ]
    },
    {
     "title": "User Info Response Codes Rates [$nbi_rate_interval]",
     "type": "timeseries",
     "description": "Rates of SSO authorization http response codes when requesting 'GET userInfo'",
     "gridPos": { "h": 8, "w": 17, "x": 4, "y": 24 },
     "targets": [
      {
       "expr": "rate(nbi_sso_user_info_response_code_total{instance=~\"$node\"}[$nbi_rate_interval])",
       "legendFormat": "Code: {{code}}"
      }
     ]
    },
    {
     "title": "Authorization Processed Seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "nbi_sso_authorization_processed_seconds{instance=~\"$node\"}",
       "legendFormat": "Quantile: {{quantile}}"
      }
     ]
    },
    {
     "title": "User Info Authorization Processed Seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "nbi_sso_user_info_request_processed_seconds{instance=~\"$node\"}",
       "legendFormat": "Quantile: {{quantile}}"
      }
     ]
    },
    {
     "title": "Authorization Processed Seconds Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "nbi_sso_authorization_processed_seconds_max{instance=~\"$node\"}",
       "legendFormat": "Seconds"
      }
     ]
    },
    {
     "title": "User Info Processed Seconds Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "nbi_sso_user_info_request_processed_seconds_max{instance=~\"$node\"}",
       "legendFormat": "Seconds"
      }
     ]
    },
    {
     "title": "Authorization Processed Seconds Rates [$nbi_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(nbi_sso_authorization_processed_seconds{instance=~\"$node\"}[$nbi_rate_interval])",
       "legendFormat": "Quantile: {{quantile}}"
      }
     ]
    },
    {
     "title": "User Info Authorization Processed Seconds Rates [$nbi_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(nbi_sso_user_info_request_processed_seconds{instance=~\"$node\"}[$nbi_rate_interval])",
       "legendFormat": "Quantile: {{quantile}}"
      }
     ]
    },
    {
     "title": "Authorization Processed Seconds Count Rate [$nbi_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(nbi_sso_authorization_processed_seconds_count{instance=~\"$node\"}[$nbi_rate_interval])",
       "legendFormat": "Seconds"
      }
     ]
    },
    {
     "title": "User Info Processed Seconds Count Rate [$nbi_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(nbi_sso_user_info_request_processed_seconds_count{instance=~\"$node\"}[$nbi_rate_interval])",
       "legendFormat": "Seconds"
      }
     ]
    },
    {
     "title": "Authorization Processed Seconds Max Rate [$nbi_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(nbi_sso_authorization_processed_seconds_max{instance=~\"$node\"}[$nbi_rate_interval])",
       "legendFormat": "Seconds"
      }
     ]
    },
    {
     "title": "User Info Processed Seconds Max Rate [$nbi_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(nbi_sso_user_info_request_processed_seconds_max{instance=~\"$node\"}[$nbi_rate_interval])",
       "legendFormat": "Seconds"
      }
     ]
    },
    {
     "title": "Authorization Processed Seconds Sum Rate [$nbi_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(nbi_sso_authorization_processed_seconds_sum{instance=~\"$node\"}[$nbi_rate_interval])",
       "legendFormat": "Seconds"
      }
     ]
    },
    {
     "title": "User Info Processed Seconds Sum Rate [$nbi_rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(nbi_sso_user_info_request_processed_seconds_sum{instance=~\"$node\"}[$nbi_rate_interval])",
       "legendFormat": "Seconds"
      }
     ]
    }
   ]
  }
 ]
}