{
 "title": "Portal Dashboard",
 "time": { "from": "2022-06-22T06:11:49.320Z", "to": "2022-06-22T12:11:49.320Z" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   { "name": "verification_way", "label": "Verification way", "query": { "query": "label_values(verification_way)" } }
  ]
 },
 "panels": [
  {
   "title": "Process uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\"}"
    }
   ]
  },
  {
   "title": "Process CPU usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"$application\"}*100"
    }
   ]
  },
  {
   "title": "Process files open (current/max)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_files_open_files{application=\"$application\"}/process_files_max_files{application=\"$application\"}*100"
    }
   ]
  },
  {
   "title": "Authorization count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "portal_authorization_completed_total{application=\"$application\", status=\"success\"}",
     "legendFormat": "Success"
    },
    {
     "expr": "portal_authorization_completed_total{application=\"$application\", status=\"failed\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "HikariCP connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=\"$application\"}",
     "legendFormat": "active connections"
    },
    {
     "expr": "hikaricp_connections_idle{application=\"$application\"}",
     "legendFormat": "idle connections"
    },
    {
     "expr": "hikaricp_connections_pending{application=\"$application\"}",
     "legendFormat": "pending connections"
    },
    {
     "expr": "hikaricp_connections_max{application=\"$application\"}",
     "legendFormat": "max connections"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\"}*1000"
    }
   ]
  },
  {
   "title": "Rates",
   "type": "stat",
   "description": "Sums of per-second average rates of how the requests number is increasing over a period of time",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "req/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(portal_authentication_started_total{application=\"$application\"}[1h]))",
     "legendFormat": "Auth start"
    },
    {
     "expr": "sum(rate(portal_authentication_success_total{application=\"$application\"}[1h]))",
     "legendFormat": "Auth success"
    },
    {
     "expr": "rate(portal_authorization_completed_total{application=\"$application\"}[1h])",
     "legendFormat": "Authorization {{status}}"
    }
   ]
  },
  {
   "title": "Started Authentications (per 1h)",
   "type": "timeseries",
   "description": "Started authentications number divided by authentication type",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(portal_authentication_started_total{application=\"$application\"}[1h])) by (verification_way) ",
     "legendFormat": "{{authentication_type}}"
    }
   ]
  },
  {
   "title": "Success Authentications (per 1h)",
   "type": "timeseries",
   "description": "Successful authentications number divided by authentication type",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(portal_authentication_success_total{application=\"$application\"}[1h])) by (verification_way)",
     "legendFormat": "{{authentication_type}}"
    }
   ]
  },
  {
   "title": "Completed Authorizations (per 1h)",
   "type": "timeseries",
   "description": "Completed authorizations number divided by status",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(portal_authorization_completed_total{application=\"$application\"}[1h])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Rates",
   "type": "timeseries",
   "description": "Sums of per-second average rates of how the requests number is increasing over a period of time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(portal_authentication_started_total{application=\"$application\"}[1h]))",
     "legendFormat": "Auth start"
    },
    {
     "expr": "sum(rate(portal_authentication_success_total{application=\"$application\"}[1h]))",
     "legendFormat": "Auth success"
    },
    {
     "expr": "rate(portal_authorization_completed_total{application=\"$application\"}[1h])",
     "legendFormat": "Authorization {{status}}"
    }
   ]
  }
 ]
}