{
 "title": "EMS dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "node", "label": "node", "query": { "query": "label_values(instance)" } },
   {
    "name": "ems_interval",
    "label": "EMS interval",
    "query": "10s,15s,30s,1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "EMS common metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "panels": [
    {
     "title": "UpTime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "process_uptime_seconds{instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(system_cpu_usage{instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "LA",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " sum(system_load_average_1m{instance=~\"$node\"} / system_cpu_count{instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Heap usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{instance=~\"$node\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{instance=~\"$node\", area=\"heap\"})"
      }
     ]
    },
    {
     "title": "File descriptors usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(process_files_open_files{instance=~\"$node\"})/sum(process_files_max_files{instance=~\"$node\"})*100"
      }
     ]
    },
    {
     "title": "Mysql connection usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hikaricp_connections{instance=~\"$node\"})/sum(hikaricp_connections_max{instance=~\"$node\"})*100"
      }
     ]
    },
    {
     "title": "Alerts to be sent to GUI in queue",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ems_metric_alert_queue_size{instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "targets": [
      {
       "expr": "process_start_time_seconds{instance=~\"$node\"}*1000"
      }
     ]
    },
    {
     "title": "Alerts in cache",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ems_metric_alerts_in_cache{instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "Alerts without handler",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ems_metric_alerts_without_handler{instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "Number service session",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ems_metric_service_sessions{instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "Active async process",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ems_metric_async_process_active{instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "Devices counters by type, protocol, OTT-mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ems_device_count{instance=~\"$node\"}",
       "legendFormat": "{{full_type}} | {{protocol}} | {{ott_mode}}"
      }
     ]
    },
    {
     "title": "Number GUI sessions",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ems_metric_gui_sessions{instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "Total number of devices",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 5, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ems_device_count{instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Devices counter by types",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ems_device_count{instance=~\"$node\"}",
       "legendFormat": "{{full_type}} | {{protocol}} | {{ott_mode}}"
      }
     ]
    },
    {
     "title": "Async process",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ems_metric_async_process_current_queue_size{instance=~\"$node\"}",
       "legendFormat": "Async process queue size"
      },
      {
       "expr": "ems_metric_async_process_active{instance=~\"$node\"}",
       "legendFormat": "Approximate number of threads that are actively executing tasks"
      }
     ]
    },
    {
     "title": "Async started processes types",
     "type": "piechart",
     "description": "Number and percent of started async processes by type.",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ems_metric_async_process_starting_by_type_total{instance=~\"$node\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Async started processes by type (increase 15m)",
     "type": "timeseries",
     "description": "Async started processes by type (increase 15m).\n\nincrease() function calculates the difference between the last and the first raw sample on the selected time range.",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(ems_metric_async_process_starting_by_type_total{instance=~\"$node\"}[15m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Async finished processes statuses by type (see descr)",
     "type": "piechart",
     "description": "(ru) Посмотреть процентное и количественное соотношение статусов завершения для одной конкретной задачи (успехов к ошибкам и тд) можно, выделив в таблице (legend графика) только относящиеся к этой задаче строки.",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ems_metric_async_process_finished_status_by_type_total{instance=~\"$node\"}",
       "legendFormat": "{{type}} | {{status}}"
      }
     ]
    },
    {
     "title": "Async finished processes statuses by type (increase 15m)",
     "type": "timeseries",
     "description": "(ru) Посмотреть количественное соотношение статусов завершения для конкретной задачи (успехов к ошибкам и тд) можно, выделив в таблице (legend графика) только относящиеся к этой задаче строки.\n\nФункция increase() вычисляет увеличение временного ряда в векторе диапазона [15 мин].",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(ems_metric_async_process_finished_status_by_type_total{instance=~\"$node\"}[15m])",
       "legendFormat": "{{type}} | {{status}}"
      }
     ]
    },
    {
     "title": "Async running (started - finished) processes",
     "type": "stat",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ems_metric_async_process_starting_by_type_total{instance=~\"$node\"}) by (type) - sum(ems_metric_async_process_finished_status_by_type_total{instance=~\"$node\"}) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Async running (started - finished) processes (increase 15m)",
     "type": "timeseries",
     "description": "Async running (started - finished) processes by type (increase 15m).\n\nincrease() function calculates the difference between the last and the first raw sample on the selected time range.",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(ems_metric_async_process_starting_by_type_total{instance=~\"$node\"}[15m])) by (type) - sum(increase(ems_metric_async_process_finished_status_by_type_total{instance=~\"$node\"}[15m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Northbound requests (total count)",
     "type": "piechart",
     "description": "The diagram represents total count requests to the northbound API for each command.",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "northbound_requests_total{instance=~\"$node\"}",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Northbound requests (total count, increase 5m)",
     "type": "timeseries",
     "description": "The diagram represents total count requests to the northbound API for each command.",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 47 },
     "targets": [
      {
       "expr": "increase(northbound_requests_total{instance=~\"$node\"}[5m])",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Northbound requests (action | status)",
     "type": "piechart",
     "description": "The diagram represents total count with status code requests to the northbound API for each command.",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "northbound_response_code_total{instance=~\"$node\"}",
       "legendFormat": "{{action}} | {{status}}"
      }
     ]
    },
    {
     "title": "Northbound requests (action | status, increase 5m)",
     "type": "timeseries",
     "description": "The diagram represents total count with code requests to the northbound API for each command.",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 55 },
     "targets": [
      {
       "expr": "increase(northbound_response_code_total{instance=~\"$node\"}[5m])",
       "legendFormat": "{{action}} | {{status}}"
      }
     ]
    },
    {
     "title": "Northbound time requests (sum)",
     "type": "piechart",
     "description": "The sum of all values for each request",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "northbound_response_time_seconds_sum{instance=~\"$node\"}",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Northbound time requests (action | quantile)",
     "type": "timeseries",
     "description": "Shows us the time that is enough to complete 50%, 95% and 99% of requests for each action.",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "northbound_response_time_seconds{instance=~\"$node\"}",
       "legendFormat": "{{action}} | {{quantile}}"
      }
     ]
    },
    {
     "title": "Northbound time requests (count)",
     "type": "piechart",
     "description": "The count of all values for each action",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 71 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "northbound_response_time_seconds_count{instance=~\"$node\"}",
       "legendFormat": "{{action}}"
      }
     ]
    }
   ]
  },
  {
   "title": "EMS handlers metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Handlers queue size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ems_handler_queue_size{instance=~\"$node\"}",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Monitors process time (age 24 hours)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ems_monitor_process_s_seconds_sum{instance=~\"$node\"}/ems_monitor_process_s_seconds_count{instance=~\"$node\"}",
       "legendFormat": "{{monitor}} {{status}}"
      }
     ]
    },
    {
     "title": "Handlers requests counters (increase 15m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(ems_handler_total_requests{instance=~\"$node\"}[15m])",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Handlers work time (increase 15m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(ems_handler_work_time_seconds{instance=~\"$node\"}[15m])",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Handlers errors (increase 15m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "increase(ems_handler_errors{instance=~\"$node\"}[15m])",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Handlers dropped requests (increase 15m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "increase(ems_handler_dropped_requests{instance=~\"$node\"}[15m])",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Handler error count",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ems_handler_errors{instance=~\"$node\"}",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Handler dropped requests count",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ems_handler_dropped_requests{instance=~\"$node\"}",
       "legendFormat": "{{handler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hikari pool metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections counters by state (summary all pools)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(hikaricp_connections_active{instance=~\"$node\"})",
       "legendFormat": "Active connections"
      },
      {
       "expr": "sum(hikaricp_connections_idle{instance=~\"$node\"})",
       "legendFormat": "Idle connections"
      },
      {
       "expr": "sum(hikaricp_connections_pending{instance=~\"$node\"})",
       "legendFormat": "Pending connections"
      },
      {
       "expr": "sum(hikaricp_connections_max{instance=~\"$node\"})",
       "legendFormat": "Max connections"
      }
     ]
    },
    {
     "title": "Hikari current connections counters",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections{instance=~\"$node\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Max possible connections",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections_max{instance=~\"$node\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Total timeout connections counter",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections_timeout_total{instance=~\"$node\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Connections acquire time by pool (rate 5m)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_acquire_seconds_sum{instance=~\"$node\"}[5m]) / rate(hikaricp_connections_acquire_seconds_count{instance=~\"$node\"}[5m])",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Connections creation time by pool (rate 5m)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_creation_seconds_sum{instance=~\"$node\"}[5m]) / rate(hikaricp_connections_creation_seconds_count{instance=~\"$node\"}[5m])",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Connections usage time by pool (rate 5m)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_usage_seconds_sum{instance=~\"$node\"}[5m]) / rate(hikaricp_connections_usage_seconds_count{ instance=~\"$node\"}[5m])",
       "legendFormat": "{{pool}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Memory Total",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{instance=~\"$node\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{instance=~\"$node\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{instance=~\"$node\"})",
       "legendFormat": "max possible"
      }
     ]
    },
    {
     "title": "JVM heap",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{instance=~\"$node\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{instance=~\"$node\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{instance=~\"$node\", area=\"heap\"})",
       "legendFormat": "max possible"
      }
     ]
    },
    {
     "title": "JVM threads states counters",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_states_threads{instance=~\"$node\"}",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Geo-Clustering",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tree Object Associations (action, increase $ems_interval)",
     "type": "timeseries",
     "description": "Tree Object Associations Actions Increase",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "increase(ems_metric_tree_object_associations_total{instance=~\"$node\"}[$ems_interval])",
       "legendFormat": "{{action}} | {{service_id}}"
      }
     ]
    },
    {
     "title": "Tree Object Associations (action, rate $ems_interval)",
     "type": "timeseries",
     "description": "Tree Object Associations Actions Rate",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "rate(ems_metric_tree_object_associations_total{instance=~\"$node\"}[$ems_interval])",
       "legendFormat": "{{action}} | {{service_id}}"
      }
     ]
    }
   ]
  }
 ]
}