{
 "title": "Licensing",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(host)" } }
  ]
 },
 "panels": [
  {
   "title": "ELM Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "license_elm_available{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "License expire date",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "license_elm_expired_date{instance=\"$instance\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active endpoints count in time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hazelcast_endpoints_unique_per_day_size{instance=\"$instance\"}",
     "legendFormat": "current active endpoints"
    },
    {
     "expr": "license_endpoints_max_size{instance=\"$instance\"}",
     "legendFormat": "license limit"
    }
   ]
  },
  {
   "title": "License limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "license_endpoints_max_size{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current active endpoints count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hazelcast_endpoints_unique_per_day_size{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free endpoints in license",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(license_endpoints_max_size{instance=\"$instance\"}) - sum(hazelcast_endpoints_unique_per_day_size{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "License usage (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hazelcast_endpoints_unique_per_day_size{instance=\"$instance\"})/sum(license_endpoints_max_size{instance=\"$instance\"})*100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}