{
 "title": "MS AD",
 "description": "Метрики работы c библиотекой взаимодействия с MS AD.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(host)" } }
  ]
 },
 "panels": [
  { "title": "Authentication counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success auth count total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "auth_successful_count_total{application=\"Ovis\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "auth_successful_count_total{application=\"Ovis\",instance=\"$instance\"}",
     "legendFormat": "Success"
    },
    {
     "expr": "auth_timeout_count_total{application=\"Ovis\",instance=\"$instance\"}",
     "legendFormat": "Timeout"
    },
    {
     "expr": "auth_failed_count_total{application=\"Ovis\",instance=\"$instance\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Auth counts (rate)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(auth_successful_count_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "success auth count"
    },
    {
     "expr": "rate(auth_failed_count_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "failed auth count "
    },
    {
     "expr": "rate(auth_timeout_count_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "timeout error count"
    }
   ]
  },
  {
   "title": "Failed auth count total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "auth_failed_count_total{application=\"Ovis\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timeout auth count total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "auth_timeout_count_total{application=\"Ovis\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Authentication duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Authentication duration",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "auth_process_time_seconds{quantile=\"0.5\",instance=\"$instance\"} ",
     "legendFormat": "quantile = 0.5"
    },
    {
     "expr": "auth_process_time_seconds{quantile=\"0.95\",instance=\"$instance\"}",
     "legendFormat": "quantile = 0.95"
    },
    {
     "expr": "auth_process_time_seconds{quantile=\"0.99\",instance=\"$instance\"}",
     "legendFormat": "quantile = 0.99"
    }
   ]
  }
 ]
}