{
 "title": "RADIUS Dashboard",
 "description": "RADIUS Server monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(host)" } }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start time",
   "type": "stat",
   "description": "Time when the server was started",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeradius_start_time{instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Radius server status",
   "type": "stat",
   "description": "Value = 1 (default) means correct RADIUS work",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeradius_stats_error{instance=\"$instance\"}",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Authentication Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 5 },
   "options": {
    "content": "<h3 style=\"font-size: 17px;\"><b>Radius-packets processed by the server (rate)</b></h3>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 5 },
   "options": {
    "content": "<h3 style=\"font-size: 17px;\"><b>Radius-packets proxied to all home servers (rate)</b></h3>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Access packets received (rate per 5m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(freeradius_total_access_requests{instance=\"$instance\"}[5m])",
     "legendFormat": "Request"
    },
    {
     "expr": "rate(freeradius_total_access_accepts{instance=\"$instance\"}[5m])",
     "legendFormat": "Accepts"
    },
    {
     "expr": "rate(freeradius_total_access_rejects{instance=\"$instance\"}[5m])",
     "legendFormat": "Rejects"
    },
    {
     "expr": "rate(freeradius_total_access_challenges{instance=\"$instance\"}[5m])",
     "legendFormat": "Challenges"
    }
   ]
  },
  {
   "title": "Access packets proxied (rate per 5m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(freeradius_total_proxy_access_requests{instance=\"$instance\"}[5m])",
     "legendFormat": "Request"
    },
    {
     "expr": "rate(freeradius_total_proxy_access_accepts{instance=\"$instance\"}[5m])",
     "legendFormat": "Accepts"
    },
    {
     "expr": "rate(freeradius_total_proxy_access_rejects{instance=\"$instance\"}[5m])",
     "legendFormat": "Rejects"
    },
    {
     "expr": "rate(freeradius_total_proxy_access_challenges{instance=\"$instance\"}[5m])",
     "legendFormat": "Challenges"
    }
   ]
  },
  {
   "title": "Authentication responses packets sent (rate per 5m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(freeradius_total_auth_responses{instance=\"$instance\"}[5m])",
     "legendFormat": "Responses"
    }
   ]
  },
  {
   "title": "Authentication responses packets proxied (rate per 5m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(freeradius_total_proxy_auth_responses{instance=\"$instance\"}[5m])",
     "legendFormat": "Responses"
    }
   ]
  },
  {
   "title": "Authentication incorrect requests (rate per 5m)",
   "type": "timeseries",
   "description": "Authentication incorrect requests packets received",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(freeradius_total_auth_duplicate_requests{instance=\"$instance\"}[5m])",
     "legendFormat": "Duplicate"
    },
    {
     "expr": "rate(freeradius_total_auth_dropped_requests{instance=\"$instance\"}[5m])",
     "legendFormat": "Dropped"
    },
    {
     "expr": "rate(freeradius_total_auth_invalid_requests{instance=\"$instance\"}[5m])",
     "legendFormat": "Invalid"
    },
    {
     "expr": "rate(freeradius_total_auth_malformed_requests{instance=\"$instance\"}[5m])",
     "legendFormat": "Malformed"
    },
    {
     "expr": "rate(freeradius_total_auth_unknown_types{instance=\"$instance\"}[5m])",
     "legendFormat": "Unknown types"
    }
   ]
  },
  {
   "title": "Authentication incorrect requests (rate per 5m)",
   "type": "timeseries",
   "description": "Authentication incorrect requests recieved from home servers",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(freeradius_total_proxy_auth_duplicate_requests{instance=\"$instance\"}[5m])",
     "legendFormat": "Duplicate"
    },
    {
     "expr": "rate(freeradius_total_proxy_auth_dropped_requests{instance=\"$instance\"}[5m])",
     "legendFormat": "Dropped"
    },
    {
     "expr": "rate(freeradius_total_proxy_auth_invalid_requests{instance=\"$instance\"}[5m])",
     "legendFormat": "Invalid"
    },
    {
     "expr": "rate(freeradius_total_proxy_auth_malformed_requests{instance=\"$instance\"}[5m])",
     "legendFormat": "Malformed"
    },
    {
     "expr": "rate(freeradius_total_proxy_auth_unknown_types{instance=\"$instance\"}[5m])",
     "legendFormat": "Unknown types"
    }
   ]
  },
  { "title": "Queue Length Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "PPS Queue Length (in / out)",
   "type": "timeseries",
   "description": "Packets per second queue in/out lengths",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "freeradius_queue_pps_in{instance=\"$instance\"}",
     "legendFormat": "In"
    },
    {
     "expr": "freeradius_queue_pps_out{instance=\"$instance\"}",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Queue length by types",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "freeradius_queue_len_auth{instance=\"$instance\"}",
     "legendFormat": "Auth"
    },
    {
     "expr": "freeradius_queue_len_detail{instance=\"$instance\"}",
     "legendFormat": "Detail"
    },
    {
     "expr": "freeradius_queue_len_internal{instance=\"$instance\"}",
     "legendFormat": "Internal"
    },
    {
     "expr": "freeradius_queue_len_proxy{instance=\"$instance\"}",
     "legendFormat": "Proxy"
    }
   ]
  },
  { "title": "Authentication Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Requests",
   "type": "stat",
   "description": "Authentication incorrect requests packets received",
   "gridPos": { "h": 4, "w": 8, "x": 2, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeradius_total_access_requests{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "stat",
   "description": "Authentication responses packets sent",
   "gridPos": { "h": 4, "w": 8, "x": 14, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeradius_total_auth_responses{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Duplicate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeradius_total_auth_duplicate_requests{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Dropped",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeradius_total_auth_dropped_requests{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Access",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeradius_total_access_accepts{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Rejects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeradius_total_access_rejects{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Invalid",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeradius_total_auth_invalid_requests{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Malformed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeradius_total_auth_malformed_requests{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Challenges",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeradius_total_access_challenges"
    }
   ]
  },
  {
   "title": "Unknown Types",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeradius_total_auth_unknown_types{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Authentication Proxy Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Requests",
   "type": "stat",
   "description": "Authentication requests recieved from home servers",
   "gridPos": { "h": 4, "w": 8, "x": 2, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeradius_total_proxy_access_requests{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "stat",
   "description": "Authentication responses packets proxied",
   "gridPos": { "h": 4, "w": 8, "x": 14, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeradius_total_proxy_auth_responses{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Duplicate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeradius_total_proxy_auth_duplicate_requests{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Dropped",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeradius_total_proxy_auth_dropped_requests{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Access",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeradius_total_proxy_access_accepts{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Rejects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeradius_total_proxy_access_rejects{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Invalid",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeradius_total_auth_invalid_requests{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Malformed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeradius_total_proxy_auth_malformed_requests{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Challenges",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeradius_total_proxy_access_challenges"
    }
   ]
  },
  {
   "title": "Unknown Types",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "freeradius_total_proxy_auth_unknown_types{instance=\"$instance\"}"
    }
   ]
  }
 ]
}