{
 "title": "TACACS Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({application=\"Aquila\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Aquila Up Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"Aquila\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "License errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_reply_license_error_total{application=\"Aquila\", instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Main statistic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": " Accepted packets received rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(tacacs_requests_any_counter_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Request"
    },
    {
     "expr": "rate(tacacs_reply_pass_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Pass"
    },
    {
     "expr": "rate(tacacs_reply_fail_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Fail"
    },
    {
     "expr": "rate(tacacs_reply_other_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Response time of 50%, 95%, 99% of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tacacs_any_request_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "99%"
    },
    {
     "expr": "tacacs_any_request_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "95%"
    },
    {
     "expr": "tacacs_any_request_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 1, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_requests_any_counter_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reponses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_reply_any_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid",
   "type": "stat",
   "description": "Bad requests. Example: \"Bad secret\".",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_requests_invalid_counter_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Malformed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_requests_malformed_counter_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fail",
   "type": "stat",
   "description": "Reject reply.",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_reply_fail_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pass",
   "type": "stat",
   "description": "Accept reply.",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_reply_pass_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unknown",
   "type": "stat",
   "description": "Request from unknown network device.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_requests_unknown_device_counter_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Other",
   "type": "stat",
   "description": "Other responses. Example: GETPASS(request password from user) and others.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_reply_other_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Identity Sources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 26 },
   "options": {
    "content": "<h3 style=\"font-size:24px;text-align: center;\"><b>MS AD Identity Sources</b></h3>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 26 },
   "options": {
    "content": "<h3 style=\"font-size:24px;text-align: center;\"><b>LDAP Identity Sources</b></h3>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 26 },
   "options": {
    "content": "<h3 style=\"font-size:24px;text-align: center;\"><b>Local DB Identity Source</b></h3>"
   }
  },
  {
   "title": "User found",
   "type": "stat",
   "description": "Count of found users responses from MS AD identity sources.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_user_found_ms_ad_counter_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timed out",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_authenticate_ms_ad_timeout_counter_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "description": "Any unexpected erros from MS AD Identity sources.",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_authenticate_ms_ad_error_counter_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User found",
   "type": "stat",
   "description": "Count of found users responses from LDAP identity source.",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_user_found_ldap_counter_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timed out",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_authenticate_ldap_timeout_counter_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "description": "Any unxpected errors from LDAP identity sources.",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_authenticate_ldap_error_counter_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User found",
   "type": "stat",
   "description": "Count of found users responses from local DB identity source.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_user_found_local_counter_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time of 50%, 95%, 99% of auth MS AD requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tacacs_authenticate_ms_ad_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "99%"
    },
    {
     "expr": "tacacs_authenticate_ms_ad_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "95%"
    },
    {
     "expr": "tacacs_authenticate_ms_ad_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Response time of 50%, 95%, 99% of auth LDAP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tacacs_authenticate_ldap_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "99%"
    },
    {
     "expr": "tacacs_authenticate_ldap_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "95%"
    },
    {
     "expr": "tacacs_authenticate_ldap_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Response time of 50%, 95%, 99% of auth DB requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tacacs_authenticate_local_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "99%"
    },
    {
     "expr": "tacacs_authenticate_local_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "95%"
    },
    {
     "expr": "tacacs_authenticate_local_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Response time of 50%, 95%, 99% of find user in MS AD requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tacacs_find_user_ms_ad_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "99%"
    },
    {
     "expr": "tacacs_find_user_ms_ad_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "95%"
    },
    {
     "expr": "tacacs_find_user_ms_ad_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Response time of 50%, 95%, 99% of find user in LDAP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tacacs_find_user_ldap_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "99%"
    },
    {
     "expr": "tacacs_find_user_ldap_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "95%"
    },
    {
     "expr": "tacacs_find_user_ldap_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Response time of 50%, 95%, 99% of find user in local DB requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tacacs_find_user_local_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "99%"
    },
    {
     "expr": "tacacs_find_user_local_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "95%"
    },
    {
     "expr": "tacacs_find_user_local_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "50%"
    }
   ]
  },
  { "title": "Authentication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_authenticate_continue_request_timer_seconds_count{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "tacacs_authenticate_start_request_timer_seconds_count{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Password incorrect",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_authenticate_password_incorrect_counter_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fail",
   "type": "stat",
   "description": "Rejected requests.",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_reply_authenticate_fail_total {instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted authentification packets rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(authen_any{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Any"
    },
    {
     "expr": "rate(tacacs_authenticate_continue_request_timer_seconds_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Authentification Continue"
    },
    {
     "expr": "rate(tacacs_authenticate_start_request_timer_seconds_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Authentification Start"
    }
   ]
  },
  {
   "title": "Response time of 50%, 95%, 99% of LDAP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tacacs_authenticate_ldap_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "99%"
    },
    {
     "expr": "tacacs_authenticate_ldap_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "95%"
    },
    {
     "expr": "tacacs_authenticate_ldap_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "User not found",
   "type": "stat",
   "description": "On authentication, user not found in any identity source in identity sequence.",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_authenticate_user_not_found_counter_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Authorization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_authorize_request_timer_seconds_count{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User not found",
   "type": "stat",
   "description": "On authorization, user not found in any identity source in identity sequence.",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_authorize_user_not_found_counter_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fail",
   "type": "stat",
   "description": "Rejected requests.",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_reply_authorize_fail_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted authorization packets rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(tacacs_authorize_request_timer_seconds_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Any"
    }
   ]
  },
  {
   "title": "Response time of 50%, 95%, 99% of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tacacs_authorize_request_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "99%"
    },
    {
     "expr": "tacacs_authorize_request_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "95%"
    },
    {
     "expr": "tacacs_authorize_request_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Fail cmd",
   "type": "stat",
   "description": "Network device command rejected by command set.",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_authorize_command_fail_counter_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Accounting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tacacs_acct_request_timer_seconds_count{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted accounting packets rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(tacacs_acct_request_timer_seconds_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Any"
    }
   ]
  },
  {
   "title": "Response time of 50%, 95%, 99% of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tacacs_acct_request_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "99%"
    },
    {
     "expr": "tacacs_acct_request_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "95%"
    },
    {
     "expr": "tacacs_acct_request_timer_seconds{application=\"Aquila\", instance=\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "50%"
    }
   ]
  }
 ]
}